### ISSUE TITLE
States of type String have value 0 in channel weather

### ISSUE THREAD

**Issue by Vertumnus** [iobroker-community-adapters/ioBroker.worx#102]
The states _description_, _icon_ and _main_ have the value 0 in the channel _weather_. In the past there were more or less meaningfull values. I recognized that the states are the only ones of type String and the issue affects only those. The other states in the channel are numeric and the adapter fills them as expected.

I've debugged the problem in more detail and found out, that the cause is using the bit operator for _or_ (|) instead of the logical  operator for _or_ (||). See main.js -> https://github.com/iobroker-community-adapters/ioBroker.worx/blob/af83bef46f9acb1d733c2e00837a2aadef9b8308/main.js#L492

So, I will create a pull request for fixing this issue.

**Comment by MeisterTR** [comment]
done
