### ISSUE TITLE
Adapter doesn't reconnect after restored internet connection 

### ISSUE THREAD

**Issue by MKaiser96** [iobroker-community-adapters/ioBroker.worx#108]
I have a reconnection problem of the adapter after a lost internet connection has been restored. Today the internet connection got lost for about one hour. After the internet has been reconnectet, the adapter doesn't automatically reconnect to the worx server.  Therefore I have to restart the adapter manually.

The adapter should restart automatically when the internet connection has been restored.

**Comment by MeisterTR** [comment]
it could take some hours if you get data after inet was lost.
