### ISSUE TITLE
old version landroid-s works, new one not

### ISSUE THREAD

**Issue by marcuswaldeck** [iobroker-community-adapters/ioBroker.worx#17]
hi, in deutsch, die alte 2.xx version konnte ich verbinden, bei der neuen hapert es, da keine verbindung zum worx zustande kommt. 
alles neu installiert, node ab version 10.

debug log zeigt nichts an:

> 2019-07-26 21:29:47.722  - [32minfo[39m: host.All-In-One_RasPi object change system.adapter.worx.0
> 2019-07-26 21:29:47.725  - [32minfo[39m: worx.0 cleaned everything up...
> 2019-07-26 21:29:47.723  - [32minfo[39m: host.All-In-One_RasPi stopInstance system.adapter.worx.0
> 2019-07-26 21:29:47.723  - [32minfo[39m: host.All-In-One_RasPi stopInstance system.adapter.worx.0 killing pid 13471
> 2019-07-26 21:29:47.730  - [32minfo[39m: worx.0 cleaned everything up...
> 2019-07-26 21:29:47.778  - [32minfo[39m: host.All-In-One_RasPi instance system.adapter.worx.0 terminated with code 156 ()
> 2019-07-26 21:29:50.942  - [32minfo[39m: host.All-In-One_RasPi object change system.adapter.worx.0
> 2019-07-26 21:29:50.958  - [32minfo[39m: host.All-In-One_RasPi instance system.adapter.worx.0 started with pid 17632
> 2019-07-26 21:29:53.375  - [32minfo[39m: worx.0 States connected to redis: 127.0.0.1:6379
> 2019-07-26 21:29:53.447  - [32minfo[39m: worx.0 starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.worx, node: v10.16.0
> 2019-07-26 21:29:53.455  - [32minfo[39m: worx.0 config e-mail: XXXXXXX@email.de
> 2019-07-26 21:29:53.456  - [32minfo[39m: worx.0 config password: XXXXXXXXX

was kann ich ändern?

**Comment by MeisterTR** [comment]
Kannst du den Adapter mal auf Debug log stellen und erneut den log posten. Werde am Wochenende mal ein testsystem mit node 10 aufsetzen.

**Comment by marcuswaldeck** [comment]
Anfängerfrage, wie und wo stell ich das ein?
Hatte vorher node 8.1 drauf, dachte es liegt daran, daher habe ich auf 10 aktualisiert

**Comment by marcuswaldeck** [comment]
streiche den letzten post, habs gefunden...

der Adapter startet ganz normal, Host und Lebenszeichen sind auf "wahr", verbunden mit worx zeigt weiterhin "falsch" an.
das log ist hier:

> 

worx.0 | 2019-07-27 10:51:02.272 | silly | redis publish io.system.adapter.worx.0.outputCount {"val":8,"ack":true,"ts":1564217462265,"q":0,"from":"system.adapter.worx.0","lc":1564169010579}
-- | -- | -- | --
worx.0 | 2019-07-27 10:51:02.271 | silly | redis publish io.system.adapter.worx.0.inputCount {"val":0,"ack":true,"ts":1564217462264,"q":0,"from":"system.adapter.worx.0","lc":1564169010578}
worx.0 | 2019-07-27 10:51:02.270 | silly | redis publish io.system.adapter.worx.0.uptime {"val":92,"ack":true,"ts":1564217462263,"q":0,"from":"system.adapter.worx.0","lc":1564217462263}
worx.0 | 2019-07-27 10:51:02.270 | silly | redis publish io.system.adapter.worx.0.memHeapUsed {"val":14.79,"ack":true,"ts":1564217462262,"q":0,"from":"system.adapter.worx.0","lc":1564217462262}
worx.0 | 2019-07-27 10:51:02.269 | silly | redis publish io.system.adapter.worx.0.memHeapTotal {"val":31.58,"ack":true,"ts":1564217462260,"q":0,"from":"system.adapter.worx.0","lc":1564217387220}
worx.0 | 2019-07-27 10:51:02.268 | silly | redis publish io.system.adapter.worx.0.memRss {"val":48.09,"ack":true,"ts":1564217462259,"q":0,"from":"system.adapter.worx.0","lc":1564217387219}
worx.0 | 2019-07-27 10:51:02.268 | silly | redis publish io.system.adapter.worx.0.connected {"val":true,"ack":true,"ts":1564217462258,"q":0,"from":"system.adapter.worx.0","lc":1564217372247}
worx.0 | 2019-07-27 10:51:02.267 | silly | redis publish io.system.adapter.worx.0.alive {"val":true,"ack":true,"ts":1564217462256,"q":0,"from":"system.adapter.worx.0","lc":1564217372245}
worx.0 | 2019-07-27 10:50:47.261 | silly | redis publish io.system.adapter.worx.0.outputCount {"val":8,"ack":true,"ts":1564217447256,"q":0,"from":"system.adapter.worx.0","lc":1564169010579}
worx.0 | 2019-07-27 10:50:47.261 | silly | redis publish io.system.adapter.worx.0.inputCount {"val":0,"ack":true,"ts":1564217447255,"q":0,"from":"system.adapter.worx.0","lc":1564169010578}
worx.0 | 2019-07-27 10:50:47.260 | silly | redis publish io.system.adapter.worx.0.uptime {"val":77,"ack":true,"ts":1564217447253,"q":0,"from":"system.adapter.worx.0","lc":1564217447253}
worx.0 | 2019-07-27 10:50:47.260 | silly | redis publish io.system.adapter.worx.0.memHeapUsed {"val":14.7,"ack":true,"ts":1564217447252,"q":0,"from":"system.adapter.worx.0","lc":1564217447252}
worx.0 | 2019-07-27 10:50:47.260 | silly | redis publish io.system.adapter.worx.0.memHeapTotal {"val":31.58,"ack":true,"ts":1564217447250,"q":0,"from":"system.adapter.worx.0","lc":1564217387220}
worx.0 | 2019-07-27 10:50:47.259 | silly | redis publish io.system.adapter.worx.0.memRss {"val":48.09,"ack":true,"ts":1564217447249,"q":0,"from":"system.adapter.worx.0","lc":1564217387219}
worx.0 | 2019-07-27 10:50:47.259 | silly | redis publish io.system.adapter.worx.0.connected {"val":true,"ack":true,"ts":1564217447248,"q":0,"from":"system.adapter.worx.0","lc":1564217372247}
worx.0 | 2019-07-27 10:50:47.259 | silly | redis publish io.system.adapter.worx.0.alive {"val":true,"ack":true,"ts":1564217447246,"q":0,"from":"system.adapter.worx.0","lc":1564217372245}
worx.0 | 2019-07-27 10:50:32.257 | silly | redis publish io.system.adapter.worx.0.outputCount {"val":8,"ack":true,"ts":1564217432253,"q":0,"from":"system.adapter.worx.0","lc":1564169010579}
worx.0 | 2019-07-27 10:50:32.256 | silly | redis publish io.system.adapter.worx.0.inputCount {"val":0,"ack":true,"ts":1564217432252,"q":0,"from":"system.adapter.worx.0","lc":1564169010578}
worx.0 | 2019-07-27 10:50:32.256 | silly | redis publish io.system.adapter.worx.0.uptime {"val":62,"ack":true,"ts":1564217432251,"q":0,"from":"system.adapter.worx.0","lc":1564217432251}
worx.0 | 2019-07-27 10:50:32.256 | silly | redis publish io.system.adapter.worx.0.memHeapUsed {"val":14.59,"ack":true,"ts":1564217432250,"q":0,"from":"system.adapter.worx.0","lc":1564217432250}
worx.0 | 2019-07-27 10:50:32.256 | silly | redis publish io.system.adapter.worx.0.memHeapTotal {"val":31.58,"ack":true,"ts":1564217432249,"q":0,"from":"system.adapter.worx.0","lc":1564217387220}
worx.0 | 2019-07-27 10:50:32.255 | silly | redis publish io.system.adapter.worx.0.memRss {"val":48.09,"ack":true,"ts":1564217432248,"q":0,"from":"system.adapter.worx.0","lc":1564217387219}
worx.0 | 2019-07-27 10:50:32.255 | silly | redis publish io.system.adapter.worx.0.connected {"val":true,"ack":true,"ts":1564217432247,"q":0,"from":"system.adapter.worx.0","lc":1564217372247}
worx.0 | 2019-07-27 10:50:32.255 | silly | redis publish io.system.adapter.worx.0.alive {"val":true,"ack":true,"ts":1564217432246,"q":0,"from":"system.adapter.worx.0","lc":1564217372245}
worx.0 | 2019-07-27 10:50:17.246 | silly | redis publish io.system.adapter.worx.0.outputCount {"val":8,"ack":true,"ts":1564217417242,"q":0,"from":"system.adapter.worx.0","lc":1564169010579}
worx.0 | 2019-07-27 10:50:17.245 | silly | redis publish io.system.adapter.worx.0.inputCount {"val":0,"ack":true,"ts":1564217417241,"q":0,"from":"system.adapter.worx.0","lc":1564169010578}
worx.0 | 2019-07-27 10:50:17.245 | silly | redis publish io.system.adapter.worx.0.uptime {"val":47,"ack":true,"ts":1564217417240,"q":0,"from":"system.adapter.worx.0","lc":1564217417240}
worx.0 | 2019-07-27 10:50:17.245 | silly | redis publish io.system.adapter.worx.0.memHeapUsed {"val":14.49,"ack":true,"ts":1564217417239,"q":0,"from":"system.adapter.worx.0","lc":1564217417239}
worx.0 | 2019-07-27 10:50:17.245 | silly | redis publish io.system.adapter.worx.0.memHeapTotal {"val":31.58,"ack":true,"ts":1564217417238,"q":0,"from":"system.adapter.worx.0","lc":1564217387220}
worx.0 | 2019-07-27 10:50:17.244 | silly | redis publish io.system.adapter.worx.0.memRss {"val":48.09,"ack":true,"ts":1564217417237,"q":0,"from":"system.adapter.worx.0","lc":1564217387219}
worx.0 | 2019-07-27 10:50:17.244 | silly | redis publish io.system.adapter.worx.0.connected {"val":true,"ack":true,"ts":1564217417236,"q":0,"from":"system.adapter.worx.0","lc":1564217372247}
worx.0 | 2019-07-27 10:50:17.244 | silly | redis publish io.system.adapter.worx.0.alive {"val":true,"ack":true,"ts":1564217417235,"q":0,"from":"system.adapter.worx.0","lc":1564217372245}
worx.0 | 2019-07-27 10:50:02.233 | silly | redis publish io.system.adapter.worx.0.outputCount {"val":8,"ack":true,"ts":1564217402229,"q":0,"from":"system.adapter.worx.0","lc":1564169010579}
worx.0 | 2019-07-27 10:50:02.233 | silly | redis publish io.system.adapter.worx.0.inputCount {"val":0,"ack":true,"ts":1564217402228,"q":0,"from":"system.adapter.worx.0","lc":1564169010578}
worx.0 | 2019-07-27 10:50:02.233 | silly | redis publish io.system.adapter.worx.0.uptime {"val":32,"ack":true,"ts":1564217402227,"q":0,"from":"system.adapter.worx.0","lc":1564217402227}
worx.0 | 2019-07-27 10:50:02.232 | silly | redis publish io.system.adapter.worx.0.memHeapUsed {"val":14.4,"ack":true,"ts":1564217402226,"q":0,"from":"system.adapter.worx.0","lc":1564217402226}
worx.0 | 2019-07-27 10:50:02.232 | silly | redis publish io.system.adapter.worx.0.memHeapTotal {"val":31.58,"ack":true,"ts":1564217402225,"q":0,"from":"system.adapter.worx.0","lc":1564217387220}
worx.0 | 2019-07-27 10:50:02.232 | silly | redis publish io.system.adapter.worx.0.memRss {"val":48.09,"ack":true,"ts":1564217402224,"q":0,"from":"system.adapter.worx.0","lc":1564217387219}
worx.0 | 2019-07-27 10:50:02.231 | silly | redis publish io.system.adapter.worx.0.connected {"val":true,"ack":true,"ts":1564217402222,"q":0,"from":"system.adapter.worx.0","lc":1564217372247}
worx.0 | 2019-07-27 10:50:02.231 | silly | redis publish io.system.adapter.worx.0.alive {"val":true,"ack":true,"ts":1564217402221,"q":0,"from":"system.adapter.worx.0","lc":1564217372245}
worx.0 | 2019-07-27 10:49:47.228 | silly | redis publish io.system.adapter.worx.0.outputCount {"val":8,"ack":true,"ts":1564217387224,"q":0,"from":"system.adapter.worx.0","lc":1564169010579}
worx.0 | 2019-07-27 10:49:47.228 | silly | redis publish io.system.adapter.worx.0.inputCount {"val":0,"ack":true,"ts":1564217387223,"q":0,"from":"system.adapter.worx.0","lc":1564169010578}
worx.0 | 2019-07-27 10:49:47.227 | silly | redis publish io.system.adapter.worx.0.uptime {"val":17,"ack":true,"ts":1564217387222,"q":0,"from":"system.adapter.worx.0","lc":1564217387222}
worx.0 | 2019-07-27 10:49:47.227 | silly | redis publish io.system.adapter.worx.0.memHeapUsed {"val":14.29,"ack":true,"ts":1564217387221,"q":0,"from":"system.adapter.worx.0","lc":1564217387221}
worx.0 | 2019-07-27 10:49:47.227 | silly | redis publish io.system.adapter.worx.0.memHeapTotal {"val":31.58,"ack":true,"ts":1564217387220,"q":0,"from":"system.adapter.worx.0","lc":1564217387220}
worx.0 | 2019-07-27 10:49:47.227 | silly | redis publish io.system.adapter.worx.0.memRss {"val":48.09,"ack":true,"ts":1564217387219,"q":0,"from":"system.adapter.worx.0","lc":1564217387219}
worx.0 | 2019-07-27 10:49:47.226 | silly | redis publish io.system.adapter.worx.0.connected {"val":true,"ack":true,"ts":1564217387218,"q":0,"from":"system.adapter.worx.0","lc":1564217372247}
worx.0 | 2019-07-27 10:49:47.226 | silly | redis publish io.system.adapter.worx.0.alive {"val":true,"ack":true,"ts":1564217387217,"q":0,"from":"system.adapter.worx.0","lc":1564217372245}
worx.0 | 2019-07-27 10:49:32.266 | silly | redis mget 3 3
worx.0 | 2019-07-27 10:49:32.259 | silly | redis publish io.system.adapter.worx.0.outputCount {"val":8,"ack":true,"ts":1564217372259,"q":0,"from":"system.adapter.worx.0","lc":1564169010579}
worx.0 | 2019-07-27 10:49:32.258 | silly | redis publish io.system.adapter.worx.0.inputCount {"val":0,"ack":true,"ts":1564217372258,"q":0,"from":"system.adapter.worx.0","lc":1564169010578}
worx.0 | 2019-07-27 10:49:32.256 | silly | redis publish io.system.adapter.worx.0.uptime {"val":2,"ack":true,"ts":1564217372256,"q":0,"from":"system.adapter.worx.0","lc":1564217372256}
worx.0 | 2019-07-27 10:49:32.254 | silly | redis publish io.system.adapter.worx.0.memHeapUsed {"val":14.71,"ack":true,"ts":1564217372254,"q":0,"from":"system.adapter.worx.0","lc":1564217372254}
worx.0 | 2019-07-27 10:49:32.252 | silly | redis publish io.system.adapter.worx.0.memHeapTotal {"val":20.58,"ack":true,"ts":1564217372252,"q":0,"from":"system.adapter.worx.0","lc":1564217372252}
worx.0 | 2019-07-27 10:49:32.250 | silly | redis publish io.system.adapter.worx.0.memRss {"val":46.47,"ack":true,"ts":1564217372250,"q":0,"from":"system.adapter.worx.0","lc":1564217372250}
worx.0 | 2019-07-27 10:49:32.248 | silly | redis publish io.system.adapter.worx.0.connected {"val":true,"ack":true,"ts":1564217372247,"q":0,"from":"system.adapter.worx.0","lc":1564217372247}
worx.0 | 2019-07-27 10:49:32.245 | silly | redis publish io.system.adapter.worx.0.alive {"val":true,"ack":true,"ts":1564217372245,"q":0,"from":"system.adapter.worx.0","lc":1564217372245}
worx.0 | 2019-07-27 10:49:32.241 | silly | redis keys 3 *.logging
worx.0 | 2019-07-27 10:49:32.228 | silly | redis psubscribe io.worx.0.checkLogging
worx.0 | 2019-07-27 10:49:32.214 | info | config password: 88888888
worx.0 | 2019-07-27 10:49:32.213 | info | config e-mail: marcuswaldeck@email.de
worx.0 | 2019-07-27 10:49:32.204 | info | starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.worx, node: v10.16.0
worx.0 | 2019-07-27 10:49:32.157 | silly | redis get system.adapter.worx.0.alive ok: {"val":false,"ack":true,"ts":1564217339234,"q":0,"from":"system.host.All-In-One_RasPi","lc":1564217339200}
worx.0 | 2019-07-27 10:49:32.132 | info | States connected to redis: 127.0.0.1:6379
worx.0 | 2019-07-27 10:49:32.126 | debug | statesDB connected
worx.0 | 2019-07-27 10:49:32.096 | debug | objectDB connected

**Comment by MeisterTR** [comment]
der log sagt so nur sehr wenig aus, stell mal nicht auf silly sondern nur auf debug und einen etwas längeren logauszug

**Comment by marcuswaldeck** [comment]
da kommt ja nichts weiter. in 5 minuten nur das hier:

> 

info.0 | 2019-07-31 17:53:26.246 | info | Popup-News readed...
-- | -- | -- | --
worx.0 | 2019-07-31 17:49:02.681 | info | config password: XXXXXX
worx.0 | 2019-07-31 17:49:02.681 | info | config e-mail: XXXXXXX@email.de
worx.0 | 2019-07-31 17:49:02.675 | info | starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.worx, node: v10.16.0
worx.0 | 2019-07-31 17:49:02.635 | info | States connected to redis: 127.0.0.1:6379
worx.0 | 2019-07-31 17:49:02.628 | debug | statesDB connected
worx.0 | 2019-07-31 17:49:02.582 | debug | objectDB connected
host.All-In-One_RasPi | 2019-07-31 17:49:00.061 | info | instance system.adapter.worx.0 started with pid 29062
host.All-In-One_RasPi | 2019-07-31 17:49:00.040 | info | object change system.adapter.worx.0

**Comment by MeisterTR** [comment]
Sehr merkwürdig, ich brauche ein paar Tage um ein test file zu erstellen. Mfg

**Comment by MeisterTR** [comment]
bitte mal debug mit der 0.4.0 machen

**Comment by marcuswaldeck** [comment]
keine Änderung :-(


worx.0 | 2019-08-04 08:47:03.971 | info | starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.worx, node: v10.16.0
-- | -- | -- | --
worx.0 | 2019-08-04 08:47:03.900 | info | States connected to redis: 127.0.0.1:6379
worx.0 | 2019-08-04 08:47:03.894 | debug | statesDB connected
worx.0 | 2019-08-04 08:47:03.855 | debug | objectDB connected
host.All-In-One_RasPi | 2019-08-04 08:47:00.604 | info | instance system.adapter.worx.0 started with pid 6466
host.All-In-One_RasPi | 2019-08-04 08:46:58.101 | info | instance system.adapter.worx.0 terminated with code 156 ()
worx.0 | 2019-08-04 08:46:58.077 | info | cleaned everything up...
worx.0 | 2019-08-04 08:46:58.063 | info | cleaned everything up...
host.All-In-One_RasPi | 2019-08-04 08:46:58.059 | info | stopInstance system.adapter.worx.0 killing pid 29062
host.All-In-One_RasPi | 2019-08-04 08:46:58.059 | info | stopInstance system.adapter.worx.0
host.All-In-One_RasPi | 2019-08-04 08:46:58.059 | info | object change system.adapter.worx.0
host.All-In-One_RasPi | 2019-08-04 08:46:29.798 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
iobroker | 2019-08-04 08:46:29.147 | info | exit 0
iobroker | 2019-08-04 08:46:29.056 | info | upload [0] worx.admin /opt/iobroker/node_modules/iobroker.worx/admin/admin.d.ts admin.d.ts video/mp2t

**Comment by MeisterTR** [comment]
installiere nochmal von git, ich habe noch mehr log Einträge hinzugefügt um zu schauen wo er aussteigt. mfg
