### ISSUE TITLE
Unzutreffende Warnung in der Logdatei: your connection is blocked

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#203]
Bei jedem Einschalten der Worx Instanz kommt folgende Warnung im Log:

_maybe your connection is blocked from Worx, please test start button, if not working, try again in 24h
DON`T CONTACT THE OFFICIAL WORX SUPPORT BECAUSE THIS IS AN INOFFICAL APP !!!!!!!!!!!_

[WorxLog.html.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/6109114/WorxLog.html.txt)

Ein korrektes Arbeiten mit dem Adapter ist trotzdem möglich.

Adapter version: 1.2.9
JS-Controller version: 3.1.6
Node version: 12.18.4
Operating system: Raspbian GNU/Linux 10 (buster) 5.4.51-v7l+

**Comment by MeisterTR** [comment]
das ist eine Sicherheitsmaßnahme, da ich mehrfach davon gehört habe dass leute den offiziellen Support um hilfe gebeten haben
