### ISSUE TITLE
Objekt 'batteryChargeCycle' wird nicht zurückgesetzt

### ISSUE THREAD

**Issue by darkman242** [iobroker-community-adapters/ioBroker.worx#217]
Ich habe für meinen Roboter einen größeren Akku gekauft. In der Worx-App habe ich die Statistik 'Ladungen/Zyklen' zurückgesetzt (ging dort also mit 0 los). Im Adpater hat er dies nicht übernommen und auf 0 gesetzt sondern die neue Anzahl der Ladungen zum alten Objektwert addiert.
Es wird die aktuelle Version 1.2.9 des Adapters  verwendet.

**Comment by MeisterTR** [comment]
Das ist normal, da der Wert nur in der App geändert wird, auf dem Server jedoch die Gesamtzahl bleibt
