### ISSUE TITLE
GPS Koordinaten aus Find My Landroid

### ISSUE THREAD

**Issue by dibman** [iobroker-community-adapters/ioBroker.worx#218]
Hallo,
in der WORX App sehe ich die, zugegeben mäßig genauen, GPS Koordinaten des Landroid vo Find my Landroid Module. Nutze win Worx WR143E.
Wie bekommt es hin, diese auch im iobroker als object anzeigen zu lassen?

Kann gern mit Tests oder ähnlichem unterstützten.

VG Steve

**Comment by MeisterTR** [comment]
schalte mal den Adapter auf debug, und schaue im log da stehen die Rohdaten, wenn sie übermittelt werden, müssten sie da stehen

**Comment by dibman** [comment]
in den Rohdaten finde ich die korrekten GPS-Daten des Worx: "gps":{"coo":[50.860057,12.909236]}
die dazugehörigen Rohdaten (bereinigt um SN & Co.) habe ich als Anlage angehangen
[debug_clean.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/6266789/debug_clean.txt)

**Comment by MeisterTR** [comment]
`{"cfg":{"id":1,"lg":"it","tm":"17:46:14","dt":"06/04/2021","sc":{"m":2,"distm":0,"ots":{"bc":0,"wtm":0},"p":0,"d":[["00:00",0,0],["08:30",450,1],["08:30",450,0],["08:30",450,0],["08:30",450,1],["08:30",390,0],["00:00",0,0]],"dd":[["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":60,"sn":"","modules":{"US":{"enabled":1},"4G":{"enabled":1,"geo":{"coo":[50.560057,11.909326],"rad":24}}}},"dat":{"mac":"","fw":3.22,"fwb":1,"bt":{"t":7.5,"v":19.73,"p":100,"nr":347,"c":0,"m":1},"dmp":[0.3,3.2,0],"st":{"b":53578,"d":927196,"wt":58318,"bl":192},"ls":1,"le":0,"lz":1,"rsi":-65,"lk":1,"act":1,"tr":0,"conn":"4G","rain":{"s":0,"cnt":0},"time":{"r":0,"l":0},"modules":{"US":{"stat":"ok"},"4G":{"mode":1,"stat":"ok","vers":2.34,"batt":{"v":4.09,"l":95,"t":9},"network":{"status":"connected","ICCID":"","IMSI":"","mode":"EDGE","rssi":-65},"geo":{"stat":"in"},"gps":{"coo":[50.560057,11.909236]}}}}}`

werde es bei gelegenheit einbinden
