### ISSUE TITLE
Kein Datenpunkt für letzte Cloud Aktualisierung

### ISSUE THREAD

**Issue by Cosmicbase** [iobroker-community-adapters/ioBroker.worx#219]
In English:
I would like to integrate the data point of the last cloud update into the Vis.
In the Worx app, this point is available in the front view.
Can this data point be entered?

In Deutsch: 
Ich möchte gerne den Datenpunkt der letzten Cloud Aktualisierung in die Vis einbauen. 
In der Worx App ist dieser Punkt im Front View vorhanden.
Kann dieser Datenpunkt eingepflegt werden?

**Comment by MeisterTR** [comment]
dafür kannst du ganz einfach das timestamp widget in vis benutzen, das zeigt an wann ein datenpunkt das letzte mal aktualisert wurde

**Comment by Cosmicbase** [comment]
Danke dir, und soweit habe ich das verstanden.
Kann ich mit dem Timestamp Widget nur die Aktualisierung sehen oder kann ich auch irgendwie eine Aktualisierung anstoßen?
Ich habe gesehen das der Robbi beim Ausführen vom Kantenschnitt solange auf "Verlassen der Ladestation" steht bis eine Aktualisierung statt findet.
Diese Aktualisierung sollte meiner Meinung in kleinen Intervall Schritten alle paar Sekunden automatisch stattfinden...
Macht es aber nicht. Es ist wohl zu unbequem dies manuell per swipe in der app durchzuführen. 
Vielleicht kann man das auch per Adapter anstoßen.

In allen 2 Screenshots macht der Robbi ein Kantenschnitt.

Bild 1 - - - > ohne Swipe

In Bild 1 ist zu sehen das die letzte Cloud Aktualisierung zum Teil Minuten lang ausgesetzt wird und nur manuell aktualisiert wird.
![Screenshot_20210408_120712_it positec landroid](https://user-images.githubusercontent.com/31271212/114017177-fdaf9f80-986b-11eb-88fa-648fa45b5707.jpg)

Bild 2 - - - > mit Swipe

![Screenshot_20210408_112802_it positec landroid](https://user-images.githubusercontent.com/31271212/114017271-1a4bd780-986c-11eb-91b4-c7de3c90cc1b.jpg)

Bild 3 zeigt das auch nach fast 10 Minuten den Status nicht aktualisiert hat.

![Screenshot_20210408_112813_it positec landroid](https://user-images.githubusercontent.com/31271212/114017289-1f108b80-986c-11eb-964c-2e851dd47bb3.jpg)

**Comment by Cosmicbase** [comment]
Jetzt habe ich rausgefunden, wenn ich 2 x Kantenschnitt trigger sich augenblicklich auch der State in der App, Adapter aktualisiert und logischerweise auch der timestamp.
