### ISSUE TITLE
Keine Verbindung ERROR: StatusCodeError: 403

### ISSUE THREAD

**Issue by Wilhelm08** [iobroker-community-adapters/ioBroker.worx#227]
Update auf 1.30
neue Fehler erhalten: 

worx.0 | 2021-04-15 19:16:04.081 | error | (21559) ERROR: StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
-- | -- | -- | --
worx.0 | 2021-04-15 19:16:04.080 | error | (21559) Could not Connect to Worx Server: StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
worx.0 | 2021-04-15 19:16:03.862 | info | (21559) worx is selected
worx.0 | 2021-04-15 19:16:03.746 | info | (21559) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.worx, node: v12.20.1, js-controller: 3.2.16
host.raspberryiob | 2021-04-15 19:16:01.731 | info | instance system.adapter.worx.0 started with pid 21559
host.raspberryiob | 2021-04-15 19:16:00.686 | info | Restart adapter system.adapter.worx.0 because enabled
host.raspberryiob | 2021-04-15 19:16:00.678 | info | instance system.adapter.worx.0 scheduled normal terminated and will be restarted on schedule.
worx.0 | 2021-04-15 19:16:00.032 | info | (21481) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
worx.0 | 2021-04-15 19:16:00.028 | info | (21481) terminating
worx.0 | 2021-04-15 19:16:00.016 | info | (21481) cleaned everything up...

**Comment by MeisterTR** [comment]
ich kann den Fehler nicht bestätigen Passwort mal neu eingegeben?

**Comment by MeisterTR** [comment]
oder ggf mal bis morgen abgschaltet lassen

**Comment by Wilhelm08** [comment]
Danke für die schnelle Reaktion.
Beim neu anmelden kommt: Verbindungsfehler
Ich schalte den Mäher bis morgen aus.

**Comment by Wilhelm08** [comment]
Moin,  habe heute Morgen den Worx-Mäher neu gestartet und folgende Meldung erhalten.
 
worx.0 | 2021-04-16 11:20:04.972 | warn | (9410) DON`T CONTACT THE OFFICIAL WORX SUPPORT BECAUSE THIS IS AN INOFFICAL APP !!!!!!!!!!!
-- | -- | -- | --
worx.0 | 2021-04-16 11:20:04.971 | warn | (9410) maybe your connection is blocked from Worx, please test start button, if not working, try again in 24h

**Comment by MeisterTR** [comment]
Aber läuft?

**Comment by Wilhelm08** [comment]
Ja läuft, probiere Morgen nochmal.

**Comment by MeisterTR** [comment]
sehe ich hiermit als erledigt an
