### ISSUE TITLE
Could not Connect to Worx Server

### ISSUE THREAD

**Issue by FNIO** [iobroker-community-adapters/ioBroker.worx#230]
worx.0 | 2021-04-17 13:15:42.564 | error | (13251) ERROR: RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
-- | -- | -- | --
worx.0 | 2021-04-17 13:15:42.563 | error | (13251) Could not Connect to Worx Server: RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
worx.0 | 2021-04-17 13:15:32.490 | info | (13251) worx is selected
worx.0 | 2021-04-17 13:15:32.447 | info | (13251) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.worx, node: v12.21.0, js-controller: 3.1.6
worx.0 | 2021-04-17 13:15:32.424 | info | (13251) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

**Comment by MeisterTR** [comment]
hast du einen debug log auszug?

**Comment by FNIO** [comment]
Moin, 
ich hoffe du meist diesen debug hier :-)

worx.0 | 2021-04-18 13:11:11.034 | error | (4576) ERROR: RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
-- | -- | -- | --
worx.0 | 2021-04-18 13:11:11.033 | error | (4576) Could not Connect to Worx Server: RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
worx.0 | 2021-04-18 13:11:00.958 | debug | (4576) Connect to worx....
worx.0 | 2021-04-18 13:11:00.957 | info | (4576) worx is selected
worx.0 | 2021-04-18 13:11:00.919 | info | (4576) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.worx, node: v12.22.1, js-controller: 3.1.6
worx.0 | 2021-04-18 13:11:00.862 | info | (4576) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
worx.0 | 2021-04-18 13:11:00.856 | debug | (4576) Plugin sentry Initialize Plugin (enabled=true)
worx.0 | 2021-04-18 13:11:00.344 | debug | (4576) statesDB connected
worx.0 | 2021-04-18 13:11:00.343 | debug | (4576) States connected to redis: 127.0.0.1:9000
worx.0 | 2021-04-18 13:11:00.334 | debug | (4576) States create System PubSub Client
worx.0 | 2021-04-18 13:11:00.331 | debug | (4576) States create User PubSub Client
worx.0 | 2021-04-18 13:11:00.322 | debug | (4576) Redis States: Use Redis connection: 127.0.0.1:9000
worx.0 | 2021-04-18 13:11:00.320 | debug | (4576) objectDB connected
worx.0 | 2021-04-18 13:11:00.310 | debug | (4576) Objects connected to redis: 127.0.0.1:9001
worx.0 | 2021-04-18 13:11:00.258 | debug | (4576) Objects client initialize lua scripts
worx.0 | 2021-04-18 13:11:00.255 | debug | (4576) Objects create User PubSub Client
worx.0 | 2021-04-18 13:11:00.253 | debug | (4576) Objects create System PubSub Client
worx.0 | 2021-04-18 13:11:00.246 | debug | (4576) Objects client ready ... initialize now
worx.0 | 2021-04-18 13:11:00.207 | debug | (4576) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.94791b47a7f2 | 2021-04-18 13:10:58.756 | info | instance system.adapter.worx.0 started with pid 4576

**Comment by Woersty** [comment]
Ich behaupte mal in deiner Netzwerk Konfiguration passt was nicht.
Was kommt denn, wenn du ` openssl s_client -connect api.worxlandroid.com:443`  machst?

**Comment by FNIO** [comment]
Erst einmal vielen Dank für die Hilfe.
Die Antwort auf ... openssl s_client -connect api.worxlandroid.com:443 ... 

root@94791b47a7f2:/opt/iobroker# openssl s_client -connect api.worxlandroid.com:443                                                                                                                                                                                             
CONNECTED(00000003)                                                                                                                                                                                                                                                             
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1                                                                                                                                                                                                                               
verify return:1                                                                                                                                                                                                                                                                 
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon                                                                                                                                                                                                                      
verify return:1                                                                                                                                                                                                                                                                 
depth=0 CN = *.worxlandroid.com                                                                                                                                                                                                                                                 
verify return:1                                                                                                                                                                                                                                                                 
---                                                                                                                                                                                                                                                                             
Certificate chain                                                                                                                                                                                                                                                               
 0 s:CN = *.worxlandroid.com                                                                                                                                                                                                                                                    
   i:C = US, O = Amazon, OU = Server CA 1B, CN = Amazon                                                                                                                                                                                                                         
 1 s:C = US, O = Amazon, OU = Server CA 1B, CN = Amazon                                                                                                                                                                                                                         
   i:C = US, O = Amazon, CN = Amazon Root CA 1                                                                                                                                                                                                                                  
 2 s:C = US, O = Amazon, CN = Amazon Root CA 1                                                                                                                                                                                                                                  
   i:C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", CN = Starfield Services Root Certificate Authority - G2                                                                                                                                          
 3 s:C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", CN = Starfield Services Root Certificate Authority - G2                                                                                                                                          
   i:C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority                                                                                                                                                                                 
---                                                                                                                                                                                                                                                                             
Server certificate                                                                                                                                                                                                                                                              
-----BEGIN CERTIFICATE-----                                                                                                                                                                                                                                                     
MIIFlTCCBH2gAwIBAgIQBSvU9JicxY1ykDf7jG38rjANBgkqhkiG9w0BAQsFADBG                                                                                                                                                                                                                
MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRUwEwYDVQQLEwxTZXJ2ZXIg                                                                                                                                                                                                                
Q0EgMUIxDzANBgNVBAMTBkFtYXpvbjAeFw0yMTAyMTYwMDAwMDBaFw0yMjAzMTcy  
...
OJyJMyaJKIe47chWsGYdhfhSlMdFfXldUhWpR6L7DzAlok2OSjcet/LrukIoGAT4                                                                                                                                                                                                                
m7PgsK07G4k2OsT912iRjJwwosY8R2exFDypMBouwWloEbZqIg/KWXw=                                                                                                                                                                                                                        
-----END CERTIFICATE-----                                                                                                                                                                                                                                                       
subject=CN = *.worxlandroid.com                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                
issuer=C = US, O = Amazon, OU = Server CA 1B, CN = Amazon                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                
---                                                                                                                                                                                                                                                                             
No client certificate CA names sent                                                                                                                                                                                                                                             
Peer signing digest: SHA512                                                                                                                                                                                                                                                     
Peer signature type: RSA                                                                                                                                                                                                                                                        
Server Temp Key: ECDH, P-256, 256 bits                                                                                                                                                                                                                                          
--- 
SSL handshake has read 5564 bytes and written 438 bytes                                                                                                                                                                                                                         
Verification: OK                                                                                                                                                                                                                                                                
---                                                                                                                                                                                                                                                                             
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256                                                                                                                                                                                                                             
Server public key is 2048 bit                                                                                                                                                                                                                                                   
Secure Renegotiation IS supported                                                                                                                                                                                                                                               
Compression: NONE                                                                                                                                                                                                                                                               
Expansion: NONE                                                                                                                                                                                                                                                                 
No ALPN negotiated                                                                                                                                                                                                                                                              
SSL-Session:                                                                                                                                                                                                                                                                    
    Protocol  : TLSv1.2                                                                                                                                                                                                                                                         
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256                                                                                                                                                                                                                                     
    Session-ID: 40ACEBE96525A48F8141E35926AA5CC134C3BC0C7A2B25A90C096B79470B3972                                                                                                                                                                                                
    Session-ID-ctx:                                                                                                                                                                                                                                                             
    Master-Key: 418FA3FA3E0DF32425D0038B310FA624D333B345C09E2A79E5AC271954D505564988108FB4B3D34521FB97EDCE2B637E                                                                                                                                                                
    PSK identity: None                                                                                                                                                                                                                                                          
    PSK identity hint: None                                                                                                                                                                                                                                                     
    SRP username: None                                                                                                                                                                                                                                                          
    TLS session ticket lifetime hint: 43200 (seconds)                                                                                                                                                                                                                           
    TLS session ticket:                                                                                                                                                                                                                                                         
    0000 - 18 ed 62 af a0 26 05 f5-b2 ee e9 5b 43 39 15 11   ..b..&.....[C9..                                                                                                                                                                                                   
    0010 - a6 c6 f0 df b1 d1 5e 71-3f a3 1b 4d 13 3b 9f 87   ......^q?..M.;..                                                                                                                                                                                                   
    0020 - f1 a6 33 30 99 9c bf a3-17 d7 62 23 9e b1 2b e1   ..30......b#..+.                                                                                                                                                                                                   
    0030 - 16 0f 7a 95 88 a4 49 7f-78 42 f6 74 4e a4 6e 46   ..z...I.xB.tN.nF                                                                                                                                                                                                   
    0040 - 8c 56 83 16 cf e8 16 4c-16 f6 27 c9 29 12 bc 0d   .V.....L..'.)...                                                                                                                                                                                                   
    0050 - bd 27 66 7b 89 21 23 8a-87 8e 39 7f af ec 09 40   .'f{.!#...9....@                                                                                                                                                                                                   
    0060 - 35 c1 13 e7 2e 56 da 23-16 6a f1 56 b6 1a cf b5   5....V.#.j.V....                                                                                                                                                                                                   
    0070 - 30 1f 46 ce 42 02 5e c2-48 12 1b 47 d3 87 b1 c9   0.F.B.^.H..G....                                                                                                                                                                                                   
    0080 - 05 53 20 21 22 94 dc d6-ef c0 8c 6f f0 67 93 c0   .S !"......o.g..                                                                                                                                                                                                   
    0090 - 57 fb c7 29 58 25 02 bb-65 62 5a 64 9a 2b 39 d7   W..)X%..ebZd.+9.                                                                                                                                                                                                   
    00a0 - da 43 5f cb af 1f 95 b5-2e b0 9e dc 76 71 d8 40   .C_.........vq.@                                                                                                                                                                                                   
    00b0 - 93 2d 32 82 e3 7c 22 f9-b3 72 7c 7f 7e f4 7b 54   .-2..|"..r|.~.{T                                                                                                                                                                                                   
    00c0 - 7b 68 8d f9 73 32 c6 24-d0 bd a9 9f 3b 02 15 07   {h..s2.$....;...                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                
    Start Time: 1618761626                                                                                                                                                                                                                                                      
    Timeout   : 7200 (sec)                                                                                                                                                                                                                                                      
    Verify return code: 0 (ok)                                                                                                                                                                                                                                                  
    Extended master secret: no                                                                                                                                                                                                                                                  
---                                                                                                                                                                                                                                                                             
^C

**Comment by FNIO** [comment]
Problem gelöst!
Danke für den Hinweis auf die Netzwerkeinstellungen.
Das Systemstandardgaytway meiner QNAP stand auf automatisch.
Habe ich nun fix auf den Virtuellen Switch gestellt, an dem auch der ioBroker-Docker hängt.
Und siehe da ... alles gut!

Bis die Tage... bleib gesund!
