### ISSUE TITLE
Force update button?

### ISSUE THREAD

**Issue by woessmich** [iobroker-community-adapters/ioBroker.worx#232]
I wonder if it would be possible to add a button to force information update like the App does when pulling down the main screen.

I can observe that for whatever reason, every once in a while my Landroid seems to decide no longer to send updates to the Server. Status becomes "offline". Typically, this only happens when it is at home in the station. I do not know the reason. Wifi might not be perfect in this location but without problems, status is updated immediately as soon as I do the force updating in the App (screen pulling down). If I do not do that, it stays offline.
Sometimes this happens multiple times a day, sometimes only once in a week.
I am aware that the adapter should not do that excessively so not to be blocked by the servers, but the option to do a forced update (once in an hour in case of an offline-status would not hurt) would be a nice thing to have.
To avoid accidental "misuse", the option might come with the need to activate in the adapter config.

**Comment by MeisterTR** [comment]
i think thats a wifi problem so you shoud fix that.

**Comment by woessmich** [comment]
Question: How can the mobile App have a different Wifi connection than the iobroker adapter?
Requesting an update in the App updates status every time, but the mower does not update on its own account under certain circumstances. After forcing the update in the App, the adapter also sees the mower as online again.
My believe is: If the mower has no time program and is at home, it does not see the requirement to send updates on its own account because there is nothing to report.
A force update button is required here.

**Comment by hsteinme** [comment]
> My believe is: If the mower has no time program and is at home, it does not see the requirement to send updates on its own account because there is nothing to report.

Sorry, this is a mibelief, which is proven, for example, by a look at the log file of my mower. The mower sends a status to the cloud at least every 10 minutes, even if nothing special happens.

![image](https://user-images.githubusercontent.com/33778564/120116159-08f5bc00-c187-11eb-9367-237977133435.png)

**Comment by woessmich** [comment]
Well, this is your mower.
And maybe not all mowers are created equal:
The log from my mower proves that without being disconnected from Wifi (as it is not reconnecting before action!) it can wait until being woken from the App to respond.
It did charge battery until shortly before 06:00, then waited doing nothing (not even logging anything) and pretend to be offline (in iobroker) until I woke it up at 09:28:19 with the iPhone App.
Then, after iobroker noticed it being back online, at 09:30:00 it sent a "go" command, (iobroker, not the App). It would have received the "go" much earlier if it would have been reporting to be "at home" and online but I check for status before sending.

<img width="620" alt="Screenshot 2021-05-31 171359" src="https://user-images.githubusercontent.com/26891071/120213819-f5ecf580-c233-11eb-9829-d6dbcaa82183.png">

BTW: Mine is doing this send thing every 10 minutes also most of the time. But just only mostly which is just not sufficient.
The day before, last signal looked like this:
![image](https://user-images.githubusercontent.com/26891071/120215462-0bfbb580-c236-11eb-96d8-bb2c8dcd57b0.png)
And there was never a disconnect between.
But there is this error which might or might not be related:
![image](https://user-images.githubusercontent.com/26891071/120215654-41a09e80-c236-11eb-9aad-f1d2aaf9370d.png)

**Comment by hsteinme** [comment]
May I please ask which mower model and which firmware version you are using?

According to the firmware developers a can-bus overrun error does not have any negative impact.

**Comment by woessmich** [comment]
Hi
It is a Landroid WR141E, Firmware was 3.17.
Now, it is on 3.24

**Comment by hsteinme** [comment]
Thank you. Surprise, surprise! My mower is also a WR141E. I've checked logs from August 2020 (Version 3.16), from June 2020 (Version 3.11) and April 2019 (Version 2.74). They all showed the same behaviour as in my logfile above. Very strange!
