### ISSUE TITLE
js-controller 3.3.1 

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.worx#236]
![grafik](https://user-images.githubusercontent.com/6681528/116652471-8611f380-a985-11eb-80f2-5c4bf7866300.png)

**Comment by Qube2org** [comment]
unfortunately not completely fixed, still get with v1.3.2 this messages:

worx.0 | 2021-05-14 15:51:07.741 | info | (2108103) State value to set for "worx.0.201930199301011414FB.weather.lastUpdate" has to be type "date" but received type "object"
-- | -- | -- | --
worx.0 | 2021-05-14 15:51:07.739 | info | (2108103) State value to set for "worx.0.201930199301011414FB.weather.humidity" has to be type "string" but received type "number"
worx.0 | 2021-05-14 15:51:07.465 | info | (2108103) State value to set for "worx.0.201930199301011414FB.areas.startSequence" has to be type "string" but received type "object"
worx.0 | 2021-05-14 15:51:07.037 | info | (2108103) State value to set for "worx.0.201930199301011414FB.areas.startSequence" has to be type "string" but received type "object"
unifi.0 | 2021-05-14 15:51:06.334 | info | (3650867) Update done
worx.0 | 2021-05-14 15:51:00.761 | info | (2108103) worx is selected
worx.0 | 2021-05-14 15:51:00.725 | info | (2108103) starting. Version 1.3.2 in /opt/iobroker/node_modules/iobroker.worx, node: v14.17.0, js-controller: 3.3.9
