### ISSUE TITLE
INFO: wrong type after update of js-controller

### ISSUE THREAD

**Issue by lobomau76** [iobroker-community-adapters/ioBroker.worx#248]
After updating the js-controller to 3.3.8 I have a lot of infos in the log:

`
<html>
<body>

worx.0 | 2021-05-10 09:41:47.981 | info | (7410) State value to set for "worx.0.30173502170329012345.areas.startSequence" has to be type "string" but received type "object"
-- | -- | -- | --
worx.0 | 2021-05-10 09:41:47.980 | info | (7410) State value to set for "worx.0.30173502170329012345.mower.firmware" has to be type "string" but received type "number"
worx.0 | 2021-05-10 09:41:47.975 | info | (7410) State value to set for "worx.0.30173502170329012345.mower.totalBladeTime" has to be type "number" but received type "string"
worx.0 | 2021-05-10 09:41:47.975 | info | (7410) State value to set for "worx.0.3017350217032912345.mower.totalDistance" has to be type "number" but received type "string"
worx.0 | 2021-05-10 09:41:47.974 | info | (7410) State value to set for "worx.0.3017350217032912345.mower.totalTime" has to be type "number" but received type "string"

</body>
</html>`

**Comment by hsteinme** [comment]
This is a duplicate issue, see https://github.com/iobroker-community-adapters/ioBroker.worx/issues/236. Please close this issue here.
