### ISSUE TITLE
many message in log about incorrect state types

### ISSUE THREAD

**Issue by Qube2org** [iobroker-community-adapters/ioBroker.worx#250]
**Describe the bug**  

many message in log about incorrect state types

**To Reproduce**  

in log you find many entries about incorrect types of states, like this:

worx.0 | 2021-05-13 21:59:16.184 |info | (3649815) State value to set for "worx.0.201930199301011414FB.areas.startSequence" has to be type "string" but received type "object"
-- | -- | -- | --
worx.0 | 2021-05-13 21:59:16.182 | info | (3649815) State value to set for "worx.0.2019...FB.mower.firmware" has to be type "string" but received type "number"
worx.0 | 2021-05-13 21:59:16.175 | info | (3649815) State value to set for "worx.0.2019...FB.mower.totalBladeTime" has to be type "number" but received type "string"
worx.0 | 2021-05-13 21:59:16.174 | info | (3649815) State value to set for "worx.0.2019...FB.mower.totalDistance" has to be type "number" but received type "string"
worx.0 | 2021-05-13 21:59:16.173 | info | (3649815) State value to set for "worx.0.2019...FBB.mower.totalTime" has to be type "number" but received type "string"

**Expected behavior**  

All states have the correct type and no messages like above.

**Versions:**  
 - Adapter version: 1.3.0
 - JS-Controller version: 3.3.9
 - Node version: v14.17.0
 - Operating system: Ubuntu 20.04.2 LTS

**Additional context**

**Comment by hsteinme** [comment]
This is a duplicate issue, see https://github.com/iobroker-community-adapters/ioBroker.worx/issues/236 and https://github.com/iobroker-community-adapters/ioBroker.worx/issues/248. Please close this issue here.

**Comment by MeisterTR** [comment]
and fixed in 1.3.1
