### ISSUE TITLE
Edge cutting

### ISSUE THREAD

**Issue by Woersty** [iobroker-community-adapters/ioBroker.worx#251]
Geht das Edge cutting eigentlich inzwischen?

Hier gab es bisher keine Reaktion: https://github.com/axelmohnen/fhem-landroid-s/issues/15

**Comment by hsteinme** [comment]
Gemäß https://github.com/iobroker-community-adapters/ioBroker.worx/issues/62 funktioniert der Kantenschnitt wieder seit Ende August 2020 (Version 1.2.3)
