### ISSUE TITLE
Klingen und Batteriewechsel

### ISSUE THREAD

**Issue by Cosmicbase** [iobroker-community-adapters/ioBroker.worx#257]
Zunächst mal ein großen Dank und Lob an @MeisterTR für die unermüdliche Arbeit am Adapter.

Ich weiß es war schon mal ein Thema, Klingen und Batteriewechsel über ein Script zu steuern.
Doch leider ist das weder komfortabel noch leicht zu realisieren. 
Wenn ich in der App die Werte zuücksetze bleiben sie im Adapter stehen. Auch ein überschreiben ist im Adapter nicht möglich, obwohl es so sinnvoll wäre.

@MeisterTR Kannst du dich der Sache nochmal widmen?

Vielen Dank

**Comment by hsteinme** [comment]
@MeisterTR Siehe zur Problematik beim Skript-Versuch https://github.com/iobroker-community-adapters/ioBroker.worx/issues/67#issuecomment-685740159 sowie zur Datenstruktur https://github.com/iobroker-community-adapters/ioBroker.worx/issues/67#issuecomment-674422961

**Comment by Cosmicbase** [comment]
Ein neuer Datenpunkt wäre natürlich auch nicht schlecht. Er müsste nur die Mähzeit bzw. die Zeit wo sich die Messer drehen berücksichtigen. Die App kann ja Aussen vor bleiben.
Der Datenpunkt könnte currentBladeTime heißen und sich beim Wechseln zurücksetzen lassen. 
Auch beim Akku sinnvoll.

**Comment by Cosmicbase** [comment]
@MeisterTR super das in die Sache nochmal Wind kommt. 👍

**Comment by TA2k** [comment]
In der aktuellen Github version werden alle rohdaten abgespeichert wenn man in den Instanze Optionen die Option dafür aktiviert

**Comment by Cosmicbase** [comment]
So die Rohdaten sehe ich alle. Perfekt
Die aktuelle Klingen Arbeitszeit bzw. Ladezykkus jedoch nicht. Nur die Gesamtanzahl ist wie vor vorhanden.
@MeisterTR Musst du noch da Datenpunkte einpflegen?

**Comment by TA2k** [comment]
Unter 
worx.0.21231234123213.rawMqtt.raw.battery_charge_cycles
worx.0.21231234123213.rawMqtt.raw.blade_work_time_reset_at

solltest du doch alles sehen. Es müssen keine zusätzliche Datenpunkte eingepflegt werden.

**Comment by Cosmicbase** [comment]
Ich sehe die 2 Datenpunkte unter raw.
Aber sie haben immer noch den gleichen Wert. 
In der App auf Null und unter Raw Alter Wert.
Wenn ich den auf Null setzte und den Adapter neu starte setzten sich die Werte wieder auf ursprünglichen Stand zurück.

**Comment by TA2k** [comment]
Das sind die rohen Werte die der Worx zurückgibt, diese können nicht verändert werden. 
Ich sehe leider nicht in der App wo man die Klingenzeit zurücksetzt.
Wenn die Werte nicht irgendwo in den raw Daten sind dann kann der Adapter nicht weiterhelfen.

**Comment by Cosmicbase** [comment]
In der App unter "Statistiken" 
können sowohl Klingenzeit als auch Ladezyklen zurück gesetzt werden. Diese Werte müssen doch irgendwie auffindbar sein.

![Screenshot_20210605_120448_it positec landroid](https://user-images.githubusercontent.com/31271212/120888029-6ca03f00-c5f6-11eb-9de5-f8f903e77e09.jpg)

**Comment by TA2k** [comment]
Man findet die Werte folgendes Beispiel:
Bladetime wurde noch nie resetet:
"blade_work_time": 25010,
        "blade_work_time_reset": 0,
        "blade_work_time_reset_at": null,

Bladetime wurde resetet:
   "blade_work_time": 25010,
        "blade_work_time_reset": 25144,
        "blade_work_time_reset_at": "2021-06-05 11:46:49",

Jetzt musst du wie die app 
blade_work_time - blade_work_time_reset und das zeigt die App an

**Comment by hsteinme** [comment]
@TA2k : Hat im 2. Beispiel der Fehlerteufel zugeschlagen? blade_work_time müsste größer oder gleich blade_work_time_reset sein.

@Cosmicbase : Erinnerst Du Dich an https://github.com/iobroker-community-adapters/ioBroker.worx/issues/67#issuecomment-674422961 und https://github.com/iobroker-community-adapters/ioBroker.worx/issues/67#issuecomment-685740159?

**Comment by TA2k** [comment]
Das sind daten direkt aus dem System. Anscheinend ist es nicht immer der Fall

**Comment by Cosmicbase** [comment]
> Man findet die Werte folgendes Beispiel:
> Bladetime wurde noch nie resetet:
> "blade_work_time": 25010,
> "blade_work_time_reset": 0,
> "blade_work_time_reset_at": null,
> 
> Bladetime wurde resetet:
> "blade_work_time": 25010,
> "blade_work_time_reset": 25144,
> "blade_work_time_reset_at": "2021-06-05 11:46:49",
> 
> Jetzt musst du wie die app
> blade_work_time - blade_work_time_reset und das zeigt die App an alles größer 0 ist

Also habe ich das richtig verstanden?
Die aktuelle Klingenzeit wird in Differenz berechnet?
Und da z.B. zwischen "blade_work_time": 25010,
"blade_work_time_reset": 25010, kein Unterschied besteht ist = 0, und je weiter der Unterschied desto größer die aktuelle Klingenlaufzeit.
Wenn ich später einen Reset mache, müssten alle 2 Zeiten den gleichen Wert haben. 🤔

**Comment by Cosmicbase** [comment]
> Das sind daten direkt aus dem System. Anscheinend ist es nicht immer der Fall

Bladetime wurde resetet:
"blade_work_time": 25010,
"blade_work_time_reset": 25144,
"blade_work_time_reset_at": "2021-06-05 11:46:49",

Bei mir sind die 2 Werte nach dem reset gleich. So sollte es dann scheinbar sein. Bei Nutzung des Rasenroboter nach Wechsel der Klingen sollte sich dann eine Differenz ergeben.
Ich weiß nur noch nicht wie das umsetzten soll???

**Comment by hsteinme** [comment]
> Ich weiß nur noch nicht wie das umsetzten soll???

Jetzt sprengen wir den Rahmen von GitGub-Issues. Stell doch diese Frage im Forum, dann helfe ich Dir dort gerne weiter - falls Du eine Lösung in Javascript möchtest. Bei Blockly müsste ich passen.

**Comment by Cosmicbase** [comment]
OK wird geschlossen und hab dir geschrieben :)

**Comment by Cosmicbase** [comment]
> Das sind daten direkt aus dem System. Anscheinend ist es nicht immer der Fall

Genau das habe ich jetzt auch bemerkt. Das "blade_work_time_reset" manchmal größer ist als "blade_work_time" macht gar kein Sinn.
Zumal es mit dem JS jetzt Probleme gibt. Es sollte ja generell blade_work_time_reset von "blade_work_time" abgezogen werden, so das die aktuelle Klingenzeit in einem DP ausgegben wird.
Aber so wird das auch nicht funktionieren.

Bitte um Vorschläge, Gruß Cosmicbase

**Comment by Cosmicbase** [comment]
Irgend jemand eine Idee warum die Raw Werte vertauscht sind. In der App werden ja die Werte unter Statistik richtig dargestellt.

Hier nochmal der Fehler. Entweder es liegt am Adapter oder an den Daten von Positec.

![Unbenannt](https://user-images.githubusercontent.com/31271212/122140522-c18c5280-ce4b-11eb-8824-beb71a8e9677.PNG)

**Comment by TA2k** [comment]
Der Adapter gibt die werte direkt zurück vielleicht sind die Werte auch anders zu interpretieren. 
blade_work_time ist zum reset zeitpunkt und blade_work_time_reset ist seit dem reset
Einfach mal rumprobieren

**Comment by Cosmicbase** [comment]
> Der Adapter gibt die werte direkt zurück vielleicht sind die Werte auch anders zu interpretieren.
> blade_work_time ist zum reset zeitpunkt und blade_work_time_reset ist seit dem reset
> Einfach mal rumprobieren

Angenommen du hast Recht. Aber warum zählt die App schön tapfer die Klingenzeit mit...
Aber im Adapter ist sie nicht aktualisiert??

**Comment by hsteinme** [comment]
Die vom Adapter gezeigten Werte scheinen aus verschiedenen Datenquellen zu stammen. Die Daten zu worx.0.xxx.rawMqtt.message werden im Abstand von maximal etwa 10 Minuten synchronisiert, während die Daten zu worx.0.xxx.rawMqtt.raw im Abstand von zwei oder mehr Stunden synchronisiert werden.

Hier scheinen auch Unstimmigkeiten zwischen den Daten aus den verschiedenen Quellen aufzutreten. Zwei Beispiele bei mir:

- worx.0.xxx.rawMqtt.message.dat.st.b = **64117** vs. worx.0.xxx.rawMqtt.raw.blade_work_time = **64034**
- worx.0.xxx.rawMqtt.message.dat.st.d = **1123567** vs. worx.0.xxx.rawMqtt.raw.distance_covered = **1122190**

Fazit: Nichts genaues weiss man nicht.

**Comment by Cosmicbase** [comment]
Also die Daten wo ich benötige werden nicht automatisch abgeholt. 

Lösung: Adapter neu starten!

Vielleicht kann @MeisterTR hier eine automatische Aktualisierung einbauen mit Intervall.

**Comment by TA2k** [comment]
War mein Fehler hatte das nur in das Start update eingefügt. Jett nochmal via github installieren dann müsste es sich immer updaten.

**Comment by Cosmicbase** [comment]
Per GitHub oder geht auch per npm installieren?

**Comment by TA2k** [comment]
Nur per github

**Comment by Cosmicbase** [comment]
> Nur per github

Daten von GitHub runterladen und die Worx Daten überschreiben ohne Installation?

**Comment by hsteinme** [comment]
@Cosmicbase : https://www.google.com/search?q=iobroker+%22adapter+aus+github+installieren%22

**Comment by Cosmicbase** [comment]
Das meinte ich nicht. Man kann ja wohl über ne Installationsroutine via GitHub als auch händisch die Daten überschreiben. 🤔
Hab es via GitHub gemacht 😂

**Comment by Cosmicbase** [comment]
Nachdem ja die raw Werte nicht sauber und vor allem regelmäßig synchronisiert werden habe ich jetzt die message DP worx.0.9999999999rawMqtt.message.dat.bt.nr für den Batterie Charge Cycle hergekommen und worx.0.9999999999.rawMqtt.message.dat.st.b für die Klingenzeit.

Das ganze jeweils in ein JS gepackt und siehe da, die aktuellen Daten werden übertragen.

**Comment by TA2k** [comment]
Ich würde behaupten das wirklich alles was über MQTT reinkommt geschrieben wird aber die erste Nachricht beim Start ist denke ich eine andere die dann regelmässig kommt.
Wenn die Werte wirklich die korrekten Werten sind kann @MeisterTR sie als feste Werte einbauen.

**Comment by Cosmicbase** [comment]
@TA2k

Habe jetzt nochmal intensiv alles geprüft.
So wie ich oben beschrieben habe funktioniert die aktuelle Klingenlaufzeit recht gut. Einzig wenn ich in der App unter Statistik einen Klingenreset mache wird worx.0.9999999999.rawMqtt.message.dat.st.b

Erst nach einem Adapter Neustart aktualisiert.
Leider habe ich weder nach 10 Minuten noch nach längerer Mähzeit keinen Reset bemerkt. 
Die Zeit läuft einfach weiter. Nach nem Neustart wird die genau berechnete Differenz richt angezeigt.


Bitte Update nochmals überprüfen.
Wäre ja schön wenn der, die message DP automatisch aktualisiert werden würden. 
Entweder bei Veränderungen oder per Intervall.

DANKESCHÖN ☺️
