### ISSUE TITLE
Zusätzliche Felder im Adapter

### ISSUE THREAD

**Issue by Creekhail** [iobroker-community-adapters/ioBroker.worx#261]
Ich habe leider keine Information in Foren oder hier entdeckt, daher jetzt eine Anfrage auf diesem Weg:
Gibt es die Möglichkeit Boolean-Felder im Adapter zu integrieren, die die Werte "Bei Regen mähen" und "Rette die Igel" aus der App abbilden würden? In der App sind das Schalter die man aktivieren kann, allerdings weiß ich nicht, ob das über die Schnittstelle von Worx überhaupt verfügbar gemacht wird.
Da der Schalter "Party-Modus" inzwischen jedoch im Adapter integriert wurde, habe ich natürlich die Hoffnung, dass auch für die restlichen Schalter eine Möglichkeit existiert.

**Comment by hsteinme** [comment]
Zunächst zum **Thema "Regen"**:

Hier werden auf der üblichen Schnittstelle die folgenden Felder zum Adapter übertragen:

- cfg.rd = Verzögerung des Mähbeginns nach Regenende in Minuten oder 0 = bei Regen mähen
- dat.rain.s = Regenverzögerung 0 = inaktiv / 1 = aktiv
- dat.rain.cnt = Verbleibende Zeit der Regenverzögerung in Minuten

Bei bzw. nach Regen gilt dann folgender Ablauf:

- bei Trockenheit: “rain“:{"s":0,"cnt":0}
- bei feuchtem Regensensor: “rain“:{"s":1,"cnt":40} (z.B. 40 = Regenverzögerung)
- Regensensor wieder trocken: .cnt in “rain“:{"s":1,"cnt":40} wird minutenweise runtergezählt
- Regenverzögerung abgelaufen: “rain“:{"s":0,"cnt":0}

Der Wert cfg.rd (und damit der Indikator "bei Regen mähen") wird bereits im Adapter abgebildet, und zwar auf den Datenpunkt mower.waitRain. Der Zustand dat.rain.s = 1 wird indirekt in mower.error = 5 (raining) abgebildet. Im Adapter fehlt demnach lediglich die Wartezeit bis zum Ende der Regenverzögerung (= dat.rain.cnt). 

Nun zum **Thema "Igel"**:

Die Kennung "Rettet die Igel" ist ein Teil der für die automatische Zeitplanung des Mähers erforderlichen Daten, u.a. auch Mähpausen und Bewässerungszeiten, Gras- und Bodenarten sowie Düngung und Zeiterhöhungsgrade. Diese Daten stehen auf einer gesonderten Schnittstelle zur Verfügung.

Ich stelle mir jedoch die Frage, was die Parameter des Zeitplanungsautomaten in einer Home Automation wie ioBroker verloren haben. Ein Automat sollte doch wohl keinem anderen Automaten dazwischen funken. Falls nur die Anzeige dieser Werte (ohne Änderungsmöglichkeit) gewünscht wird: Wo ist der Mehrwert dann gegenüber der App?

**Comment by Creekhail** [comment]
Das Argument mit "ein Automat sollte doch wohl keinem anderen Automaten dazwischen funken" würde am Ende bei einer Robotersteuerung doch bedeuten, dass sämtliche Steuerung außerhalb der Originalapp abzulehnen wäre.
Ich habe mir in iobroker eine Oberfläche gebaut, die zwar auf der automatischen Steuerung der Originalapp aufbaut - also z.B. die Mähzeiten nicht verändert sondern automatisch berechnen lässt und nur anzeigt, jedoch bleiben immer noch Einstellungen übrig, die ich gern über die VIS-Oberfläche vornehmen würde. Das Argument liegt dabei auf der Hand - ich nehme an genauso wie es auch beim Party-Modus der Fall ist => ich möchte nicht extra die Originalapp auf irgendeinem Handy öffnen um den Schalter zu betätigen.
Konkret sieht das bei mir so aus: Ich kann über iobroker die automatische Zeitplanung und den Party-Modus ein- und ausschalten. Jetzt dachte ich eben noch an den Rest der Schalter, die ich manchmal in der Originalapp nutze.
Was den Schalter "Rettet die Igel" betrifft ist der allerdings nicht allzu wichtig, da ich nur in Ausnahmefällen überhaupt diese Einstellung verändern werde - dann in die Originalapp zu wechseln wäre jetzt kein Beinbruch.
Im Grunde gilt das natürlich aber auch mehr oder weniger für alle Schalter: Wenn man sich eine zentrale Oberfläche für die Steuerung im Haus baut, möchte man die Funktionalität eben auf einer Oberfläche vereinen. Ein Tablet im Kioskmodus der alles zentral steuert. Je mehr ich dort integrieren kann, desto weniger Bedarf um in die Originalapps zu wechseln.
Was den Regenschalter betrifft: Danke für die Erklärung, das hilft mir auf jeden Fall bereits wieder weiter.

**Comment by hsteinme** [comment]
(1) Die App ist kein Automat, sie ist lediglich eine Oberfläche zur Einstellung der Parameter des Automaten, der sich irgendwo in der Cloud befindet. Schließlich will der Mäher ja auch gesteuert werden, wenn die App geschlossen ist.

(2) Dein Ansatz einer zentralen Steuerung "über alles" ist ja nur umsetzbar, wenn der Adapter schreibenden Zugriff auf die Parameter des Automaten hat - was ich persönlich bezweifle. Aber dazu muss @MeisterTR was sagen können.

**Comment by Creekhail** [comment]
Ich finde über den Adapter geht bereits sehr viel - vor allem wenn man sieht wie die meisten darüber quasi die vollständige Kontrolle übernehmen und die Automatik komplett ausschalten.
Letztendlich geht es bei mir ja um einen Mix aus beidem. Versteht mich nicht falsch, letztendlich ist es natürlich ein Hobby und Bastelarbeit für den Heimbereich was ich hier treibe und ich bin froh über jedes kleine Feature, was ich dabei realisiere. Man freut sich halt über Kleinigkeiten wenn wieder etwas mehr funktioniert, aber natürlich steckt da nicht viel Notwendigkeit und tiefer Sinn hinter manchen Dingen.

**Comment by MeisterTR** [comment]
Is da denn überhaupt einen cloudbasierte Steuerung hinter ? Meine eigentlich, dass es nur auf hinterlegte Werte und Formeln ein mähprofil generiert ä, welches  dann wie jede manuelle Änderung an den Mäher übertragen wird...

**Comment by Creekhail** [comment]
So habe ich das eigentlich auch bisher verstanden. In der Cloud werden die Werte gespeichert und damit Berechnungen durchgeführt. Z.B. für die Erstelung des automatischen Zeitplanes. Allerdings ist der Roboter völlig ohne Internetverbindung lauffähig, weil die entscheidenden Wert auf ihm hinterlegt werden. Wie sie dort zu Stande kommen, kann auf verschiedene Arten beeinflusst werden.
Die Handyapp verändert letztendlich auch nur die Grundwerte in der Cloud und von dort wird dann der Roboter mit neuen Werten versorgt. Oder habe ich da jetzt etwas falsch verstanden?

**Comment by hsteinme** [comment]
Ja, aus den in der App eingegebenen Parametern wird ein Mähplan erstellt, der auch in den MQTT Daten sichtbar ist. Nutzer des automatischen Mähplans haben jedoch berichtet, dass sich dieser Mähplan auch ändert, ohne dass sie in der App getätigte Eingaben geändert haben. Es gibt also zusätzliche Daten aus dem "Umfeld" des Mähers, die der Automat in die Berechnung des Mähplans einfließen lässt. Welche Umfeld-Faktoren dies sind und wie sie sich auf den Mähplan auswirken, behandelt Positec natürlich als Betriebsgeheimnis. Niemand will es schließlich seinen Mitbewerbern zu einfach machen, ihn zu kopieren.

**Comment by MeisterTR** [comment]
ok also damit mach ich den issue zu, da der automatische mähplan gegensätzlich zum adaptzer arbeitet und auch über die cloud konfiguriert wird.
