### ISSUE TITLE
more incorrect types of states

### ISSUE THREAD

**Issue by Megawaldi** [iobroker-community-adapters/ioBroker.worx#269]
Describe the bug

many message in log about incorrect state types

To Reproduce

in log you find many entries about incorrect types of states, like this:

worx.0 | 2021-06-05 10:12:39.093 | info | State value to set for "worx.0.201830190902005138CE.weather.lastUpdate" has to be type "number" but received type "object"
-- | -- | -- | --
worx.0 | 2021-06-05 10:12:39.091 | info | State value to set for "worx.0.201830190902005138CE.weather.humidity" has to be type "string" but received type "number"
worx.0 | 2021-06-05 10:12:38.733 | info | State value to set for "worx.0.201830190902005138CE.areas.startSequence" has to be stringified but received type "object"

Expected behavior

All states have the correct type and no messages like above.

Versions:

    Adapter version: 1.3.6
    JS-Controller version: 3.3.11
    Node version: v12.22.1
    Operating system: Ubuntu 20.04.2 LTS

Additional context

**Comment by hsteinme** [comment]
Please see Change Log 1.3.7 (03.06.2021):  (TA2k) type fixes

**Comment by Megawaldi** [comment]
On 1.3.7 i got one Error:


worx.0 | 2021-06-05 21:51:38.831 | info | State value to set for "worx.0.201830190902005138CE.weather.humidity" has to be type "string" but received type "number"
-- | -- | -- | --

**Comment by TA2k** [comment]
Delete the states manually and install latest version from github
