### ISSUE TITLE
Absturz des Adapters bei Rohdaten

### ISSUE THREAD

**Issue by Stefan47110815** [iobroker-community-adapters/ioBroker.worx#274]
**Describe the bug**  
Bei Setzen des Flags Rohdaten hinzufügen stürzt der Adapter ab. Im Log steht folgendes:

worx.0 | 2021-06-11 10:14:31.118 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
-- | -- | -- | --
worx.0 | 2021-06-11 10:14:31.117 | error | Error:  The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."     at validateId  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)     at Worx.setObjectNotExists  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17)     at  /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1576:16     at new Promise (&lt;anonymous&gt;)     at Worx.setObjectNotExistsAsync  (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1575:16)     at  /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:134:31     at Array.forEach (&lt;anonymous&gt;)     at extractArray  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:81:17)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:47:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/main.js:175:29
worx.0 | 2021-06-11 10:14:31.112 | error | unhandled  promise rejection: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-11 10:14:31.111 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
worx.0 | 2021-06-11 10:14:31.092 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."

**To Reproduce**  
Ein und ausschalten der Rohdaten

**Expected behavior**  
Anzeigen der Rohdaten in den Objekten

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 1.3.7
 - JS-Controller version: 3.312
 - Node version: 12.22.1
 - Operating system: Linux

**Additional context**

**Comment by hsteinme** [comment]
Das Problem tritt nicht grundsätzlich auf. In meiner Umgebung jedenfalls nicht, auch nicht, wenn ich den automatischen Zeitplan aktiviere und keine Mähpausen eintrage.

Zur näheren Analyse stell doch mal den Loglevel des Adapters auf Debug, starte den Adapter neu, suche im Log die Zeile, die "auto_schedule_settings" enthält und zitiere diese bitte hier in voller Länge.

**Comment by Stefan47110815** [comment]
host.ioBroker | 2021-06-12 12:15:15.599 | error | Caught  by controller[12]: Error: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
-- | -- | -- | --
host.ioBroker | 2021-06-12 12:15:15.598 | error | Caught  by controller[10]: Error: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
host.ioBroker | 2021-06-12 12:15:15.596 | error | Caught  by controller[8]: Error: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
host.ioBroker | 2021-06-12 12:15:15.594 | error | Caught  by controller[6]: Error: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
host.ioBroker | 2021-06-12 12:15:15.591 | error | Caught  by controller[4]: Error: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
host.ioBroker | 2021-06-12 12:15:15.590 | error | Caught  by controller[2]: Error: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
host.ioBroker | 2021-06-12 12:15:15.588 | error | Caught  by controller[0]: Error: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:13.003 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:13.002 | error | Error:  The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."     at validateId  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)     at Worx.setObjectNotExists  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17)     at  /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1576:16     at new Promise (&lt;anonymous&gt;)     at Worx.setObjectNotExistsAsync  (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1575:16)     at  /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:134:31     at Array.forEach (&lt;anonymous&gt;)     at extractArray  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:81:17)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:47:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/main.js:175:29
worx.0 | 2021-06-12 12:15:12.998 | error | unhandled  promise rejection: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.990 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.990 | error | Error:  The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."     at validateId  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)     at Worx.setObjectNotExists  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17)     at  /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1576:16     at new Promise (&lt;anonymous&gt;)     at Worx.setObjectNotExistsAsync  (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1575:16)     at  /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:134:31     at Array.forEach (&lt;anonymous&gt;)     at extractArray  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:81:17)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:47:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/main.js:175:29
worx.0 | 2021-06-12 12:15:12.985 | error | unhandled  promise rejection: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.972 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.972 | error | Error:  The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."     at validateId  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)     at Worx.setObjectNotExists  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17)     at  /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1576:16     at new Promise (&lt;anonymous&gt;)     at Worx.setObjectNotExistsAsync  (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1575:16)     at  /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:134:31     at Array.forEach (&lt;anonymous&gt;)     at extractArray  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:81:17)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:47:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/main.js:175:29
worx.0 | 2021-06-12 12:15:12.971 | error | unhandled  promise rejection: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.963 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.963 | error | Error:  The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."     at validateId  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)     at Worx.setObjectNotExists  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17)     at  /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1576:16     at new Promise (&lt;anonymous&gt;)     at Worx.setObjectNotExistsAsync  (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1575:16)     at  /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:134:31     at Array.forEach (&lt;anonymous&gt;)     at extractArray  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:81:17)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:47:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/main.js:175:29
worx.0 | 2021-06-12 12:15:12.962 | error | unhandled  promise rejection: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.955 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.955 | error | Error:  The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."     at validateId  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)     at Worx.setObjectNotExists  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17)     at  /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1576:16     at new Promise (&lt;anonymous&gt;)     at Worx.setObjectNotExistsAsync  (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1575:16)     at  /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:134:31     at Array.forEach (&lt;anonymous&gt;)     at extractArray  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:81:17)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:47:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/main.js:175:29
worx.0 | 2021-06-12 12:15:12.954 | error | unhandled  promise rejection: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.947 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.946 | error | Error:  The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."     at validateId  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)     at Worx.setObjectNotExists  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17)     at  /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1576:16     at new Promise (&lt;anonymous&gt;)     at Worx.setObjectNotExistsAsync  (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1575:16)     at  /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:134:31     at Array.forEach (&lt;anonymous&gt;)     at extractArray  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:81:17)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:47:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/main.js:175:29
worx.0 | 2021-06-12 12:15:12.943 | error | unhandled  promise rejection: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.907 | error | The  id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.907 | error | Error:  The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."     at validateId  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)     at Worx.setObjectNotExists  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17)     at  /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1576:16     at new Promise (&lt;anonymous&gt;)     at Worx.setObjectNotExistsAsync  (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1575:16)     at  /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:134:31     at Array.forEach (&lt;anonymous&gt;)     at extractArray  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:81:17)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:47:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:49:17     at Array.forEach (&lt;anonymous&gt;)     at extractKeys  (/opt/iobroker/node_modules/iobroker.worx/lib/extractKeys.js:41:20)     at /opt/iobroker/node_modules/iobroker.worx/main.js:175:29
worx.0 | 2021-06-12 12:15:12.857 | error | unhandled  promise rejection: The id  "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days."  is invalid. Ids are not allowed to end in "."
worx.0 | 2021-06-12 12:15:12.484 | debug | {"_events":{},"_eventsCount":0,"_maxListeners":100,"serial":"2018301985120021876E","online":true,"raw":{"id":262619,"product_id":51,"user_id":214053,"serial_number":"2018301985120021876E","mac_address":"98D863345F76","name":"M1000","locked":false,"firmware_version":3.24,"firmware_auto_upgrade":true,"push_notifications":true,"sim":null,"push_notifications_level":"warning","test":0,"iot_registered":true,"mqtt_registered":true,"pin_code":"ADCB","registered_at":"2019-06-18   00:00:00","online":true,"app_settings":null,"accessories":{"digital_fence":true},"features":{"provisionable":true,"wifi_pairing":"smartlink","tracking_firmware":true,"provisioning_replaceable":true,"rain_delay_start":3.08,"mac_address":true,"unrestricted_mowing_time":true,"multi_zone":true,"multi_zone_percentage":true,"multi_zone_zones":4,"mqtt":true,"display_type":"lcd","input_type":"keyboard_arrow_keys","lock":true,"pin":true,"rain_delay":true,"chassis":"m_2019","one_time_scheduler":3.15,"scheduler_two_slots":3.15,"auto_lock":3.25,"wifi_connection":"smartlink_display"},"pending_radio_link_validation":null,"mqtt_topics":{"command_in":"PRM100/98D863345F76/commandIn","command_out":"PRM100/98D863345F76/commandOut"},"warranty_registered":true,"purchased_at":"2019-06-18  00:00:00","warranty_expires_at":"2022-06-18  00:00:00","setup_location":{"latitude":50.30747017012906,"longitude":9.62371185987022},"city":{"id":2827376,"country_id":276,"name":"Sterbfritz","latitude":50.313351,"longitude":9.62282,"created_at":"2018-02-15  22:24:50","updated_at":"2018-02-15  22:24:50"},"time_zone":"Europe/Berlin","lawn_size":1000,"lawn_perimeter":291,"auto_schedule_settings":{"exclusion_scheduler":{"days":[{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false}],"exclude_nights":true},"irrigation":false,"soil_type":"silt","nutrition":{"n":5,"p":8,"k":12},"boost":2,"grass_type":"mixed_species"},"auto_schedule":true,"distance_covered":1241445,"mower_work_time":89690,"blade_work_time":79545,"blade_work_time_reset":78932,"blade_work_time_reset_at":"2021-06-10   17:33:32","battery_charge_cycles":482,"battery_charge_cycles_reset":null,"battery_charge_cycles_reset_at":null,"messages_in":5188,"messages_out":67005,"raw_messages_in":5378,"raw_messages_out":67005,"created_at":"2019-01-16  14:30:16","updated_at":"2021-06-03  01:26:18"},"edgeCut":false,"mqtt_command_in":"PRM100/98D863345F76/commandIn","mqtt_command_out":"PRM100/98D863345F76/commandOut","message":{"cfg":{"lg":"it","id":1,"dt":"12/06/2021","tm":"12:14:33","rd":180,"sn":"2018301985120021876E","mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"sc":{"p":0,"d":[["07:45",375,1],["07:45",375,0],["07:45",375,0],["07:45",375,1],["07:45",375,0],["07:45",375,0],["07:45",375,0]],"m":1,"distm":0,"ots":{"bc":0,"wtm":30},"dd":[["15:15",375,0],["15:15",375,0],["15:15",375,0],["15:15",375,0],["15:15",375,0],["15:15",375,0],["15:15",375,0]]},"cmd":0},"dat":{"mac":"98D863345F76","fw":3.24,"fwb":1,"lz":0,"rsi":-75,"lk":0,"dmp":[15.7,-4.2,359.1],"st":{"b":79693,"d":1243489,"wt":89838,"bl":291},"rain":{"s":0,"cnt":0},"bt":{"t":32.2,"v":17.29,"p":12,"nr":482,"c":0,"m":0},"le":0,"ls":7,"act":1,"conn":"wifi","modules":{"DF":{"stat":"ok"}}}}}
worx.0 | 2021-06-12 12:15:12.034 | debug | 2  Recieve User Devices:  [{"id":262619,"product_id":51,"user_id":214053,"serial_number":"2018301985120021876E","mac_address":"98D863345F76","name":"M1000","locked":false,"firmware_version":3.24,"firmware_auto_upgrade":true,"push_notifications":true,"sim":null,"push_notifications_level":"warning","test":0,"iot_registered":true,"mqtt_registered":true,"pin_code":"ADCB","registered_at":"2019-06-18   00:00:00","online":true,"app_settings":null,"accessories":{"digital_fence":true},"features":{"provisionable":true,"wifi_pairing":"smartlink","tracking_firmware":true,"provisioning_replaceable":true,"rain_delay_start":3.08,"mac_address":true,"unrestricted_mowing_time":true,"multi_zone":true,"multi_zone_percentage":true,"multi_zone_zones":4,"mqtt":true,"display_type":"lcd","input_type":"keyboard_arrow_keys","lock":true,"pin":true,"rain_delay":true,"chassis":"m_2019","one_time_scheduler":3.15,"scheduler_two_slots":3.15,"auto_lock":3.25,"wifi_connection":"smartlink_display"},"pending_radio_link_validation":null,"mqtt_topics":{"command_in":"PRM100/98D863345F76/commandIn","command_out":"PRM100/98D863345F76/commandOut"},"warranty_registered":true,"purchased_at":"2019-06-18  00:00:00","warranty_expires_at":"2022-06-18  00:00:00","setup_location":{"latitude":50.30747017012906,"longitude":9.62371185987022},"city":{"id":2827376,"country_id":276,"name":"Sterbfritz","latitude":50.313351,"longitude":9.62282,"created_at":"2018-02-15  22:24:50","updated_at":"2018-02-15  22:24:50"},"time_zone":"Europe/Berlin","lawn_size":1000,"lawn_perimeter":291,"auto_schedule_settings":{"exclusion_scheduler":{"days":[{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false},{"slots":[],"exclude_day":false}],"exclude_nights":true},"irrigation":false,"soil_type":"silt","nutrition":{"n":5,"p":8,"k":12},"boost":2,"grass_type":"mixed_species"},"auto_schedule":true,"distance_covered":1241445,"mower_work_time":89690,"blade_work_time":79545,"blade_work_time_reset":78932,"blade_work_time_reset_at":"2021-06-10   17:33:32","battery_charge_cycles":482,"battery_charge_cycles_reset":null,"battery_charge_cycles_reset_at":null,"messages_in":5188,"messages_out":67005,"raw_messages_in":5378,"raw_messages_out":67005,"created_at":"2019-01-16  14:30:16","updated_at":"2021-06-03 01:26:18"}]
&nbsp;

**Comment by hsteinme** [comment]
`The id "2018301985120021876E.rawMqtt.raw.auto_schedule_settings.exclusion_scheduler.days." is invalid. Ids are not allowed to end in "."`

Das sollte sich @TA2k einmal näher ansehen.

**Comment by TA2k** [comment]
@Stefan47110815  bitte mal mit der github version erneut testen

**Comment by Stefan47110815** [comment]
Ja, hat jetzt geklappt.
