### ISSUE TITLE
Erweiterung: Datenpunkte für Aus-/Einschalten des OffLimits Moduls

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#282]
Ab der Firmware Version 3.24b27 als Vorabversion der 3.25 kann die Nutzung eines angeschlossenen OLM per Webkommando aus- bzw. eingeschaltet werden:
```
{
	"cfg": {
		"modules": {
			"DF": {
				"cut": 0,
				"fh": 1
			}
		}
	}
}
```

- cut: OLM aus/ein während des Mähens
- fh: OLM aus/ein während der Shortcut-Erkennung für Fast Homing

Bitte entsprechende Datenpunkte implementieren. Vorschlag:
- mower.OLMSwitch_Cutting, Boolean
- mower.OLMSwitch_FastHoming, Boolean
- mower.OLMSwitch_Start, Button

Erst beim Betätigen des Buttons werden die beiden erstgenannten Werte zur Cloud übertragen.

**Comment by MeisterTR** [comment]
was ist olm? bitte ein bisschen näher beschreiben. wie soll die sende JSON Aussehen?

**Comment by hsteinme** [comment]
OLM = Off Limits Module: Es ist ein nachrüstbarer Sensor, der auf ausgelegte Magnetkabel reagiert. Beim Antreffen eines Magnetkabels dreht der Mäher um. Mit den Magnetkabeln kannst Du schützenswerte Bereiche abgrenzen, dauerhaft z.B. bei Bäumen, Blumenbeeten, Sandkästen, ..., die im Inneren des Rasens stehen, temporär z.B. bei Nachsaaten auf Teilen des Rasens. Siehe auch https://www.obi.de/zubehoer-fuer-rasenmaeher/worx-landroid-modul-flaechenabgrenzung-offlimits/p/4372330.

Fast Homing: Kurze Magnetkabel können auch in einem bestimmtem Muster als Shortcuts auf dem Begrenzungsdraht ausgelegt werden, die den Mäher veranlassen, den Draht nach links im rechten Winkel zu verlassen und beim nächsten Drahtkontakt die Heimfahrt fortzusetzen. Bei geschickter Verteilung dieser Shortcuts können Nachhausewege deutlich verkürzt werden. Zu Details siehe https://www.roboter-forum.com/core/index.php?attachment/103569-shortcut-pdf/.

Als Sende-JSON reicht folgendes aus:
`{"modules":{"DF":{"cut":0,"fh":1}}}`

**Comment by MeisterTR** [comment]
kurz Nochmal zur Syntax: 
```{"cut":0,"fh":1}``` : nimmt auf heimweg abkürzungen
```{"cut":1,"fh":0}``` : Beim Mähvorgang wird bei Kabelkontakt zum nächsten Magnetstreifen gemäht?
```{"cut":1,"fh":1}``` : beides?

mower.OLMSwitch_Start, Button was soll da passieren? Spezielle heimfahrt? welcher command?

muss leider soviel Fragen da ich "nur" das 2017 Modell habe

**Comment by hsteinme** [comment]
Kein Problem mit Deinen Fragen 👍

Betrachte bitte die beiden Parameter unabhängig voneinander. Es gibt keinen Zusammenhang zwischen den beiden Einstellungen.

**cut:** Das Magnetkabel funktioniert ähnlich wie das Begrenzungskabel. Es grenzt Gebiete dadurch ab, dass es nicht vom Mäher überfahren wird. Trifft der Mäher auf das Begrenzungskabel, "prallt" er in einem zufälligen Winkel davon ab. Trifft er auf ein Magnetkabel, "prallt" er in einem Wingel zwischen ungefähr 170° und 190° davon ab. Dies gilt halt, wenn cut auf 1 steht. Steht cut auf 0, so werden im Raseninneren liegende Magnetkabel ignoriert, also überfahren.

**fh:** Liegen zwei kurze Magnetkabelstücke in einem bestimmten Muster am/auf dem Begrenzungsdraht, so interpretiert auf der Heimfahrt der Mäher dies als ein Kommando, sich den Nachhauseweg durch einen Linksschwenk im rechten Winkel zu verkürzen. Dies gilt für fh = 1. Bei fh = 0 werden die Magnetkabelmuster am/auf dem Begrenzungsdraht ignoriert. (Generell werden die Magnetkabelstücke bei der Zonensuche und beim Kantenschnitt ignoriert, also ohne Abkürzung überfahren.)

Zu Deinen obigen **Beispielen**:
- `{"cut":0,"fh":1}` : Magnetkabel im Raseninneren werden ignoriert und damit überfahren, Magnetkabelmuster auf dem Draht werden bei der Heimfahrt beachtet und veranlassen eine Abkürzung.
- `{"cut":1,"fh":0}` : Magnetkabel im Raseninneren werden beachtet und damit nicht überfahren, Magnetkabelmuster auf dem Draht werden bei der Heimfahrt ignoriert. Die Fahrt wird also auf dem Draht fortgesetzt.
- `{"cut":1,"fh":1`} :  Magnetkabel im Raseninneren werden beachtet und damit nicht überfahren, Magnetkabelmuster auf dem Draht werden bei der Heimfahrt beachtet und veranlassen eine Abkürzung.
- `{"cut":0,"fh":0`} : Magnetkabel werden grundsätzlich ignoriert. Im Raseninneren werden sie überfahren. Am/auf dem Draht veranlassen sie kein abkürzendes Verlassen des Drahts.

**Verhalten** der OLMSwitch_* Datenpunkte: Mein Vorschlag entspricht dem bewährten Verhalten der oneTime* Datenpunkte:
- Änderungen an oneTimeWithBorder bzw. oneTimeWorkTime führen nicht zu einem Senden der Werte an die Cloud. Erst beim Betätigen von oneTimeStart werden die dann aktuellen Werte dieser beiden Datenpunkte zur Cloud geschickt.
- Änderungen an OLMSwitch_Cutting bzw. OLMSwitch_FastHoming sollen nicht zu einem Senden der Werte an die Cloud führen. Erst beim Betätigen von OLMSwitch_Start sollen die dann aktuellen Werte dieser beiden Datenpunkte zur Cloud geschickt werden.

Das Adapterverhalten hat nichts mit einer "speziellen Heimfahrt" zu tun. Es stellt lediglich Parameter beim Mäher ein, die zu gegebener Zeit das Verhalten des Mähers beim Antreffen von Magnetkabel steuern. Von daher ist kein spezielles sendCommand erforderlich. Es wird bei Drücken von OLMSwitch_Start lediglich `{"modules":{"DF":{"cut":x,"fh":y}}}` zur Cloud geschickt.

Bei weiteren Fragen oder Unklarheiten können wir auch gern einen telefonischen Austausch vereinbaren. Sprich mich dann bitte per PN unter https://www.roboter-forum.com/core/index.php?user/40544-hsteinme/ an.

**Comment by MeisterTR** [comment]
in  1.4.0 ist es drin, gerne testen

**Comment by hsteinme** [comment]
Funktioniert! Danke für die schnelle Umsetzung.
