### ISSUE TITLE
Erweiterung: Datenpunkte für Aus-/Einschalten des AutoLock-Features

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#283]
Siehe https://www.roboter-forum.com/core/index.php?attachment/103568-auto-lock-pdf/

Ab der Firmware Version 3.24b27 als Vorabversion der 3.25 kann die neu eingeführte AutoLock-Funktion per Webkommando aktiviert und deaktiviert werden:

```
{
	"cfg": {
		"al": {
			"lvl": 0,
			"t": 0
		}
	}
}
```

- lvl: AutoLock aus/ein
- t: Wartezeit in Sekunden bis PIN-Anforderung (0, 30, 60, ..., 600 / andere Werte werden von der Firmware gerundet)

Bitte entsprechende Datenpunkte implementieren. Vorschlag:
- mower.AutoLock_Level, Boolean
- mower.AutoLock_Time, Integer 
- mower.AutoLock_Start, Button

Erst beim Betätigen des Buttons werden die beiden erstgenannten Werte zur Cloud übertragen.

**Comment by hsteinme** [comment]
Sende-JSON:
`{"al":{"lvl":0,"t":0}}`

**Comment by MeisterTR** [comment]
Also kann t eine belibe Ganzzahl bis 600 sein?
auch hier die frage für Start?

**Comment by hsteinme** [comment]
Ganzzahl >= 0 und <= 600

Start-Verhalten analog zu oneTimeStart und OLMSwitch_Start gemäß https://github.com/iobroker-community-adapters/ioBroker.worx/issues/282#issuecomment-873356046.

Falls es Dir eine Hilfe sein kann, schau Dir mal im [DeskApp Plugin Pool](https://drive.google.com/drive/folders/1Z-XCyhchfsyygMCozjXBvlfhwGGsHllb) die Funktionen DoIt() in PluginAutoLockSwitch.cs (und PluginOffLimitsModuleSwitch.cs) an.

**Comment by MeisterTR** [comment]
in 1.4.0 ist es drin

**Comment by hsteinme** [comment]
- In AutoLockTimer empfangene Werte werden nicht als Zahlen dargestellt, sondern fälschlicherweise als Boolsche Werte.
- Wird bei einem Ausgangsstand "al":{"lvl":0,"t":0} AutoLock = true gesendet, so wird die Annahme dieses Wertes wegen t=0 verweigert. Er wird wieder auf false gesetzt.
- Nur wenn zuerst AutoLockTimer auf einen Wert > 0 gesetzt und gesendet wird, akzeptiert der Mäher ein AutLock = true.
- Dieser nicht dokumentierte Weg ruft Verwirrung hervor. Ich halte weiterhin den oben vorgeschlagenen Weg über einen Sende-Button für den deutlich besseren Weg. Zumal dann auch hier eine einheitliche Methode mit Blick auf die oneTime* Datenpunkte gegeben ist-

**Comment by MeisterTR** [comment]
Es gibt halt zwei varianten, einmal die "Scripter" und die "Darsteller" gerade für eine Visu ist der Weg von ich lege hier einen Schalter um drücke hier noch einen Taster zu umständlich und auch verwirrend. es wird erwartet ,dass auf eine Aktion eine Reaktion folgt. bei den Calenderdaten kommt man ohne ein Senden fast nciht aus. Also darf der Datenpunt t nicht = 0 sein? oder wird er auf 0 gesetzt wenn autolock aus ist?

**Comment by hsteinme** [comment]
- lvl=0, t=0; wird akzeptiert, AutoLock ist aus
- lvl=0, t>0: wird akzeptiert, AutoLock ist aus
- lvl=1, t>0: wird akzeptiert, AutoLock ist an mit Wartezeit t
- lvl=1, t=0: 0 wird akzeptiert, der Mäher setzt lvl=0, AutoLock ist aus

Konsequenz: Wer aus einem ausgeschalteten AutoLock heraus (also lvl=0, t=0) den AutoLock mit x Sekunden Wartezeit aktivieren möchte, muss im Adapter zuerst t=x setzen und dann lvl=1. Andersrum kommt er nicht von der Stelle.

**Comment by hsteinme** [comment]
> In AutoLockTimer empfangene Werte werden nicht als Zahlen dargestellt, sondern fälschlicherweise als Boolsche Werte.

Auf gut Deutsch: Hier liegt eine **Datenverfälschung** vor.

Die Firmware-Version 3.25 ist bereits seit einigen Tagen im Massenrollout. Im Roboter-Forum ist zu sehen, dass die AutoLock-Funktion bei Nutzern mit Kindern oder Hunden in Rasennähe gut angenommen wird. Daher die Frage: Gibt es schon einen zeitlichen Plan für eine Korrektur im Adapter?

**Comment by hsteinme** [comment]
Nachtest 1.4.3: AutoLockTimer wird nun korrekt als Zahl dargestellt.
