### ISSUE TITLE
wrong serial when using raw data

### ISSUE THREAD

**Issue by MeisterTR** [iobroker-community-adapters/ioBroker.worx#289]
@TA2k  kannst du dein addon nochmal checken, irgendwo wird darin sie seriennummer gerundet

<html>
<body>

worx.0 | 2021-07-05 10:04:35.707 | warn | State "worx.0.30174102170313010000.mower.totalTime" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
worx.0 | 2021-07-05 10:04:35.699 | debug | Test Status: 1
worx.0 | 2021-07-05 10:04:35.699 | debug | GET MQTT DATA from API: {"cfg":{"id":0,"lg":"it","tm":"12:04:21","dt":"05/07/2021","sc":{"m":1,"p":0,"d":[["00:00",0,0],["19:00",285,0],["00:00",0,0],["19:00",285,1],["10:00",90,0],["19:00",285,0],["21:45",120,1]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"301741sdfdf70313sssss"},"dat":{"mac":"F0FE6B2704FA","fw":3.52,"bt":{"t":21.8,"v":19.4,"p":100,"nr":7934,"c":0,"m":1},"dmp":[-0.8,0.9,342],"st":{"b":61556,"d":1057009,"wt":67989},"ls":1,"le":0,"lz":4,"rsi":-65,"lk":0}}

</body>
</html>

**Comment by TA2k** [comment]
Ich habe an der Stelle nichts geändert nur rein rawMQTT. Eine geänderte sn muss direkt von der mqtt nachricht kommen. Bei mir tritt das nicht auf

**Comment by MeisterTR** [comment]
hab es gerade nochmal kontrolliert, die seriennummer wird auf jedenfall in der fkt extractKeys geändert, sobald ich den aufruf raus nehme bleibt die sn wie sie sein soll. Bitte Check das nochmal woran es liegen kann.

**Comment by TA2k** [comment]
Habe den Fehler gefunden. Wußte ich auch nicht
JSON.parse("333333333333322222222")
333333333333322240000

Habs gefixt
