### ISSUE TITLE
Version 1.3.7: sendCommands > 7 führen zu Reset der Mäher-Logdatei und zum Ausschalten des Mähers

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#290]
Version 1.3.7: sendCommands > 7 führen zu Reset der Mäher-Logdatei und zum Ausschalten des Mähers

Für sendCommand ist ein Maximalwert von 7 eingestellt. Größere Werte werden automatisch auf 7 umgebogen. sendCommand = 7 ist das Kommando zum Zurücksetzen der Mäher-Logdatei und zum Ausschalten des Mähers.

Laut Code-Review ist dieser Fehler auch in Version 1.4.0 noch enthalten.

Vorschlag: Maximalwert entfallen lassen. Bei künftigen neuen sendCommand Werten oberhalb 9 können diese dann ohne Anpassung des Adapters gleich genutzt werden.

**Comment by MeisterTR** [comment]
fixed in 1.4.2

**Comment by hsteinme** [comment]
Getestet: Nach Installation aus GitHub, Stoppen des Adapters, manuellem Löschen des sendCommand Datenpunktes und Start des Adapters gelöst. Danke für die schnelle Lösung 👍
