### ISSUE TITLE
Mähzeit, Arbeitszeit außerhalb des Bereiches (Work time (24226) Time out of range 0 min < time < 720 min)

### ISSUE THREAD

**Issue by Domi920** [iobroker-community-adapters/ioBroker.worx#297]
Hallo,
habe seit kurzer Zeit folgenden Mähroboter:
**Worx Landroid M700Plus WR167E**

Allerdings ist mir aufgefallen, dass die Mähzeit **maximal 720 Minuten bzw. 12 Stunden** betragen darf.
Es sieht so aus als würden größere Werte nicht an die Worx Cloud übertragen.

Im Log Protokoll sieht man dazu folgende Fehlermeldung:
**(24226) Time out of range 0 min < time < 720 min.**

Wenn ich allerdings über die originale Landroid App eine Zeitspanne von z. B. 4:00 - 23:45 Uhr festlege meckert weder die App noch der Adapter in IOBroker.
Der Datenpunkt **"Work time"** aktualisiert sich auf den Wert **1185**.

Ist diese Limitierung von maximal 12 Stunden Mähdauer bereits aufgehoben worden?

Kurz nebenbei noch eine Frage:
Leider gibt es in den Datenpunkten nur eine Startzeit & die Mähdauer zum festlegen.
Wäre es möglich die Endzeit auch anzeigen & editierbar zu lassen?

_(Natürlich kann man dass auch mit Hilfe eines Skriptes & Datenpunkte machen, aber schöner wäre es wenns im Adapter integriert wäre)_

Gruß Dominik

**Comment by MeisterTR** [comment]
fixed on git
