### ISSUE TITLE
firmware_auto_upgrade Fehler

### ISSUE THREAD

**Issue by Cosmicbase** [iobroker-community-adapters/ioBroker.worx#298]
firmware_auto_upgrade lässt sich weder mit button noch mit Schalter steuern.
Wenn ich auf false setze wird der DP automatisch wieder auf true gesetzt.
Und das ganze auch umgekehrt.
Der DP wird zwar richtig angezeigt, also wenn ich Firmware Update in der App auf auto setze habe ich im DP true und auch umgekehrt. Nur ändert sich in der App nix wenn ich das Verhalten über den Adapter simmuliere.

Bitte im Adapter überprüfen ob ein Fehler drin ist.
![Unbenannt](https://user-images.githubusercontent.com/31271212/125183236-2782b480-e215-11eb-99c6-af8afdfc269c.PNG)

**Comment by MeisterTR** [comment]
Der datenpunkt ist nicht schaltbar, er dient nur zur Visualisierung.
