### ISSUE TITLE
Warnung: partyModus has no Object

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [iobroker-community-adapters/ioBroker.worx#301]
Adapter erzeugt Warnung

`State "worx.0.XXXXXX.mower.partyModus" has no existing object, this might lead to an error in future versions.`

Löschen und neu Erzeugen der Instanz bringt keine Änderung.

**Comment by Feuer-sturm** [comment]
Warnung tritt mit worx Adapter 1.4.1 auf und js-controller 3.3.14

**Comment by MeisterTR** [comment]
test 1.4.2

**Comment by OstfrieseUnterwegs** [comment]
Fixed, Danke
