### ISSUE TITLE
Werte werden nicht mehr automatisch aktualisiert

### ISSUE THREAD

**Issue by tofrie** [iobroker-community-adapters/ioBroker.worx#302]
Hallo zusammen,

mir ist aufgefallen, dass die Werte meines Landroids nicht mehr automatisch aktualisiert werden. Diese werden nur aktualisiert wenn ich in der App den Bildschirm herunterziehe um eine Aktualisierung anzustoßen. Ansonsten passiert nichts.

**Comment by MeisterTR** [comment]
Das ist ein Problem deines Landroids. Entweder ist die Internetverbindung nicht stabil oder er hat ein anderes Problem. Der Adapter bekommt die Werte er holt sie nicht, also wenn sie nicht aktualisiert werden ist irgendwo ein problem vom landroid zur cloud

**Comment by Cosmicbase** [comment]
Das Problem hatte ich auch schon mal angesprochen. Die App bzw. Cloud aktualisiert alle 10 Minuten die Daten ausser bei einer Veränderung.
Also wenn sich der Status in der App ändert, dann auch im Adapter ☺️

**Comment by MeisterTR** [comment]
Das Problem ist, dass die App eine Aktualisierung der Daten anstößt. Dieser Vorgang ist aber vom Hersteller untersagt für die smarthome Software, da die datenlast zu groß wird. Ich selber hatte das Problem auch zu Beginn. Und es war direkt weg al ich einen neuen wlan AP im Garten Bereich installiert habe.
