### ISSUE TITLE
Daten werden nicht mehr aktualisiert/nicht vorhanden

### ISSUE THREAD

**Issue by mbhomie007** [iobroker-community-adapters/ioBroker.worx#305]
Die Daten im ioBroker Addon werden seit einigen Daten nicht mehr aktualisiert.

In der Android App sind alle Daten aktuell, ein manuelles aktualisieren in der App bringt nichts.
Die Daten im Screenshot sind 10 Tage alt.
Ich habe zum Beispiel schon die Version 3.25 drauf, hier steht noch die 3.24.

![image](https://user-images.githubusercontent.com/64688879/126322228-7bac80b9-c27d-42a3-b418-533e73987013.png)

Siehe Timestamp:

![image](https://user-images.githubusercontent.com/64688879/126323206-531efe09-9168-426b-b28b-b6d45ff0a78f.png)

Die Wetter Daten sind überhaupt nicht vorhanden:

![image](https://user-images.githubusercontent.com/64688879/126322450-c2d5daa2-3377-429a-8099-1f355b062d7f.png)

Hunderte Fehlermeldungen im LOG:

![image](https://user-images.githubusercontent.com/64688879/126322753-6bb1657f-3bae-4ad6-a1bd-20ddb5cf127e.png)

![image](https://user-images.githubusercontent.com/64688879/126322821-e53b8eda-4728-40c1-a880-cc7936fe83d8.png)

WORX Landroid L1000 Modell 2021 
Firmware V3.25.

![image](https://user-images.githubusercontent.com/64688879/126324195-09197c13-f171-4221-9b84-5150b7be3baa.png)

**Comment by MeisterTR** [comment]
Bitte die version von git installieren und testen

**Comment by mbhomie007** [comment]
@MeisterTR 
Welche Version meinst du?
Ich habe die letzte Version 1.4.1 installiert.

**Comment by MeisterTR** [comment]
Ich meine die 1.4.1 von GITHUB da ist eine änderung drin die die du brauchst oder and die 1.4.2 warten

**Comment by mbhomie007** [comment]
Vielen Dank für deine Rückmeldung.
Dann warte ich auf die Version 1.4.2 um direkt über das Webinterface zu updaten.

Kannst du schon ca. sagen, wann die Version raus kommt?

**Comment by MeisterTR** [comment]
test 1.4.2
