### ISSUE TITLE
Version 1.4.1: Syntaxfehler beim Senden von OLMSwitch_Cutting und OLMSwitch_FastHoming

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#307]
Übertragene Werte für OLMSwitch_Cutting und OLMSwitch_FastHoming werden von der Cloud wegen eines Syntaxfehlers im JSON-String nicht übernommen: Die geschweiften Klammern sind nicht paarig.

Log:
`Worxcloud MQTT sendMessage to xxx Message: {"modules":{"DF":{"cut":1,"fh":1}}`
`___________________________________________1__________2_____3______________32 --------> 1 ?????`

siehe main.js:
`msg.cut = state.val | 0;`
`that.WorxCloud.sendMessage('{"modules":{"DF":' + JSON.stringify(msg) + '}', mower.serial);`
`msg.fh = state.val | 0;`
`that.WorxCloud.sendMessage('{"modules":{"DF":' + JSON.stringify(msg) + '}', mower.serial);`

**Comment by MeisterTR** [comment]
Okay da fehlt ne klammer. Fix ich die tage, bin noch im urlaub

**Comment by hsteinme** [comment]
Ich wünsche Dir einen weiterhin schönen Urlaub!

**Comment by MeisterTR** [comment]
test 1.4.2

**Comment by hsteinme** [comment]
Nachtest mit 1.4.3: Problem behoben
