### ISSUE TITLE
Connect to Worx server

### ISSUE THREAD

**Issue by ZoltanBrindza** [iobroker-community-adapters/ioBroker.worx#315]
HI
Sometimes the connection to the server fails.Do you have this problem too?Is it a server problem?
Thank you

**Comment by Cosmicbase** [comment]
Please reinstall the Firmware for your mower.
I have no problems with connecting server via adapter.

**Comment by hsteinme** [comment]
The suggestion to reinstall the firmware in this case makes no sense in my experience.

@ZoltanBrindza: Where do you get which error message? What does the log file say? How stable is your Wi-Fi connection to the mower? Is Wi-Fi available on the entire lawn?
