### ISSUE TITLE
Wrong Type by Datapoint since JS-Controller 3.3

### ISSUE THREAD

**Issue by metaxa1** [iobroker-community-adapters/ioBroker.worx#324]
v1.4.3

<html>
<body>

  |   |   |  
-- | -- | -- | --
worx.0 | 2021-08-07 14:15:22.308 | info | (5381) State value to set for "worx.0.201730190911000203F7.weather.lastUpdate" has to be type "date" but received type "number"
worx.0 | 2021-08-07 14:15:22.277 | info | (5381) State value to set for "worx.0.201730190911000203F7.weather.humidity" has to be type "string" but received type "number"
worx.0 | 2021-08-07 14:15:16.924 | info | (5381) found DoubleShedule, create states...
worx.0 | 2021-08-07 14:15:14.925 | info | (5381) worx is selected
worx.0 | 2021-08-07 14:15:14.772 | info | (5381) starting. Version 1.4.3 in /opt/iobroker/node_modules/iobroker.worx, node: v12.22.2, js-controller: 3.3.15
worx.0 | 2021-08-07 14:15:04.680 | info | (940) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

</body>
</html>

**Comment by mbhomie007** [comment]
Still present
