### ISSUE TITLE
eigenständiger "Manueller Stopp" und somit "Kabel fehlt"

### ISSUE THREAD

**Issue by RoboCop0815** [iobroker-community-adapters/ioBroker.worx#337]
ich habe einen WR141E mit der aktuellen 3.25 drauf und mein Problem ist, das er nach der Rückkehr in die "Ausgangsposition" sich irgend wann, zu unterschiedlichen Zeiten, eigenmächtig mit einem "Manueller Stopp" ausschaltet was zu einem "Kabel fehlt" führt.
Ich habe, wenn ich mich recht erinnere auch den Worx Adapter angepasst.
Der Worx Support hat dazu geantwortet: " Wenn das vor dem Update nicht der Fall war, dann empfehle ich Ihnen vorerst wieder
Liegt das jetzt an der Firmware oder muss/sollte ich den Fehler wo anders suchen? 
**Kann der Worx Adapter einen Befehl zum "manuellen Stopp" senden?**
Also ist dir der Fehler bekannt und/oder haben andere auch das Problem oder nur ich?
Würde mich über eine Antwort freuen.
Grüße Robbie
Der Worx Adapter hat die Version 1.4.3

**Comment by Cosmicbase** [comment]
Über den Adapter kann man einen manuellen Stop senden. Aber warum sollte das der Adapter von selbst machen?

Wenn der Robbie von alleine stehen bleibt, sich von alleine ausschaltet oder die sync mit der Cloud nicht passt... würde ich immer die Firmware neu installieren. Das hat bei meinem Sync Problem mit Cloud geholfen.

**Comment by hsteinme** [comment]
Der Mäher kann aus dem Web niemals einen Auftrag für einen manuellen Stopp erhalten. Das gibt die Schnittstelle einfach nicht her. Also kann auch der Adapter oder ein ioBroker Skript oder eine App den Mäher nicht in den manuellel Stopp-Zustand bringen.

Zu den Symptomen "Manueller Stopp" und "Kabel fehlt" bist Du am besten in [roboter-forum.com](https://www.roboter-forum.com/index.php?board/81-worx-kress-landxcape/) aufgehoben. Als Einstiegslektüre eompfehle ich den [FAQ-Abschnitt "Fehlermeldung -E1- Kabel fehlt    (Error wire missing OR outside wire)"](https://www.roboter-forum.com/index.php?thread/35552-faq-allgemein/&postID=452480#post452480).

Da Dein Thema hier beim Adapter völlig falsch aufgehoben ist, empfehle ich Dir, diesen  Issue zu schließen.
