### ISSUE TITLE
Missing Installation Guide

### ISSUE THREAD

**Issue by int5749** [iobroker-community-adapters/ioBroker.worx#34]
Hi all,
I like to install this but wasn't ablt to find any installation guide for this. Anyone working on this, or can you please direct me to that one?

Regards
Joerg

**Comment by MeisterTR** [comment]
Where is the problem?

**Comment by int5749** [comment]
Hi,
Sorry if this was wrongly opened as issue, but I wasn‘t able to find any
guide how to install this in order to connect to openHAB :-/

Are you able to advise??

Regards
Joerg

MeisterTR <notifications@github.com> schrieb am Di. 25. Feb. 2020 um 15:23:

**Comment by MeisterTR** [comment]
there is no way to use this with openhab, but you can use iobroker instead if openhab or use both and integrade openhab in iobroker
