### ISSUE TITLE
Fehler in api.js bei Multi-Mäher-Betrieb

### ISSUE THREAD

**Issue by nefiertsrebliS** [iobroker-community-adapters/ioBroker.worx#346]
**Fehlerbeschreibung**  
Sind in der Cloud mehr als ein Mäher registriert, so werden beim Online-Check immer nur die Daten des **ersten** Mähers als Status gesendet.

**Maßnahme**  
Ersetzt man in der api.js in Zeile 339
`                let akt_mower = that.mower.find(mower => element.serial_number);
`
durch 
`                let akt_mower = that.mower.find(mower => mower.serial === element.serial_number);
`
funktioniert der Online-Status auch im Multi-Mäher-Betrieb.

**Comment by MeisterTR** [comment]
fixed in next version
