### ISSUE TITLE
Erweiterung: Neuer Datenpunkt mower.Torque zur Drehmomentanpassung

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#353]
Mit Version 3.26 (bzw. der Roboter-Forum-internen Vorabversion 3.25b34) kann über das Web-API eine Nachjustage des Drehmoments des Mähers vorgenommen werden. Der Justagewert ist eine Ganzzahl zwischen -50 und 50. Dabei bedeuten zum Beispiel: 0 = Standardwert der Firmware, -10 = Standardwert minus 10%, 10 = Standardwert plus 10%. Die Nachjustage kann im laufenden Betrieb des Mähers vorgenommen werden.

mqtt-Element: cfg.tq
zu senden: {tq:##}

https://www.roboter-forum.com/index.php?thread/54309-firmware-v3-25b36-vorabversion-der-3-26/

**Comment by hsteinme** [comment]
Die Firmware Version 3.26 ist mittlerweile generell freigegeben. Im Roboter-Forum kommen erste Anfragen zur Drehmoment-Einstellung per ioBroker, da manche in Abhängigkeit von der anzusteuernden Zone mit verschiedenen Drehmomenten arbeiten möchten.

**Comment by mbhomie007** [comment]
@MeisterTR

Möchte mal nett nachfragen, wann die neue Version rauskommt?
Wird noch an dem Adapter gearbeitet?

**Comment by MeisterTR** [comment]
please test 1.5.0

**Comment by hsteinme** [comment]
Neuer Datenpunkt ist nicht zu sehen, siehe https://github.com/iobroker-community-adapters/ioBroker.worx/issues/365

**Comment by mitch85** [comment]
was genau bedeuten denn das? Bzw. wofür ist die Anpassung gut?
Dass die reifen mehr / weniger durchdreht bei einem Hindernis? Oder ist es das Drehmoment für den Messerteller?

**Comment by hsteinme** [comment]
Es geht um das Drehmoment für die Antriebsräder. Ziel soll es sein, dasFahrverhalten den spezifischen Gegebenheiten eines Gartens anzupassen.
