### ISSUE TITLE
Break out Worx API

### ISSUE THREAD

**Issue by riker09** [iobroker-community-adapters/ioBroker.worx#36]
Hello again. As posted in the [old repository](https://github.com/MeisterTR/ioBroker.landroid-s/issues/34) I would like to know if it is possible to create an NPM package of the Worx API. As I understood from playing around with the code in this repository it has a rather tight coupling with ioBroker.

If there was a standalone NPM package of the Worx API I could imagine a whole lot more community input for that package in the future. I have some experience with NPM packages, NodeJS & TypeScript myself and would like to help. But I wanted to check with you beforehand and make sure that this is actually something you want and agree with.

[EDIT]
This is pretty much a duplicate of [issue #34 in MeisterTR/ioBroker.landroid-s](https://github.com/MeisterTR/ioBroker.landroid-s/issues/34) and the other issue can be closed since that repo is marked as deprecated as far as I understood. However, since information about the Worx API and howto integrate it with *any* Home Automation system is in my experience rather scattered at the moment I'm cross-referencing issues so that other people can follow up more easily.

**Comment by MeisterTR** [comment]
Die Api.js ist tatsächlich nicht alt so sehr mit dem Adapter verheiratet, da ich sie als eigenständiges Modul geschrieben habe und dann in den Adapter eingebaut habe. Es hat sich jedoch die gesamte Struktur geändert. Vorteil ist zu einem, dass jetzt auch mehrere Mäher verarbeitet werden und flexibel die Gesamte Worx palette abgedeckt ist, deswegen hat es sich auch von landroid-s zu worx geändert. ich suche Heute abend nochmal meine dev dateien raus und schau ob sie so virzeigefähig sind..

**Comment by harzer** [comment]
Zur not machen wir sie Vorzeigbar ;-)

**Comment by MeisterTR** [comment]
kann meine Ur Version nicht mehr finden, aber mit der api.js geht es genauso gut.

alternative wäre dies: https://github.com/EishaV/Nodjes

da müsste Eisha auch die neuen Sachen schon drin haben

die Homebridge version nutzt auch die api.js 
https://github.com/Arkrissym/homebridge-worx-landroid

hab mir die landroid-bridge gerade mal näher angeschaut, durch copy paste ist es leider nicht getan... 
wenn du/ihr hilfe braucht einfach melden

**Comment by MeisterTR** [comment]
sollte wieder gehen hab es gefixed
