### ISSUE TITLE
Version 1.5.0: Datenpunkt mower.torque nicht angezeigt im Objektbaum

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#365]
Trotz https://github.com/iobroker-community-adapters/ioBroker.worx/issues/353#issuecomment-927230864 wird in der Version 1.5.0 der Datenpunkt `mower.torque` im Objektbaum nicht angezeigt. In der Logdatei findet sich folgender Eintrag:
`State "worx.0.9999.mower.torque" has no existing object, this might lead to an error in future versions`

Stoppen der Instanz, Löschen des Objektbaums des entsprechenden Mähers und Restart der Instanz bringen keine Besserung.

`worx.0.9999.rawMqtt.message.cfg.tq` ist zu sehen und hat einen korrekten Wert,

**Comment by MeisterTR** [comment]
bitte mal die 1.5.1 testen von git

**Comment by mbhomie007** [comment]
Version 1.5.1 ist nicht zu finden. 🤔

**Comment by Cosmicbase** [comment]
Einfach Adapter über die GitHub Funktion in ioBroker darüber installieren. Und schon ist V 1.5.1 installiert.

**Comment by hsteinme** [comment]
1.5.1 installiert. Fehlerbild ist gleich geblieben - im Objektbaum und im Log. Auch nach Löschen des Objektbaums und Neustart des Adapters.

Ist denn womöglich bei der Installation was schief gelaufen?
[Protokoll_WorxAdapter_1.5.1.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/7234600/Protokoll_WorxAdapter_1.5.1.txt)

**Comment by MeisterTR** [comment]
kannst du mal einen debuglog posten incl. start

**Comment by hsteinme** [comment]
Bitte schön:
[log.zip](https://github.com/iobroker-community-adapters/ioBroker.worx/files/7238764/log.zip)

Ablauf:
- Instanz angehalten
- Objektbaum gelöscht
- Instanz gestartet
- Log gezogen

Was ist mit Zeile 153 in main,js?
`objects.module_tq.map(...` module???

**Comment by MeisterTR** [comment]
bitte nochmal von git testen, jetzt sollte es gehen

**Comment by hsteinme** [comment]
mower.torque ist nun vorhanden und funktioniert auch lesend und schreibend. Danke schön!
