### ISSUE TITLE
Version 1.5.5: Datenpunkt mower.torque nicht angezeigt im Objektbaum

### ISSUE THREAD

**Issue by fu-zhou** [iobroker-community-adapters/ioBroker.worx#374]
Hallo zusammen,

bei mir wird auch in der 1.5.5 das Drehmoment nicht angezeigt. Kann es sein, dass nicht jedes Modell "torque" zur Verfügung stellt? Ich habe einen 2 1/2 Jahre alten M500 (WR141E). Wenn ich den Adapter im Debug Modus starte, steht im Log nichts von "torque" drin, also als wenn das der Mäher gar nicht liefert. Kann das sein?

Danke vorab!

**Comment by hsteinme** [comment]
Welche Firmware-Version hast Du im Einsatz?

**Comment by fu-zhou** [comment]
> Welche Firmware-Version hast Du im Einsatz?

3.26

**Comment by hsteinme** [comment]
Gehe bitte folgenden Weg:
- Aktiviere das Debug-Logging für den worx-Adapter
- Stoppe die worx-Instanz
- Lösche den Datenpunkt `worx.0._SerienNummer_` inklusive aller darunter liegenden Datenpunkte
- Starte die worx-Instanz

Gibt es jetzt den Datenpunkt mower.torque?

Falls nicht:
- Gibt es in der Logdatei Fehlermeldungen zum worx-Adapter.
- Suche in der Lodatei einen worx-Eintrag "GET MQTT DATA from API: ...". Was steht in dieser Zeile hinter `"al":{"lvl":x,"t":xx}` (x und xx sind Zahlen)

Damit Du die Logdatei-Zeilen vollständig sehen kannst, musst Du nach dem Starten der Logdatei-Anzeige den Button "Download Lag" und anschließend den Eintrag mit dem aktuellen Datum aufrufen.

**Comment by fu-zhou** [comment]
Wollte mich grade an deine Anleitung machen, da habe ich gesehen, dass "torque" über Nacht in die Objekte gekommen ist. Allerdings mit Wert "0". Der Wert bleibt "0", egal ob der Mäher lädt oder mäht. Gibt es schon Erkenntnisse, in welchem Band "torque" eingestellt werden kann (z.B. 0-100) und wo min und max liegt?

**Comment by fu-zhou** [comment]
Heute morgen steht im Log "found torque control". Ich glaube, dass das WLAN mit geschlossenem Alurollo gestern Abend zu schwach war und der Mäher nicht kommuniziert hat, nur die Cloud mit dem Adapter...

**Comment by hsteinme** [comment]
>  Der Wert bleibt "0", egal ob der Mäher lädt oder mäht.

ich bin mir nicht sicher, ob Du das Thema der Drehmomentanpassung richtig verstanden hast. Der Torque-Wert ist ein vom Benutzer einstellbarer Konfigurationsparameter, der nicht durch Verhalten des Mähers (mähen, laden, ...) verändert wird.

> -50..+50 wäre vielleicht sinnvoll, das in die Anleitung mit aufzunehmen.

Von welcher Anleitung sprichst Du?

Hast Du Dir schon mal die Eigenschaften des torque Datenpunktes anzeigen lassen?

![image](https://user-images.githubusercontent.com/33778564/135728147-0bf19b5e-95b2-4323-a91f-c9641fc86350.png)

**Comment by fu-zhou** [comment]
Ich sehe gerade, dass ich oben einen Widerspruch eingebaut habe, da das Drehmoment einstellbar und kein Messwert ist, was ich zuerst dachte, da die Einstellung in der App nicht zu finden ist. Der Satz mit "... bleibt 0 ..." ist also überflüssig. Nachdem ich in deinem Thread -50 .. +50 gefunden habe, habe ich nicht in den Datenpunkt reingeschaut. Mit Anleitung meine ich die Liesmich-Seite vom Adapter, die man im iobroker aufrufen kann. Da gibt es einen Absatz "Die Einstellungen".
Die Funktion ist aber echt klasse, habe heute damit rumprobiert. Bei -50 schafft der Mäher es kaum, im Gras auf der Stelle zu drehen oder die Richtung zu ändern. Wenn die Drehmomentgrenze erreicht ist, bricht der Mäher die Drehung ab und versucht anders zu fahren, um im Drehmomentenbereich zu bleiben. Hätte ich das nicht beobachtet, hätte ich wohl fragen müssen, was passiert, nicht dass der Mäher mit "Drehmomentüberschreitung" oder so stehen bleibt. Ich bin bei meinem ziemlich ebenen Rasen nach eine paar Probeläufen bei -30 angekommen. Damit wendet er gut, buddelt aber keine Löcher, falls er mal hängen bleibt. Aber genau dafür wurde die Funktion ja implementiert.
Danke für die Hilfe bisher!
