### ISSUE TITLE
Anmeldung wird blockiert

### ISSUE THREAD

**Issue by sebaboehm** [iobroker-community-adapters/ioBroker.worx#39]
Hallo!
Der Adapter funktioniert leider nicht mehr.
Fehler im Log:
(20491) Connection blocked from Worx, please try again in 24h

Ich hatte vorab den Worx Support kontaktiert.
Antwort:
_Verwenden Sie zufaellig iwelche andere Software, um den Roboter zu steuern (und nicht nur unsere offizielle App)? Wenn Sie eine inoffizielle App, Software oder Suite nutzen, sollten Sie diese deinstallieren und vom Roboter trennen. Wir unterstützen nur die offizielle Worx-Landroid-App, die Sie im App Store/Play Store herunterladen können. Die meisten Apps von Drittanbietern können sich negativ auf die Servereinstellungen auswirken, sodass wir sie vorerst nicht unterstützen. Wir weisen darauf hin, dass einige dieser Apps von unseren Sicherheitssystemen als bösartig eingestuft werden könnten, was eine vorübergehende Sperrung des Kontos zur Folge hat.__ 

Kann das behoben werden?

Danke vorab.

**Comment by MeisterTR** [comment]
Die Fehlermeldung saugt doch alles. Der worx Server lässt nur eine gewisse Anzahl an Schreib und lese Vorgängen zu. Startet man den Adapter zu oft neu oder nutzt ein Script welches zu oft die Mähzeiten anpasst, wird der Mäher geblockt. Also Adapter ausschalten und morgen wieder anschalten.

**Comment by sebaboehm** [comment]
Ja, mir ist klar was die Fehlermeldung sagt. Aber es ändert sich seit Tagen nichts daran.
Deswegen habe ich mich an den Worx Support gewendet woraufhin die beschriebene Antwort kam.
Mein Account ist geblockt. Und Worx hat offernbar kein Interesse daran, das der Adapter genutzt wird: _Wenn Sie eine inoffizielle App, Software oder Suite nutzen, sollten Sie diese deinstallieren und vom Roboter trennen. Wir unterstützen nur die offizielle Worx-Landroid-App_...
Ich verwende im übrigen nur den Adapter. Kein Skript oder sonst irgendwas.

**Comment by MeisterTR** [comment]
Lass die app und den Adapter mal für 24 Stunden geschlossen, also auch nicht mal gucken obs geht. Danaxh sollte es wieder gehen. Das kann auch von mehren neustarts in verbindung mit app nutzung zustande kommen.

**Comment by romerod** [comment]
Ich denke es wäre noch gut der api.js eine Disconnect() methode hinzuzufügen um die Verbindung zu MQTT und den online check zu beenden.
function Disconnect() {
  this.mqttC.end();
  clearInterval(this.interval);
}
