### ISSUE TITLE
Fehlermeldung im Log

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.worx#40]
Ich habe seit ein paar Wochen regelmäßig Fehler im Log. Meistens um 9 Uhr und um 11 Uhr:

worx.0 | 2020-04-15 11:00:42.090 | error | (913) Onlinecheck: couldnt get data StatusCodeError: 502 -  "<html>\r\n<head><title>502 Bad  Gateway</title></head>\r\n<body>\r\n<center><h1>502  Bad  Gateway</h1></center>\r\n<hr><center>nginx</center>\
-- | -- | -- | --

Nach Lust und Laune kommen die Fehler dann auch noch Nachmittags.

**Comment by hombach** [comment]
Hier identisches Verhalten  mit V1.0.2, teste zur Zeit ein zusätzliches Error Handling
