### ISSUE TITLE
sendCommand und Pause teilweise ohne Funktion

### ISSUE THREAD

**Issue by RogerRabbit79** [iobroker-community-adapters/ioBroker.worx#487]
Meine höchste Wertschätzung für die geleistete Arbeit an dem Worx-Adapter.
Habe ihn seit ein paar Tagen im Einsatz und finde ihn klasse.

Nun habe ich mich heute an ein paar Funktionen versucht und dabei festgestellt, dass der Worx Landroid auf die Eingaben "Pause" (boolean) und "Send Command" (2 - Stop) nicht reagiert. Der WLAN-Router ist bei diesen Eingaben nur wenige Meter ohne Hindernis entfernt.

[Landroid Protocol.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/8311641/Landroid.Protocol.txt)

Habe einmal das Debug-Protokoll angehängt, da ich noch nicht weiß, wie ich das hier einfügen kann. Mir scheint, dass die Eingabe zwar ankommt, aber nicht verarbeitet werden kann...

Ich hoffe, jemand kann mir hierbei helfen.

**Comment by hsteinme** [comment]
Sehe ich das richtig, dass bei Deiner Versuchsreihe der Mäher in der Ladestation stand (`"ls":1`)?

**Comment by RogerRabbit79** [comment]
Ja, tatsächlich war er zu dem Moment in der Station, da ich auch die Funktion "Start" noch einmal getestet habe- das funktioniert auch!
Die Versuche hatten zwar vorher dasselbe Ergebnis, dennoch werde ich heute Nachmittag noch einmal dasselbe durchführen ohne den Landroid in der LS, um das Debug-Protokoll korrekt darzustellen!

**Comment by hsteinme** [comment]
Logdateien, die nicht zeitlich zu den unter realen Bedingungen gelaufenen Tests passen, sind für eine Analyse wertlos. Ein Pause- oder Heimfahrt-Kommando, wenn der Mäher in der Station steht, ist keine reale Testsituation.

Dies gilt auch für Stop-Kommandos während des Kantenschnitts. Der Mäher ignoriert bei Fahrten über den Begrenzungsdraht (Kantenschnitt, Zonensuche, Heimfahrt) grundsätzlich Stop-Kommandos.

Logdateien im Textformat erschweren denen, die Dir helfen wollen, unnötigerweise die Arbeit. Erfahrene Helfer können sich schneller und besser in den "bunt formatierten" html-Logdateien orientieren.  Bitte die html-Logdatei verzippen und über Drag & Drop in einen Beitrag hier einbetten. Die Kenntnis der Testzeitpunkte ist dabei wertvoll für den Logdatei-Analysten.
