### ISSUE TITLE
Datapoint .raw.auto_schedule_settings.nutrition

### ISSUE THREAD

**Issue by Lucky-ESA** [iobroker-community-adapters/ioBroker.worx#492]
Hallo zusammen,
der o. g. Datenpunkt hat leider 2 unterschiedliche Werte. Bei Düngermittel deaktiviert kommt nutrition":null und bei Aktivierung kommt "nutrition":{"n":7,"p":5,"k":5}.

Könnt ihr bitte in der main.js das hinzufügen?
2 x die Stelle:
`extractKeys(that, mower.serial + '.rawMqtt', mower, null, true);`

Direkt darüber das hier einfügen:
`                if (mower.raw.auto_schedule_settings.nutrition !== 'undefined') {
                    if (mower.raw.auto_schedule_settings.nutrition === null)
                        mower.raw.auto_schedule_settings.nutrition = {"n":0,"p":0,"k":0};
                }
`

Gruß//Lucky

**Comment by hsteinme** [comment]
Die gewünschte Änderung stellt einen Breaking Change dar. Daher diese Änderung bitte **dick und fett** im Change Log dokumentieren.

**Comment by Apollon77** [comment]
I will close here because "null" is !== 0,0,0 ... so... you can handle that in a script

**Comment by Apollon77** [comment]
Hmm... was changed in 1.6.x already :-(

**Comment by Apollon77** [comment]
But because ift was not correctl working I now have removed that again in 1.6.4
