### ISSUE TITLE
no more data, only connected status

### ISSUE THREAD

**Issue by kaefert** [iobroker-community-adapters/ioBroker.worx#52]
Most of my worx datapoints are not filled with new data anymore, the only thing that still works is the "online" bit, see timestamps:

![image](https://user-images.githubusercontent.com/1448723/82228786-e4d38e00-9929-11ea-9c01-39dbfd59cf89.png)

**Comment by kaefert** [comment]
okey so I've downgraded from version 1.0.1 to the one which seems to be the latest on the repository = 1.0.0, now I get the warning: `(5615) Connection blocked from Worx, please try again in 24h`

the data though seems to suggest everything is working again now..
I will monitor it in the next days and report back my findings.

**Comment by MeisterTR** [comment]
please try the 1.1.0 from git and send a debug log. The version is untested because my server is down

**Comment by kaefert** [comment]
can you point me to a guide how to install an iobroker adapter from git instead of the iobroker repositories?

**Comment by kaefert** [comment]
also say's im blocked from the worx server:



-- | -- | -- | --
-- | -- | -- | --
worx.0 | 2020-05-19 08:28:02.900 | warn | (29255) maybe your connection is blocked from Worx, please test start button, if not working, try again in 24h
worx.0 | 2020-05-19 08:28:00.158 | info | (29255) worx is selected
worx.0 | 2020-05-19 08:28:00.072 | info | (29255) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.worx, node: v10.19.0
sql.0 | 2020-05-19 08:28:00.042 | info | (4930) enabled logging of worx.0.info.connection, Alias=false

**Comment by kaefert** [comment]
A friendly user on this forum gave me instructions to a workaround:
https://www.roboter-forum.com/index.php?thread/43992-worx-landroid-wr106si-fährt-nach-dem-laden-ein-paar-cm-aus-der-station/
simply removing the robot from my account and re-adding it removed the lock and now the iobroker adapter works again. thank you for your support! :)
