### ISSUE TITLE
Beta FW 3.11b9 - worx.0.XXX.mower.mowTimeExtend startet Roboter aus der Ladestation

### ISSUE THREAD

**Issue by heymkeyu** [iobroker-community-adapters/ioBroker.worx#53]
FW 3.11b9 bringt einen DoubleScheduler für die 2019er Modelle. 
Damit sind zwei eingeplante Mähzeiten pro Tag möglich. 

Bei Verwendung dieser Version zeigt ein Setzen der worx.0.XXX.mower.mowTimeExtend auf -100 oder 0 ein problematisches Verhalten, wenn der Mäher in der Ladestation steht: Der Mäher fährt los und beginnt zu Mähen. Ein Heimschicken führt zum Andocken und sofortigem erneuten Start.
[3.11b9-LOG_WR142E_20200522_#21.html.zip](https://github.com/iobroker-community-adapters/ioBroker.worx/files/4667461/3.11b9-LOG_WR142E_20200522_.21.html.zip)

Mit der Bitte um Feedback, wie ich unterstützen kann, das Problem zu lösen. 

Gruß,
Oli

**Comment by heymkeyu** [comment]
Reduzierung um -100%:
![image](https://user-images.githubusercontent.com/48991539/82921648-e845c580-9f78-11ea-950f-990f832bc8bf.png)

**Comment by heymkeyu** [comment]
Änderung der morgigen Mähzeit Schedule 2 von 45min auf 50min:
![image](https://user-images.githubusercontent.com/48991539/82921827-1f1bdb80-9f79-11ea-959d-ad5cd4d97637.png)
![image](https://user-images.githubusercontent.com/48991539/82921875-2e9b2480-9f79-11ea-85e9-c2018a603b4f.png)

**Comment by MeisterTR** [comment]
das abarbeiten der Anfrage ist komplett identisch zur Desktop app, deswegen ist ein unterschiedliches verhalten vollkommen unplausiebel für mich.

**Comment by heymkeyu** [comment]
Verhalten ist immer reproduzierbar. Wie kann ich helfen?

**Comment by MeisterTR** [comment]
tritt das nur bei dem einen Wert auf? also nur -100 und 0 und nur in dem Object?

**Comment by heymkeyu** [comment]
Aufgefallen ist es bei genau diesem Objekt mit genau diesen Werten (Feiertags- und Regensteuerung durch Wetterstation der Homematic. Regen oder Feiertag: -100%. Kein Regen und kein Feiertag: 0%).

**Comment by heymkeyu** [comment]
Verstellen des Werts von worx.0.XXX.mower.mowTimeExtend von -100% auf 10%: Mäher fährt los.

**Comment by heymkeyu** [comment]
Verstellen der heutigen worx.0.20193019930200004504.calendar.thursday.workTime von 45 auf 50min: Wert wird gespeichert, Mäher bleibt in der LS.

**Comment by heymkeyu** [comment]
Andere beschreibbare Werte, die ich testweise ändern soll?

**Comment by heymkeyu** [comment]
Hier nochmal das letzte Log vom Mäher, bei dem die letzten Änderungen aus dem ioBroker-Adapter enthalten sind. https://drive.google.com/file/d/1PTsCscJPIOVrfscfz9UmEVHUqW-aRT9O/view?usp=sharing

**Comment by heymkeyu** [comment]
Die Änderung von 0 auf -100 oder von 0 auf 10% führt zur unerwünschten Auslösung des OneTimeScheduler: 
#02346 - 28/05/2020 09:50:33 - Mower start sequence
#02347 - 28/05/2020 09:50:33 - [One Time Scheduler] - work start 0h30min, 19.26Volt
#02348 - 28/05/2020 09:50:33 - [One Time Scheduler] - App start Request
#02349 - 28/05/2020 09:50:33 - [wifi] - mqtt ready! waiting messages
#02350 - 28/05/2020 09:50:33 - [wifi] - sending mqtt message payload: 757, appReply
#02351 - 28/05/2020 09:50:33 - [Scheduler] - Disabled By APP - 0h0min
#02352 - 28/05/2020 09:48:49 - [wifi] - mqtt ready! waiting messages

Sitzt das Problem im ioBroker Adapter oder in der Firmware?

**Comment by heymkeyu** [comment]
Kann ich noch irgendwo unterstützen? 

Die Version 3.11 liegt mir als Release Candidate vor, mit der das Problem ebenfalls weiterhin besteht. 
Ich vermute, dass sie noch diese Woche per OTA verteilt wird.

**Comment by heymkeyu** [comment]
Hier Feedback seitens Positec: 

![image](https://user-images.githubusercontent.com/48991539/83659918-739c0800-a5c4-11ea-86a2-e22febb516ce.png)


"the Landroid start one time scheduler because is requested by msg, if not need, "ots" should be null, the issue is not related to "p".

furthermore the "distm" should not be zero."

@MeisterTR - wenn Du noch was brauchst, gib bescheid. 

Gruß,
Oli

**Comment by MeisterTR** [comment]
das könnte die lösung sein. bitte mal von git probieren

**Comment by heymkeyu** [comment]
Ich glaube das sieht gut aus. 
Minimaltest erfolgreich.

Morgen werde ich das noch einige Male mit ein paar anderen Tests versuchen.

Aber so wie das derzeit aussieht, können wir das zumachen. :-) 

Ganz herzlichen Dank! 

Gruß,
Oli

**Comment by heymkeyu** [comment]
Leider ist das Thema noch nicht ganz durch. 

Der Mäher startet zwar nun nicht mehr beim Ändern der Percantage, aber der Mäher wurde nun beim unten stehenden Beispiel disabled um fast 97h.

Folglich fand heute laut Mähplan kein Start statt. 


`#00504 - 03/06/2020 21:32:44 - [Scheduler] - Disabled By APP - 96h49min
#00505 - 03/06/2020 21:32:33 - [wifi] - mqtt ready! waiting messages
#00506 - 03/06/2020 21:32:33 - [wifi] - mqtt message sent successful (-66dB)
#00507 - 03/06/2020 21:32:31 - [wifi] - mqtt ready! waiting messages
#00508 - 03/06/2020 21:32:31 - [wifi] - sending mqtt message payload: 647, appReply
#00509 - 03/06/2020 21:32:18 - [wifi] - mqtt ready! waiting messages
#00510 - 03/06/2020 21:32:18 - [wifi] - mqtt message sent successful (-65dB)
#00511 - 03/06/2020 21:32:16 - [wifi] - mqtt ready! waiting messages
#00512 - 03/06/2020 21:32:16 - [wifi] - sending mqtt message payload: 647, appReply
#00513 - 03/06/2020 21:32:16 - [Scheduler] - Disabled By APP - 96h49min
#00514 - 03/06/2020 21:32:05 - [wifi] - mqtt ready! waiting messages
#00515 - 03/06/2020 21:32:05 - [wifi] - mqtt message sent successful (-65dB)
#00516 - 03/06/2020 21:32:04 - [wifi] - mqtt ready! waiting messages
#00517 - 03/06/2020 21:32:04 - [wifi] - sending mqtt message payload: 650, appReply
#00518 - 03/06/2020 21:32:04 - [Scheduler] - Disabled By APP - 96h49min
#00519 - 03/06/2020 21:31:52 - [wifi] - mqtt ready! waiting messages
#00520 - 03/06/2020 21:31:52 - [wifi] - mqtt message sent successful (-66dB)
#00521 - 03/06/2020 21:31:51 - [wifi] - mqtt ready! waiting messages
#00522 - 03/06/2020 21:31:51 - [wifi] - sending mqtt message payload: 647, appReply
#00523 - 03/06/2020 21:31:42 - [wifi] - mqtt ready! waiting messages
#00524 - 03/06/2020 21:31:42 - [wifi] - mqtt message sent successful (-66dB)
#00525 - 03/06/2020 21:31:40 - [wifi] - mqtt ready! waiting messages
#00526 - 03/06/2020 21:31:40 - [wifi] - sending mqtt message payload: 647, appReply
#00527 - 03/06/2020 21:31:40 - [Scheduler] - Disabled By APP - 96h49min
#00528 - 03/06/2020 21:31:13 - [wifi] - mqtt ready! waiting messages
#00529 - 03/06/2020 21:31:13 - [wifi] - mqtt message sent successful (-66dB)
#00530 - 03/06/2020 21:31:11 - [wifi] - mqtt ready! waiting messages
#00531 - 03/06/2020 21:31:11 - [wifi] - sending mqtt message payload: 650, appReply
#00532 - 03/06/2020 21:25:39 - [BW] Left: unknow, Right: unknow
#00533 - 03/06/2020 21:25:37 - [wifi] - mqtt ready! waiting messages
#00534 - 03/06/2020 21:25:37 - [wifi] - mqtt message sent successful (-58dB)
#00535 - 03/06/2020 21:25:35 - Total statistics: 175907m, 13024min, blade on time: 12116min
#00536 - 03/06/2020 21:25:35 - Current cut statistics: 32m, 3min, blade on time: 0min, yaw: 175°
#00537 - 03/06/2020 21:25:35 - [wifi] - sending mqtt message payload: 650, iotUpdt
#00538 - 03/06/2020 21:25:35 - Mower at home
#00539 - 03/06/2020 21:25:35 - Mower base found :) 353mA
#00540 - 03/06/2020 21:25:34 - Mower searching home`

**Comment by heymkeyu** [comment]
Nochmals reproduziert: 

```
Line 2: worx.0	2020-06-04 20:25:38.501	debug	(30939) GET MQTT DATA from API: {"cfg":{"id":1,"lg":"it","tm":"20:25:39","dt":"04/06/2020","sc":{"m":1,"distm":6047,"ots":{"bc":0,"wtm":30},"p":-100,"d":[["00:00",0,0],["10:30",90,1],["10:30",90,1],["
	Line 4: worx.0	2020-06-04 20:25:36.936	debug	(30939) MowerTimeExtend set to : -100
	Line 5: worx.0	2020-06-04 20:25:36.936	debug	(30939) Worxcloud MQTT sendMessage to 20193019930200004504 Message: {"sc":{"m":1,"distm":0,"p":-100,"d":[["00:00",0,0],["10:30",90,1],["10:30",90,1],["10:20",90,1],["20:15",5,1],["10:30",90,1],["10:30
```

Mäher Log:

```
#00062 - 04/06/2020 20:25:39 - [wifi] - sending mqtt message payload: 648, appReply
#00063 - 04/06/2020 20:25:39 - [Scheduler] - Disabled By APP - 0h0min
#00064 - 04/06/2020 20:25:21 - [wifi] - mqtt ready! waiting messages
#00065 - 04/06/2020 20:25:21 - [wifi] - mqtt message sent successful (-55dB)
#00066 - 04/06/2020 20:25:20 - [wifi] - mqtt ready! waiting messages
#00067 - 04/06/2020 20:25:20 - [wifi] - sending mqtt message payload: 642, appReply
#00068 - 04/06/2020 20:25:17 - [BW] Left: unknow, Right: unknow
#00069 - 04/06/2020 20:25:15 - [wifi] - mqtt ready! waiting messages
#00070 - 04/06/2020 20:25:15 - [wifi] - mqtt message sent successful (-55dB)
#00071 - 04/06/2020 20:25:14 - [wifi] - sending mqtt message payload: 642, iotUpdt
#00072 - 04/06/2020 20:25:14 - Total statistics: 179181m, 13245min, blade on time: 12325min
#00073 - 04/06/2020 20:25:14 - Current cut statistics: 29m, 2min, blade on time: 0min, yaw: 197°
#00074 - 04/06/2020 20:25:13 - Mower at home
```

Neuer Start wäre 20:45 gewesen: Mäher startet nicht. 
[3.11-RC-LOG_WR142E_20200604_#29.zip](https://github.com/iobroker-community-adapters/ioBroker.worx/files/4732211/3.11-RC-LOG_WR142E_20200604_.29.zip)

Display des Mähers zeigt: "Work Canceled today"

**Comment by heymkeyu** [comment]
Hinweis auf Issue in https://www.roboter-forum.com/index.php?thread/44695-obroker-community-adapters-iobroker-worx-und-kommende-fw-3-11/ verlinkt.

**Comment by heymkeyu** [comment]
```
{
  "cfg":{"id":0,
    "lg":"it",
    "tm":"16:26:54",
    "dt":"06/06/2020",
    "sc":{"m":1,"distm":0,"ots":{"bc":0,"wtm":30},"p":-100,"d":[
      ["00:00",0,0],
      ["10:30",90,1],
      ["10:30",90,1],
      ["10:20",90,1],
      ["10:30",90,1],
      ["10:42",60,1],
      ["10:30",60,1]]},
    "cmd":0,
    "mz":[11,43,0,0],
    "mzv":[0,1,0,1,0,1,0,1,0,1],
    "rd":30,
    "sn":"XXXX","modules":{"US":{"enabled":1}
}},
  "dat":{
    "mac":"XXXX",
    "fw":3.11,
    "bt":{"t":12.0,"v":19.02,"p":100,"nr":97,"c":0,"m":1},
    "dmp":[1.8,1.8,295.1],
    "st":{"b":12399,"d":180419,"wt":13330,"bl":38},
    "ls":1,
    "le":5,
    "lz":9,
    "rsi":-65,
    "lk":1,"act":1,"tr":0,"conn":"wifi","rain":{"s":1,"cnt":30},"modules":{"US":{"stat":"ok"},"DF":{"stat":"ok"}
}}
}
```

Wenn ich in irgendeiner Form Kontakt zu Positec herstellen kann damit dieses Issue gefixt wird kann ich das gerne tun. 

In der aktuellen Konstellation werden die Landroids mit FW 3.11 beim Setzen der mowTimeExtended  deaktiviert und können derzeit nur am Display (M700...) oder per PowerOff (M500...) zur Arbeit überredet werden.

**Comment by MeisterTR** [comment]
ich sachätze ich muss wie positec schrib distm auch noch aus dem setup entfernen, dann sollte es glaub ich gehen, mach ich die Tage.

**Comment by heymkeyu** [comment]
Super - Danke! 

Zur Sicherheit nochmals ein Update der JSON da ich heute auf 3.13b aktualisiert habe. Ich habe nicht auf Diffs gecheckt:

`{
  "cfg":{"id":0,
    "lg":"it",
    "tm":"21:43:18",
    "dt":"08\/06\/2020",
    "sc":{"m":1,"distm":0,"ots":{"bc":0,"wtm":30},"p":0,"d":[
      ["00:00",0,0],
      ["13:30",90,1],
      ["10:30",90,1],
      ["10:20",90,1],
      ["10:30",90,1],
      ["10:42",60,1],
      ["10:30",60,1]]},
    "cmd":0,
    "mz":[11,43,0,0],
    "mzv":[0,1,0,1,0,1,0,1,0,1],
    "rd":30,
    "sn":"XXXX","modules":{"US":{"enabled":1}
}},
  "dat":{
    "mac":"XXXX",
    "fw":3.13,
    "bt":{"t":15.4,"v":17.92,"p":45,"nr":98,"c":0,"m":1},
    "dmp":[2.6,0.4,12.6],
    "st":{"b":12723,"d":185406,"wt":13673,"bl":41},
    "ls":7,
    "le":0,
    "lz":5,
    "rsi":-65,
    "lk":1,"act":1,"tr":0,"conn":"wifi","rain":{"s":0,"cnt":0},"modules":{"US":{"stat":"ok"},"DF":{"stat":"ok"}
}}
}`

**Comment by heymkeyu** [comment]
Gibt's irgendwas wo ich unterstützen kann?

**Comment by MeisterTR** [comment]
bitte nochmal Testen, sollte jetzt gehen, falls nicht bitte wieder öffnen
