### ISSUE TITLE
Edcut vs. Edgecut

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#539]
In der Logdatei finden sich Debug-Einträge der Art "Edcut send cmd: 2/3". Siehe z.B https://github.com/iobroker-community-adapters/ioBroker.worx/issues/538#issuecomment-1164044267.

Lieber Adapter, schreibe bitte "Edgecut send cmd: 2/3". Soviel Zeit muss sein 😊

main.js:
568: `that.log.debug('Edcut send cmd:2');`
572: `that.log.debug('Edcut send cmd:3');`

**Comment by arteck** [comment]
fix

**Comment by hsteinme** [comment]
Danke schön!
