### ISSUE TITLE
Sporadischer Fehler

### ISSUE THREAD

**Issue by Trunks1982** [iobroker-community-adapters/ioBroker.worx#54]
Hi mir ist aufgefallen das ich immer mal diesen Fehler im Log angezeigt bekomme.

worx.0 | 2020-05-24 10:03:15.478 | error | (6239) Onlinecheck: couldnt get data StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>
-- | -- | -- | --

Was hat dies zubeudeuten?

**Comment by MeisterTR** [comment]
nimm mal die version von git und teste

**Comment by Trunks1982** [comment]
Hi den benutze ich schon.

**Comment by MeisterTR** [comment]
fixed
