### ISSUE TITLE
1.6.6. lässt sich nicht installieren

### ISSUE THREAD

**Issue by fu-zhou** [iobroker-community-adapters/ioBroker.worx#540]
Die neue Version 1.6.6 wird im iobroker angezeigt, aber nicht installiert. Das Installations-Fenster geht auf, bleibt aber leer, d.h. es gibt keinen Installationsfortschritt.

**Comment by fu-zhou** [comment]
es lässt sich bei mir gar kein Adapter updaten, hat wohl nix mit dem Worx zu tun...

**Comment by Feuer-sturm** [comment]
@fu-zhou nutzt du Admin 6?
Wenn ja ist es ein bekanntes Problem in der 6.1.5 welches bereits mit der neuen admin version gefixt ist https://github.com/ioBroker/ioBroker.admin/issues/1557

**Comment by fu-zhou** [comment]
Danke, habe über die Kommandozeile den Admin auf 6.1.6 gehoben aber auch die anderen Adapter. Mal abwarten, wenn ein weiteres Update kommt, ob das wieder über den Admin geht...
