### ISSUE TITLE
Wetter-Daten werden nicht mehr ausgelesen

### ISSUE THREAD

**Issue by mbhomie007** [iobroker-community-adapters/ioBroker.worx#541]
Seit Version 1.6.6  werden die Wetter-Daten nicht mehr ausgelesen.

![image](https://user-images.githubusercontent.com/64688879/175931364-a0e3efa4-4c72-48f9-a316-cab7e41ca65b.png)

![image](https://user-images.githubusercontent.com/64688879/175931498-369d153a-a902-495a-a199-5952c9904f56.png)

Im LOG werden keine Fehlermeldungen angezeigt.

#496

**Comment by Tagiwara** [comment]
Das kann ich bestätigen. Wetterdaten bleiben leer

**Comment by tmycgn** [comment]
Same here!

**Comment by Yunkie** [comment]
Kann ich ebenfalls bestätigen. Ich dachte, ich hätte irgendwo einen Konfigurationsfehler gemacht.

**Comment by TA2k** [comment]
Wetterdaten werden anscheinend nicht mehr von worx gesendet
