### ISSUE TITLE
log is filling with error

### ISSUE THREAD

**Issue by m-rohlfs** [iobroker-community-adapters/ioBroker.worx#546]
In Log this appears

<html><body>

worx.0 | 2022-07-17 15:19:08.797 | warn | State "worx.0.20xxxxxxxxx.mower.AutoLockTimer" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
this also came for torque an some other values. 

Reinstall does not work. 

Node.js: v16.16.0
NPM: 8.11.0
admin 5.3.8

**Comment by TA2k** [comment]
please retest with GitHub version
