### ISSUE TITLE
Invalid Obejct type weather.lastUpdate (24740)

### ISSUE THREAD

**Issue by hombach** [iobroker-community-adapters/ioBroker.worx#56]
(24740) This object will not be created in future versions. Please report this to the developer.
(24740) Object worx.0.20203019930100184901.weather.lastUpdate is invalid: obj.common.type has an invalid value (date) but has to be one of number, string, boolean, array, object, mixed, file, json

**Comment by Feuer-sturm** [comment]
Der Fehler tritt auf mit Worx Adapter Version 1.0.2, node: v12.18.0, js-controller: 3.1.6

**Comment by hombach** [comment]
Das hatte ich vergessen.... tritt hier auf mit Worx Adapter Version 1.0.2, node: v12.17.0, js-controller: 3.1.4
