### ISSUE TITLE
Support für FW 3.14+ mit DoubleScheduler

### ISSUE THREAD

**Issue by heymkeyu** [iobroker-community-adapters/ioBroker.worx#57]
Die Firmware 3.14+ beinhaltet nun den bereits mit 3.09b vorbereiteten DoubleScheduler (zwei Mähzeiten pro Tag) und weitere Feautures (Party Mode - deaktiviert Mäher, hatten wir schon ein paar Issues weiter unten ;-) )

Wäre schön, wenn der Adapter die Features der neuen FW untersützen würde.

Wie kann ich unterstützen?

**Comment by heymkeyu** [comment]
Siehe auch https://github.com/iobroker-community-adapters/ioBroker.worx/issues/58

**Comment by hsteinme** [comment]
siehe auch https://www.roboter-forum.com/index.php?thread/46592-firmware-v3-16/&postID=642954#post642954

**Comment by MeisterTR** [comment]
bitte mal von git Testen ob die 2ten Mähzeiten angelegt und gefüllt werden

**Comment by MeisterTR** [comment]
jetzt sollte auch das vertsellen gehen

**Comment by heymkeyu** [comment]
Da ich gerade selber nicht testen kann, habe ich hier 
https://www.roboter-forum.com/index.php?thread/46592-firmware-v3-16/&postID=646869#post646869
um Untersützung gebeten. 

Danke für Dein Engagement, @MeisterTR !

Gruß,
Oli

**Comment by hsteinme** [comment]
> bitte mal von git Testen ob die 2ten Mähzeiten angelegt und gefüllt werden

(1) Die 2. Mähzeiten werden als Datenpunkte angelegt und sind zunächst leer.

(2) Werden per Worx App 2. Mähzeiten angelegt, so empfängt der Adapter diese korrekt (nachlesbar im Debug-Log bei 
`GET MQTT DATA from API: {..."d":[["00:00",0,0],["16:30",15,0],["00:00",0,0],...,"dd":[["00:00",0,0],["17:30",15,1],["00:00",0,0]...`. Er trägt sie aber nicht in den neuen Datenpunkten ein. Diese bleiben weiterhin leer.

**Comment by MeisterTR** [comment]
sollte nun gehen

**Comment by hsteinme** [comment]
Eine gute und eine "andere" Nachricht:
- Die Datenpunkte der 2. Mähzeiten wurden nach der Neuinstallation angelegt und sauber initialisiert (00:00, 0, false).
- Werden per Worx App 2. Mähzeiten angelegt, so empfängt der Adapter diese korrekt, zeigt sie aber weiterhin nicht an. 

`2020-08-26 22:31:45.614  - [34mdebug[39m: worx.0 (32515) Worxcloud MQTT get Message for mower hstLandroid (xxxxxxxxxxxxxxxxxxxx)`
`2020-08-26 22:31:45.615  - [34mdebug[39m: worx.0 (32515) GET MQTT DATA from API: {"cfg":{"id":23029,"lg":"it","tm":"22:31:43","dt":"26/08/2020","sc":{"m":1,"distm":0,"ots":{"bc":0,"wtm":90},"p":0,"d":[["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["14:30",60,0],["00:00",0,0]],"dd":[["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["17:00",210,1],["00:00",0,0]]},"cmd":0,"mz":[5,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":1,"sn":"xxxxxxxxxxxxxxxxxxxx","modules":{}},"dat":{"mac":"XXXXXXXXXXXXX","fw":3.16,"fwb":12,"bt":{"t":18.4,"v":20.06,"p":100,"nr":461,"c":0,"m":0},"dmp":[1.8,-2.6,163.4],"st":{"b":45006,"d":803979,"wt":47170,"bl":80},"ls":1,"le":0,"lz":1,"rsi":-83,"lk":0,"act":1,"tr":0,"conn":"wifi","rain":{"s":0,"cnt":0},"modules":{"DF":{"stat":"ok"}}}}`
`2020-08-26 22:31:45.615  - [34mdebug[39m: worx.0 (32515) onbje: borderCut`
`2020-08-26 22:31:45.615  - [34mdebug[39m: worx.0 (32515) onbje: startTime`
`2020-08-26 22:31:45.616  - [34mdebug[39m: worx.0 (32515) onbje: workTime`
`2020-08-26 22:31:45.618  - [34mdebug[39m: worx.0 (32515) Test Status: 1`
`2020-08-26 22:31:49.215  - [34mdebug[39m: worx.0 (32515) Mower hstLandroid (xxxxxxxxxxxxxxxxxxxx) online status = true`

- Wird ein Element einer 2. Mähzeit geändert, so wird nach dem Auslösen der vorherige Wert wieder dargestellt.

`2020-08-26 22:52:01.360  - [34mdebug[39m: worx.0 (32515) state change: id_____ worx.0.xxxxxxxxxxxxxxxxxxxxx.calendar.friday2.startTime Mower ...`
`2020-08-26 22:52:01.361  - [34mdebug[39m: worx.0 (32515) h: 11 m: 11`
`2020-08-26 22:52:01.361  - [34mdebug[39m: worx.0 (32515) Mow time change at dd to: [["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["11:11",0,0],["00:00",0,0]]`
`2020-08-26 22:52:01.362  - [34mdebug[39m: worx.0 (32515) Worxcloud MQTT sendMessage to xxxxxxxxxxxxxxxxxxxxx Message: {"sc":{"dd":[["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["11:11",0,0],["00:00",0,0]]}}`
`2020-08-26 22:52:01.362  - [34mdebug[39m: worx.0 (32515) test cfg: 5 valID: 0 val: 11:11 sval: 11:11`
`2020-08-26 22:52:02.912  - [34mdebug[39m: worx.0 (32515) Worxcloud MQTT get Message for mower hstLandroid (xxxxxxxxxxxxxxxxxxxxx)`
`2020-08-26 22:52:02.913  - [34mdebug[39m: worx.0 (32515) GET MQTT DATA from API: {"cfg":{"id":1,"lg":"it","tm":"22:52:00","dt":"26/08/2020","sc":{"m":1,"distm":0,"ots":{"bc":0,"wtm":90},"p":0,"d":[["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["14:30",60,0],["00:00",0,0]],"dd":[["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]]},"cmd":0,"mz":[5,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":1,"sn":"xxxxxxxxxxxxxxxxxxxxx","modules":{}},"dat":{"mac":"XXXXXXXXXXXXX","fw":3.16,"fwb":12,"bt":{"t":18,"v":20.02,"p":100,"nr":461,"c":0,"m":0},"dmp":[1.8,-2.6,163.4],"st":{"b":45006,"d":803979,"wt":47170,"bl":80},"ls":1,"le":0,"lz":1,"rsi":-84,"lk":0,"act":1,"tr":0,"conn":"wifi","rain":{"s":0,"cnt":0},"modules":{"DF":{"stat":"ok"}}}}`
`2020-08-26 22:52:02.914  - [34mdebug[39m: worx.0 (32515) onbje: borderCut`
`2020-08-26 22:52:02.914  - [34mdebug[39m: worx.0 (32515) onbje: startTime`
`2020-08-26 22:52:02.914  - [34mdebug[39m: worx.0 (32515) onbje: workTime`
`2020-08-26 22:52:02.915  - [34mdebug[39m: worx.0 (32515) Test Status: 1`

**Comment by MeisterTR** [comment]
bitte nochmal testen

**Comment by MeisterTR** [comment]
sollte mit der 1.2.3 funktionieren

**Comment by hsteinme** [comment]
> Werden per Worx App 2. Mähzeiten angelegt, so empfängt der Adapter diese korrekt, zeigt sie aber weiterhin nicht an.

Dies ist nun behoben. Empfangene 2. Mähzeiten werden korrekt in den Datenpunkten abgestellt.

> Wird ein Element einer 2. Mähzeit geändert, so wird nach dem Auslösen der vorherige Wert wieder dargestellt.

Dieses Fehlverhalten ist weiterhin vorhanden. Siehe Logdatei:
[20200902_friday2.startTime.pdf](https://github.com/iobroker-community-adapters/ioBroker.worx/files/5162168/20200902_friday2.startTime.pdf)

**Comment by hsteinme** [comment]
Partymodus klappt gut (in der vom Adapter zur Verfügung gestellten eingeschränkten Funktionalität). Herzlichen Dank!

**Comment by hsteinme** [comment]
> > Wird ein Element einer 2. Mähzeit geändert, so wird nach dem Auslösen der vorherige Wert wieder dargestellt.

> Dieses Fehlverhalten ist weiterhin vorhanden. Siehe Logdatei:
20200902_friday2.startTime.pdf

@MeisterTR : Gibt es hier schon Neuigkeiten? Kann ich Dich durch die Bereitstellung weiterer Diagnoseinformationen unterstützen?

**Comment by hsteinme** [comment]
> Wird ein Element einer 2. Mähzeit geändert, so wird nach dem Auslösen der vorherige Wert wieder dargestellt.

Problem tritt unter 1.2.9 nicht mehr auf.
