### ISSUE TITLE
Keine Verbindung möglich

### ISSUE THREAD

**Issue by Theboss996** [iobroker-community-adapters/ioBroker.worx#582]
Hallo,
Ich erhalte forgenden fehler wenn ich über die Katze installiere...
![Screenshot 2022-10-03 181907](https://user-images.githubusercontent.com/6815999/193632590-bc78404f-7958-4adf-a9d8-d985e55b0794.png)

**Comment by TA2k** [comment]
Bitte nochmal installieren und testen

**Comment by Theboss996** [comment]
![Screenshot 2022-10-04 04 58 44](https://user-images.githubusercontent.com/6815999/193725128-500e8557-26c4-4ce5-9adf-717c1207f8c2.png)


sieht schon besser aus aber immer noch nicht verbunden. 
danke für die schnelle hilfe

**Comment by Theboss996** [comment]
Besten Dank. es funktioniert wieder :D
> Bitte nochmal installieren und testen
