### ISSUE TITLE
unterschiedliche Formatierung der Firmware-Versionen bei den Objekten

### ISSUE THREAD

**Issue by darkman242** [iobroker-community-adapters/ioBroker.worx#587]
Nach dem Update auf die Adapter-Version 2.01 ist mitr aufgefallen, dass die Firmware-Objekte unterschiedliche Formate haben. Weiss nicht ob das vorher ebenso war.

firmware: 3.28 (Punkt)
firmware_available: 3,28 (Komma)

![image](https://user-images.githubusercontent.com/46793576/194743826-32c55366-ca4b-499a-96b0-642e2275cec9.png)

**Comment by Lucky-ESA** [comment]
Danke für die Info. Werde das nächste Woche korrigieren.
Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Meinst du unter available_all? Das ist OK so.

**Comment by darkman242** [comment]
Ich meine unter rawMqtt (Firmware).
