### ISSUE TITLE
Adapter installation: Process exited with code 25

### ISSUE THREAD

**Issue by texiuozelotl** [iobroker-community-adapters/ioBroker.worx#589]
**Describe the bug**  
- Adaper update fails
- New installation also fails

**To Reproduce**  
1. Uninstall Adapter
2. Reinstall Adapter

**Screenshots & Logfiles**  
$ iobroker add worx --host iobroker-0
Installing iobroker.worx@1.7.0... (System call)
host.iobroker-0 Cannot install iobroker.worx@1.7.0: 1
ERROR: Process exited with code 25

**Versions:**  
 - Adapter version:1.7.0: 1
 - JS-Controller version: 4.0.23
 - Node version: v14.16.0
 - Operating system: ubuntu 20.04

**Comment by TA2k** [comment]
Enable on the install screen debug log to see more.
I think minim node 14.18
