### ISSUE TITLE
Zusammenfassung aller Datenpunkte unterhalb worx.9.999999.calendar.xxxx zu einem gemeinsamen Datenpunkt

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#59]
Updates der Datenpunkte unterhalb worx.9.999999.calendar.xxxx verlangen heute einen zeitlichen Abstand von mindestns 5 Sekunden, da ansonsten diese Updates verloren gehen. Siehe hierzu [https://forum.iobroker.net/topic/31506/worx-adapter-kalender-%C3%A4nderungen-per-javascript-unwirksam/](https://forum.iobroker.net/topic/31506/worx-adapter-kalender-%C3%A4nderungen-per-javascript-unwirksam/) - 26. März 2020. Zur Umgehung dieser wahrlich unhandlichen Programmiertechnik bitte je Wochentag neben den (aus Gründen der Aufwärtskompatibilität weiterhin vorhandenen) Datenpunkten startTime, workTime und borderCut einen zusätzlichen Datenpunkt schedule einführen, der als Liste oder als Array die Werte für startTime, workTime und borderCut enthält.

Siehe auch [https://forum.iobroker.net/topic/31506/worx-adapter-kalender-%C3%A4nderungen-per-javascript-unwirksam/](https://forum.iobroker.net/topic/31506/worx-adapter-kalender-%C3%A4nderungen-per-javascript-unwirksam/) - 19. April 2020.

**Comment by MeisterTR** [comment]
sollte mit der 1.2.3 funktionieren

**Comment by hsteinme** [comment]
Ich kann die angekündigten Elemente unterhalb von worx.9.999999.calendar.xxxx nicht erkennen, auch nicht nach dem Stoppen der Instanz, dem Löschen von worx.9.999999.calendar und dem Restart der Instanz.

**Comment by MeisterTR** [comment]
Du musst es in der Config aktivieren

**Comment by hsteinme** [comment]
Upps, sorry! Danke für den Hinweis.

(1) Nach Config-Anpassung sind die JSON-Strukturen der Mähzeiten zu sehen. Danke schön!

(2) JSON-Änderungen einer 1. Mähzeit laufen erfolgreich ab, liefern aber einen FAIL-Eintrag in der Lögdatei. Ist dies was Ernsthaftes? Oder nur was Irritierendes?

[20200902_FAIL.pdf](https://github.com/iobroker-community-adapters/ioBroker.worx/files/5163914/20200902_FAIL.pdf)

(3) JSON-Änderungen einer 2. Mähzeit werden nicht übernommen. Nach einer kurzen "Denkpause" wird der vorherige JSON-Inhalt wieder angezeigt. Siehe auch https://github.com/iobroker-community-adapters/ioBroker.worx/issues/57#issuecomment-685690300

(4) Der Config-Führungstext "add raw data" ist reichlich vielsagend. Bitte ändern in "Add calendar raw data".

**Comment by hsteinme** [comment]
> JSON-Änderungen einer 2. Mähzeit werden nicht übernommen. Nach einer kurzen "Denkpause" wird der vorherige JSON-Inhalt wieder angezeigt.

Problem tritt unter 1.2.9 nicht mehr auf.

**Comment by hsteinme** [comment]
> JSON-Änderungen einer 1. Mähzeit laufen erfolgreich ab, liefern aber einen FAIL-Eintrag in der Lögdatei. Ist dies was Ernsthaftes? Oder nur was Irritierendes?

Version 1.2.9: Problem tritt bei der 1. Mähzeit nicht mehr auf, jedoch bei einer Änderung der 2. Mähzeit.
