### ISSUE TITLE
MQTT Timeout

### ISSUE THREAD

**Issue by Crazyachmed** [iobroker-community-adapters/ioBroker.worx#590]
Seit dem Update auf 2.0.x habe ich im Debug-Log alle paar Minuten einen MQTT-Timeout. Vermutlich ist kein Keep-Alive für die Verbindung aktiviert. Ich habe mir das kurz mit tcpdump angeschaut und man sieht, dass die Verbindung länger funktioniert, wenn zufällig Daten mit der Cloud ausgetauscht werden.

![Screenshot from 2022-10-14 17-59-15](https://user-images.githubusercontent.com/8402464/195890405-9d2dd530-1cf4-4046-96b0-3cb1a77fbd44.png)

**Comment by Crazyachmed** [comment]
Das hat leider nicht gebracht. Laut Doku (https://github.com/aws/aws-iot-device-sdk-js#api) ist auch sowieso ein Keep-Alive von 300 Sekunden gesetzt. Ich hab gerade wenig Zeit, ich werde versuchen ein Debug-Log zu ziehen und parallel einen Trace, damit wir sehen, was überhaupt passiert.

Außer du hast noch eine andere Idee?

**Comment by TA2k** [comment]
Ich gehe davon aus dass worx die mqtt Verbindung hart trennt wenn keine Daten vom Roboter kommen. im debug sollten also keine nachrichten vom Mäher kommen.
Dann könnte man nur den log Eintrag entfernen

**Comment by TA2k** [comment]
Logs sind deaktiviert

**Comment by Crazyachmed** [comment]
Ich habe mir das Log und den Capture gerade angeschaut und finde auch nichts Besonderes. Die Verbindung wird auf jeden Fall von der Cloud-Seite aus geschlossen mit einem Encrypted Alert, sobald sich der Client meldet. Also schonmal keine verloren gegangene TCP-Session irgendeiner Firewall auf dem Weg.

Ist zwar blöd, aber das Abschalten der Meldung ist vermutlich das sinnvollste gerade.
