### ISSUE TITLE
Documentation: Minimum node version

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#597]
See https://github.com/iobroker-community-adapters/ioBroker.worx/issues/589#issuecomment-1277919114: If 14.18 is really the minimum node version please document it very well in the README.md file.

**Comment by TA2k** [comment]
I added in the readme but you will see this in the installation log as well

**Comment by hsteinme** [comment]
Thank you. BTW: It's better to see the correct node version in the README before the installation than to see it in the log after an unsuccesfull installation.
