### ISSUE TITLE
no existing object

### ISSUE THREAD

**Issue by Janideluxe** [iobroker-community-adapters/ioBroker.worx#602]
Habe einen neuen Mäher mir zugelegt und bekomme diese Fehlermeldungen in den Log geschrieben. 

![grafik](https://user-images.githubusercontent.com/51678652/200131298-c396d0fa-acc1-4974-b09a-00a7e2b04c82.png)

**Comment by TA2k** [comment]
@Lucky-ESA

**Comment by Lucky-ESA** [comment]
Irgendwie fehlen hier Infos.
Welche Version hast du installiert oder hast du vom GIT installiert?
Ist jetzt der Datenpunkt worx.0.xxxx.mower.torque angelegt oder kommt diese Meldung alle paar Minuten?
Ich benötige wahrscheinlich dein Log...Bitte mal den Adapter auf Debug stellen und mir das Logfile per Mail zusenden.
github@luckyskills.de

**Comment by Janideluxe** [comment]
Version vom Adapter ist 2.0.3 stable. 
Meldung erscheint jede Minute Log ist also komplett voll damit.
Logfile mit Debug Ausgabe kommt per Mail.

**Comment by Lucky-ESA** [comment]
Du hast 2 Mäher daher wahrscheinlich die Meldungen. Bitte die aktuelle GIT Version installieren.

**Comment by Janideluxe** [comment]
Objekte sind nun angelegt und Meldungen weg. Danke für den schnellen support.
