### ISSUE TITLE
Support for FHEM modul "axelmohnen/fhem-landroid-s" needed.

### ISSUE THREAD

**Issue by eckonator** [iobroker-community-adapters/ioBroker.worx#605]
Hello everyone, I hope you can help me.

I use [FHEM](https://fhem.de/) and the [Landroid modul](https://github.com/axelmohnen/fhem-landroid-s), which uses the [api.js](https://github.com/iobroker-community-adapters/ioBroker.worx/blob/v1.6.6/lib/api.js) of this adapter as base. Since September 28th the plugin for FHEM does not work anymore. Now I tried to adapt the FHEM plugin to the [api.js](https://github.com/iobroker-community-adapters/ioBroker.worx/blob/v1.7.0/lib/api.js) from adapter version 1.7.0. Unfortunately it exceeds my skills regarding node.js. Unfortunately, the maintainer of the module does not respond.

Would someone of you be so kind and take a look at [this file](https://github.com/axelmohnen/fhem-landroid-s/blob/master/LandroidSrv.js), what needs to be changed here, that it works again with the API version of 1.7.0?

Thanks for your help!

**Comment by TA2k** [comment]
This is not so easy fixable because the Mqtt connection was also changed.
