### ISSUE TITLE
Pull Update

### ISSUE THREAD

**Issue by mol7os** [iobroker-community-adapters/ioBroker.worx#61]
Hi,

vielen Dank für den Adapter.
Meine Adapter aktualisieren sich von Zeit zu Zeit nicht mehr auch ein regelmäßiger Neustart ändert das nicht.
Eine Aktualisierung findet dann nur noch statt wenn die App auf dem Smartphone gestartet wird.
Folgende Konstelation:

- Zeitplan ist erstellt in der App
- Zeitplan löst den Mähvorgang aus
- IoBroker übernimmt die Dauer des Mähvorgangs (da mehrere Zonen [3])

Es sind keine echten Fehlermeldungen teilbar, der Log ist nach erfolgreichem Neustart des Adapters sauber.
Allerdings muss die app geöffnet werden, damit eine Aktualisierung erfolgt. Danach funktioniert das wieder eine Weile.

Gibt es etwas was ich tun kann? Kann ich den Adapter zwingen einen "PULL" der Daten vorzunehmen?

**Comment by hsteinme** [comment]
Normalerweise sendet der Mäher im 10-Minuten-Takt Aktualisierungen (sowie bei zwischenzeitlichen Statusänderungen, die **ihm** wichtig erscheinen). Wenn Du nach dem Neustart der Instanz 10 Minuten wartest und zwischendurch nichts mit der App oder dem Adapter machst, werden da Aktualisierungen geschickt? Dazu bitte im Objects-Fenster die Spalte Timestamp beobachten.

Diesen Test bitte durchführen, wenn der Mäher durchgehend WLAN-Empfang hat.

**Comment by mol7os** [comment]
Hi,

WLAN Empfang ist durchweg gegeben, folgendes aktuelles Beispiel anhand "Akku Ladezustand":

Wir haben aktuell 13:40 und folgendes wurde als "history" aufgezeichnet: 
(noch jetzt steht er bei 52%, wir wissen das es 99% sein sollten)

52 | false | worx.0 | 2020-07-03 **11:25:24.402 |**  
42 | false | worx.0 | 2020-07-03 11:15:24.366 |  
35 | false | worx.0 | 2020-07-03 11:05:24.334 |  
9 | false | worx.0 | 2020-07-03 10:41:09.522 |  
12 | false | worx.0 | 2020-07-03 10:31:10.051 |  
25 | false | worx.0 | 2020-07-03 10:21:09.457 |  
33 | false | worx.0 | 2020-07-03 10:11:09.460 |  
39 | false | worx.0 | 2020-07-03 10:01:09.407 |  
47 | false | worx.0 | 2020-07-03 09:51:09.414 |  
53 | false | worx.0 | 2020-07-03 09:41:09.366 |  
61 | false | worx.0 | 2020-07-03 09:31:09.362 |  
88 | false | worx.0 | 2020-07-03 09:21:09.313 |  
99 | false | worx.0 | 2020-07-03 **04:00:11.575 |**  

Der Adapter Neustart findet um 4:00 statt, der Mähplan startet (auch heute) um 08:00 bis 12:00 (geplant auf APP).

Status:

1 | false | worx.0 | 2020-07-03 11:05:24.331 |  
1 | false | worx.0 | 2020-07-03 10:45:24.298 |  
7 | false | worx.0 | 2020-07-03 10:31:10.049 |  
7 | false | worx.0 | 2020-07-03 09:21:09.310 |  
1 | true | worx.0 | 2020-07-03 04:00:11.571 |

Es gab bis 9:21 keine Aktualisierung. Der Mäher ist jedoch um 08:00 gestartet mit Kantenschnitt und hat bis dahin gemäht.
9:21 ist er die 2te Runde in eine andere Zone gefahren, sowie die 3te um 10:31.

Die Logs haben quasi Lochfrass.

**Comment by mol7os** [comment]
Ach bevor ich es erwähne getriggert wurde die Kommunikation ab 09:21 durch eine "Out of Wire", welches an die App gesendet wurde.

**Comment by hsteinme** [comment]
(1) Stell mal im Instanzen-Tab den Loglevel auf Debug. Wenn wieder Statusmeldungen ausbleiben, prüf mal in der Logdatei, ob dort irgendein Fehlerhinweis zu sehen ist. Die Meldungen des Mähers sind wie folgt protokolliert: _GET MQTT DATA from API: {"cfg":{"id":1,"lg":"it","tm":..._

(2) Es wäre gut zu erfahren, ob der Mäher oder der MQTT Sender nichts schicken oder ob der Adapter nichts bekommt/protokolliert. Kennst Du die DeskApp für Windows? Siehe https://www.roboter-forum.com/index.php?thread/22795-entwicklungsprojekt-worx-landroid-kress-mission-desktop-app/. Installiere diese mal, kreuze im Plugin-Tab PluginCsvLogWriter an und drücke den DoIt Button. Dann wird im Installationsverzeichnis eine csv-Datei angelegt, in der der Datenverkehr protokolliert wird. Dann, wenn ioBroker wieder "Lochfrass" hat, nachsehen, wie es zum gleichen Zeitpunkt in der csv-Datei aussieht.

**Comment by mol7os** [comment]
ok, versuche es, danke.

**Comment by mol7os** [comment]
Heute hatte ich übrigends folgendes im Log, der Vollständigkeit halber:


worx.0 | 2020-07-03 10:11:20.811 | error | (1159) Onlinecheck: couldnt get data RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
-- | -- | -- | --
worx.0 | 2020-07-03 10:09:20.809 | error | (1159) Onlinecheck: couldnt get data RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
worx.0 | 2020-07-03 10:08:20.812 | error | (1159) Onlinecheck: couldnt get data RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
worx.0 | 2020-07-03 10:06:35.798 | info | (5466) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
worx.0 | 2020-07-03 10:06:35.792 | error | (5466) worx.0 invalid process id scenario 1159 vs. own ID 5466. Stopping
worx.0 | 2020-07-03 09:31:20.793 | error | (1159) Onlinecheck: couldnt get data RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com

Es scheint hier heute zu mindest zu Abfragefehler gekommen zu sein, jedoch nicht im 10 Minuten Takt.

Ich schaue das ich die Tage mehr Infos bekomme, wenn ich das wieder beobachten kann. Desktop App, Debuglevel

**Comment by MeisterTR** [comment]
Dee Fehler liegt an der Verbindung zum mqtt broker der cloud. Sverauxhe mal den Mäher aus deinem Account zu löschen und neu an zu lernen, dann sollte es besser sein. Vorausgesetzt wlan ist wirklich nciht das Problem.

**Comment by mol7os** [comment]
Ok habe nun folgendes im Log, wenn wieder die Aktualisierung fehlschlägt: (hoffentlich hilft das)


worx.0 | 2020-07-06 10:53:28.686 | debug | (16122) system.adapter.admin.0: logging true
-- | -- | -- | --
worx.0 | 2020-07-06 09:13:20.794 | debug | (16122) system.adapter.admin.0: logging false
worx.0 | 2020-07-06 09:13:10.794 | debug | (16122) system.adapter.admin.0: logging true
worx.0 | 2020-07-06 09:12:56.537 | error | (16122) ERROR: StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
worx.0 | 2020-07-06 09:12:56.535 | error | (16122) Could not Connect to Worx Server: StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>
worx.0 | 2020-07-06 09:12:56.262 | debug | (16122) Connect to worx....
worx.0 | 2020-07-06 09:12:56.193 | info | (16122) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.worx, node: v12.18.1, js-controller: 3.1.4
worx.0 | 2020-07-06 09:12:55.406 | debug | (16122) statesDB connected
worx.0 | 2020-07-06 09:12:55.403 | debug | (16122) States connected to redis: 127.0.0.1:9000
worx.0 | 2020-07-06 09:12:55.368 | debug | (16122) States create System PubSub Client
worx.0 | 2020-07-06 09:12:55.362 | debug | (16122) States create User PubSub Client
worx.0 | 2020-07-06 09:12:55.292 | debug | (16122) Redis States: Use Redis connection: 127.0.0.1:9000
worx.0 | 2020-07-06 09:12:55.287 | debug | (16122) objectDB connected
worx.0 | 2020-07-06 09:12:55.271 | debug | (16122) Objects connected to redis: 127.0.0.1:9001
worx.0 | 2020-07-06 09:12:55.240 | debug | (16122) Objects client initialize lua scripts
worx.0 | 2020-07-06 09:12:55.237 | debug | (16122) Objects create User PubSub Client
worx.0 | 2020-07-06 09:12:55.233 | debug | (16122) Objects create System PubSub Client
worx.0 | 2020-07-06 09:12:55.211 | debug | (16122) Objects client ready ... initialize now
worx.0 | 2020-07-06 09:12:55.108 | debug | (16122) Redis Objects: Use Redis connection: 127.0.0.1:9001
worx.0 | 2020-07-06 09:12:21.246 | info | (1145) Terminated (NO_ERROR): Without reason
worx.0 | 2020-07-06 09:12:21.244 | info | (1145) terminating
worx.0 | 2020-07-06 09:12:21.237 | info | (1145) cleaned everything up...
worx.0 | 2020-07-06 09:12:21.235 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
worx.0 | 2020-07-06 09:12:21.235 | error | at endReadableNT (_stream_readable.js:1221:12)
worx.0 | 2020-07-06 09:12:21.235 | error | at IncomingMessage.emit (events.js:327:22)
worx.0 | 2020-07-06 09:12:21.235 | error | at Object.onceWrapper (events.js:421:28)
worx.0 | 2020-07-06 09:12:21.235 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
worx.0 | 2020-07-06 09:12:21.235 | error | at Request.emit (events.js:315:20)
worx.0 | 2020-07-06 09:12:21.235 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
worx.0 | 2020-07-06 09:12:21.235 | error | at Request.emit (events.js:315:20)
worx.0 | 2020-07-06 09:12:21.235 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
worx.0 | 2020-07-06 09:12:21.235 | error | at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
worx.0 | 2020-07-06 09:12:21.235 | error | at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:104:33)
worx.0 | 2020-07-06 09:12:21.235 | error | at new StatusCodeError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:32:15)
worx.0 | 2020-07-06 09:12:21.235 | error | (1145) StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
worx.0 | 2020-07-06 09:12:21.235 | error | (1145) unhandled promise rejection: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
worx.0 | 2020-07-06 09:11:21.968 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:10:21.965 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:09:21.982 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:08:21.978 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:07:21.970 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:06:26.896 | debug | (1145) Test Status: 7
worx.0 | 2020-07-06 09:06:26.894 | debug | (1145) GET MQTT DATA from API: {"cfg":{"id":0,"lg":"it","tm":"09:06:26","dt":"06/07/2020","sc":{"m":1,"p":60,"d":[["11:00",0,0],["08:00",240,1],["08:00",240,0],["08:00",240,1],["08:00",240,0],["08:00
worx.0 | 2020-07-06 09:06:26.893 | debug | (1145) Worxcloud MQTT get Message for mower M500 (20193019840101600235)
worx.0 | 2020-07-06 09:06:21.961 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:05:21.965 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:04:21.961 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:03:21.960 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:02:21.964 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:01:21.967 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 09:00:21.957 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 08:59:21.952 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 08:58:21.965 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 08:57:21.961 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 08:56:26.881 | debug | (1145) Test Status: 7
worx.0 | 2020-07-06 08:56:26.873 | debug | (1145) GET MQTT DATA from API: {"cfg":{"id":0,"lg":"it","tm":"08:56:26","dt":"06/07/2020","sc":{"m":1,"p":60,"d":[["11:00",0,0],["08:00",240,1],["08:00",240,0],["08:00",240,1],["08:00",240,0],["08:00
worx.0 | 2020-07-06 08:56:26.872 | debug | (1145) Worxcloud MQTT get Message for mower M500 (20193019840101600235)
worx.0 | 2020-07-06 08:56:21.962 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n<
worx.0 | 2020-07-06 08:55:22.079 | error | (1145) Onlinecheck: couldnt get data StatusCodeError: 429 - {"message":"Too Many Attempts."}
worx.0 | 2020-07-06 08:54:22.128 | debug | (1145) Mower M500 (20193019840101600235) online status = true
worx.0 | 2020-07-06 08:53:22.133 | debug | (1145) Mower M500 (20193019840101600235) online status = true
worx.0 | 2020-07-06 08:52:22.132 | debug | (1145) Mower M500 (20193019840101600235) online status = true
worx.0 | 2020-07-06 08:51:22.140 | debug | (1145) Mower M500 (20193019840101600235) online status = true
worx.0 | 2020-07-06 08:50:22.123 | debug | (1145) Mower M500 (20193019840101600235) online status = true
worx.0 | 2020-07-06 08:49:22.093 | debug | (1145) Mower M500 (20193019840101600235) online status = true
worx.0 | 2020-07-06 08:48:22.104 | debug | (1145) Mower M500 (20193019840101600235) online status = true
worx.0 | 2020-07-06 08:47:22.151 | debug | (1145) Mower M500 (20193019840101600235) online status = true
worx.0 | 2020-07-06 08:46:26.851 | debug | (1145) Test Status: 7

**Comment by mol7os** [comment]
Desweiteren heute, der Mäher wird Zeitweise als "nicht online" gelistet, ist jedoch definitv im WLAN und an der Ladestation.
Nach öffnen der App wird der Status auch wieder aktualisiert:


worx.0 | 2020-07-08 11:24:07.080 | debug | (1173) Test Status: 1
-- | -- | -- | --
worx.0 | 2020-07-08 11:24:07.077 | debug | (1173) GET MQTT DATA from API: {"cfg":{"id":61850,"lg":"it","tm":"11:24:05","dt":"08/07/2020","sc":{"m":1,"p":0,"d":[["11:00",0,0],["08:00",240,1],["08:00",240,0],["08:00",240,1],["08:00",240,0],["08:
worx.0 | 2020-07-08 11:24:07.075 | debug | (1173) Worxcloud MQTT get Message for mower M500 (20193019840101600235)
worx.0 | 2020-07-08 11:24:00.359 | debug | (1173) Test Status: 1
worx.0 | 2020-07-08 11:24:00.357 | debug | (1173) GET MQTT DATA from API: {"cfg":{"id":51472,"lg":"it","tm":"11:23:58","dt":"08/07/2020","sc":{"m":1,"p":0,"d":[["11:00",0,0],["08:00",240,1],["08:00",240,0],["08:00",240,1],["08:00",240,0],["08:
worx.0 | 2020-07-08 11:24:00.355 | debug | (1173) Worxcloud MQTT get Message for mower M500 (20193019840101600235)
worx.0 | 2020-07-08 11:23:53.090 | debug | (1173) Mower M500 (20193019840101600235) online status = false
worx.0 | 2020-07-08 11:23:33.961 | debug | (1173) system.adapter.admin.0: logging true
worx.0 | 2020-07-08 11:23:24.915 | debug | (1173) system.adapter.admin.0: logging false
worx.0 | 2020-07-08 11:23:00.212 | debug | (1173) system.adapter.admin.0: logging true
worx.0 | 2020-07-08 11:22:53.167 | debug | (1173) Mower M500 (20193019840101600235) online status = false
worx.0 | 2020-07-08 11:21:53.134 | debug | (1173) Mower M500 (20193019840101600235) online status = false
worx.0 | 2020-07-08 11:20:53.075 | debug | (1173) Mower M500 (20193019840101600235) online status = false
worx.0 | 2020-07-08 11:20:52.798 | debug | (1173) Weather_d Wed Jul 08 2020 10:21:00 GMT+0200 (Central European Summer Time)
worx.0 | 2020-07-08 11:20:52.797 | debug | (1173) Weather_ {"coord":{"lon":8.88583,"lat":49.873329},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"base":"stations","main":{"temp":18.32,"feels_like":16.32,
worx.0 | 2020-07-08 11:19:53.146 | debug | (1173) Mower M500 (20193019840101600235) online status = false
worx.0 | 2020-07-08 11:18:53.095 | debug | (1173) Mower M500 (20193019840101600235) online status = false
worx.0 | 2020-07-08 11:17:53.103 | debug | (1173) Mower M500 (20193019840101600235) online status = false

**Comment by hombach** [comment]
Bei mir haben sich die massig MQTT fehler verbessert durch das Update auf MQTT4.1.0.
Evtl. versuchst du mal den Betrieb mit meinem Branch aus anstehendem Pull-Request.
