### ISSUE TITLE
"borderCut" Datenpunkt wird auch bei deaktiviertem Schedule von false auf true gesetzt

### ISSUE THREAD

**Issue by robson80** [iobroker-community-adapters/ioBroker.worx#63]
Der Datenpunkt "borderCut" wird bei deaktiviertem Zeitplan für den jeweiligen Tag immer von false auf true gesetzt.

Setze ich den Datenpunkt per Skript auf false, so wird dieser nach wenigen Sekunden wieder auf true gesetzt.

Sinnvoller wäre meiner Meinung nach den Datenpunkt bei deaktiviertem Schedule auf false zu setzen.

Probleme hat mir dieser Umstand bei der Visualisierung bereitet. Hier wurde mir angezeigt, dass für bspw. Montag der Kantenschnitt aktiviert ist, obwohl für diesen Tag überhaupt keine Mähzeiten gepflegt sind.

**Comment by hsteinme** [comment]
Ich habe versucht, Deine beschriebene Situation nachzuspielen. Vergeblich!

Mit welchem Programm, welcher Programmversion und mit welcher Vorgehensweise hast Du denn den Zeitplan für einen Tag deaktiviert?

**Comment by robson80** [comment]
Das hätte ich natürlich beschreiben können ;)

Den Zeitplan steuere ich aktuell über die Android App (v1.1.23).
Iobroker Adim Version 4.0.10

**Comment by hsteinme** [comment]
Alle folgenden Tests wurden mit Firmware 3.15, Worx Adapter 1.0.2 und Admin 4.0.3 durchgeührt:

- Android App  1.1.23
~ Zeit ohne Kantenschnitt eingestellt
~ borderCut = false
~ Tag deaktiviert
~ borderCut = false
~ Zeit mit Kantenschnitt eingestellt
~ borderCut = true
~ Tag deaktiviert
~ borderCut = true

- Android App  2.0.0 Build 1017 (Beta-Version)
~ Zeit ohne Kantenschnitt eingestellt
~ borderCut = false
~ Tag deaktiviert
~ borderCut = false
~ Zeit mit Kantenschnitt eingestellt
~ borderCut = true
~ Tag deaktiviert
~ borderCut = false

Mein Fazit: Die deaktivierende App bestimmt den Zustand von borderCut nach dem Deaktivieren, nicht der Adapter. Der Adapter gibt nur aus, was er vom MQTT Server erhält.

Nebenbei: Meiner persönlichen Schätzung nach wird die App Version 2.0.0 spätestens in drei oder vier Wochen offiziell verfügbar sein.

**Comment by robson80** [comment]
Vielen Dank für deine Tests. Meine Befürchtung war ebenfalls, dass die App für den Status verfügbar ist und nicht der Adapter.
Ich schließe dann mal hier.
