### ISSUE TITLE
Config / code inconsistency: metermin vs. meterMin

### ISSUE THREAD

**Issue by holgerpieta** [iobroker-community-adapters/ioBroker.worx#634]
**Describe the bug**  
jsonConfig.json defines metermin (all lower case), which seems to also be the one changed by the GUI tick box.
The code (helper.js anbd io-package.json) however uses meterMin (upper case second M).
Therefore the GUI tick box has no effect.
One can manually fix that by exporting the config JSON, which does contain both metermin and meterMin. Then edit the JSON and reimport it, then restart the instance.

**To Reproduce**  
1. Generate an instance of the adapter.
2. Check that distance and time are in km and h.
3. Change tick box and restart instance.
4. Distance and time still in km and h.
5. Export config JSON, edit, reimport, restart instance.
6. Distance and time now in m and min.

**Expected behavior**  
Tick box works, no manual edit required.

**Versions:**  
 - Adapter version: 2.0.3
 - JS-Controller version: 4.0.23
 - Node version: 16.19.0
 - Operating system: Linux / Raspbian / Podman

**Comment by TA2k** [comment]
Fixed on GitHub
