### ISSUE TITLE
2. Zeitplan der 2019 Modelle mit FW 3.16+ werden gelöscht. 

### ISSUE THREAD

**Issue by heymkeyu** [iobroker-community-adapters/ioBroker.worx#64]
Ich verwende folgendes JS um den Landroid heimzuschicken, bevor meine Bewässerung startet. 

Das Script verwendet eine Systemvariable der Homematic, um zu triggern.
```
var MowingProzent;


on({id: "hm-rega.0.64310"/*TRIGGER_Sperre_Landroid*/, change: "ne"}, function (obj) {
  if ((obj.state ? obj.state.val : "") === true) {

 if ((getState("hm-rega.0.64310").val == true) && (getState("worx.0.20193019930200004504.mower.status").val != 0) && (getState("worx.0.20193019930200004504.mower.status").val != 1)) {
      setState("worx.0.20193019930200004504.mower.state"/*Start/Stop*/, false);
      console.log('Landroid sent home');
    }
      
    MowingProzent = -100;
    console.log('Mowing Extension -100%');
  } else {
    MowingProzent = 0;
    console.log('Mowing Extension 0%');
  }
  setState("worx.0.20193019930200004504.mower.mowTimeExtend", MowingProzent);
    
});
```

Laut Positec führt folgendes JSON zur Löschung des 2. Zeitplans:
```
{
  "sc": {
    "p": -100,
    "dd": [
      [
        "00:00",
        0,
        0
      ],
      [
        "00:00",
        0,
        0
      ],
      [
        "00:00",
        0,
        0
      ],
      [
        "00:00",
        0,
        0
      ],
      [
        "00:00",
        0,
        0
      ],
      [
        "00:00",
        0,
        0
      ],
      [
        "00:00",
        0,
        0
      ]
    ],
    "d": [
      [
        "00:00",
        0,
        0
      ],
      [
        "09:30",
        45,
        1
      ],
      [
        "09:30",
        45,
        0
      ],
      [
        "08:30",
        30,
        0
      ],
      [
        "09:30",
        45,
        0
      ],
      [
        "09:30",
        45,
        1
      ],
      [
        "10:30",
        60,
        0
      ]
    ],
    "m": 1,
    "distm": 0
  }
}

```

**Comment by heymkeyu** [comment]
```
{
  "cfg":{"id":1,"lg":"it",
    "tm":"00:31:47","dt":"29/07/2020",
    "sc":{"m":1,"distm":0,"ots":{"bc":0,"wtm":60},"p":0,"d":[
      ["00:00",0,0],
      ["08:45",45,1],
      ["08:24",45,1],
      ["08:45",45,1],
      ["08:45",45,1],
      ["08:45",45,1],
      ["10:15",75,1]],"dd":[
      ["00:00",0,0],
      ["10:15",15,1],
      ["09:10",30,1],
      ["10:15",15,1],
      ["10:15",15,1],
      ["10:15",15,1],
      ["00:00",0,0]]},
    "cmd":0,
    "mz":[12,12,0,0],"mzv":[0,1,0,1,0,1,0,1,0,1],
    "rd":30,
    "sn":"20XXXXXXXXX04",
    "modules":{"US":{"enabled":1}
}},
  "dat":{
    "mac":"98XXXXXXXXX80",
    "fw":3.15,"fwb":25,
    "bt":{"t":19.5,"v":19.67,"p":100,"nr":121,"c":0,"m":0},
    "dmp":[1.1,2.6,308.2],
    "st":{"b":17750,"d":257679,"wt":18988,"bl":40},
    "ls":1,"le":0,"lz":3,
    "rsi":-54,"lk":1,"act":1,"tr":0,"conn":"wifi",
    "rain":{"s":0,"cnt":0},
    "modules":{"US":{"stat":"ok"},"DF":{"stat":"ok"}
}}
}
```

**Comment by heymkeyu** [comment]
modules: 
US = ACS
DF = OffLimits

**Comment by hsteinme** [comment]
Ich habe den von @heymkeyu geschilderten Ablauf nachgespielt. Die Zerstörung des 2. Zeitfensters trat bei mir nicht auf. Ablauf:

- Mähzeiten in App eingestellt: montags 09:00, 60, true und montags 15:00, 60, false

`2020-08-07 22:47:57.917  - [34mdebug[39m: worx.0 (4928) GET MQTT DATA from API: {"cfg":{"id":0,"lg":"it","tm":"22:47:55","dt":"07/08/2020","sc":{"m":1,"distm":0,"ots":{"bc":0,"wtm":60},"p":0,"d":[["00:00",0,0],["09:00",60,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]],"dd":[["00:00",0,0],["15:00",60,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]]},"cmd":0,"mz":[6,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"999999999999999999X9","modules":{}},"dat":{"mac":"XXXXXXXXXXXX","fw":3.16,"fwb":4,"bt":{"t":20.9,"v":19.17,"p":100,"nr":443,"c":0,"m":1},"dmp":[3.6,-2.1,337.4],"st":{"b":42053,"d":754954,"wt":44150,"bl":80},"ls":1,"le":0,"lz":8,"rsi":-73,"lk":0,"act":1,"tr":0,"conn":"wifi","rain":{"s":1,"cnt":0},"modules":{"DF":{"stat":"ok"}}}}`

- Beide Mähzeiten werden korrekt empfangen.
- mowTimeExtend = -100 gesetzt

`2020-08-07 22:48:52.565  - [34mdebug[39m: worx.0 (4928) Worxcloud MQTT sendMessage to 999999999999999999X9 Message: {"sc":{"m":1,"distm":0,"p":-100,"d":[["00:00",0,0],["09:00",60,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]],"dd":[["00:00",0,0],["15:00",60,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]]}}`

- Beide Mähzeiten werden korrekt mitgesendet.

`2020-08-07 22:48:54.125  - [34mdebug[39m: worx.0 (4928) GET MQTT DATA from API: {"cfg":{"id":1,"lg":"it","tm":"22:48:51","dt":"07/08/2020","sc":{"m":1,"distm":0,"ots":{"bc":0,"wtm":60},"p":-100,"d":[["00:00",0,0],["09:00",60,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]],"dd":[["00:00",0,0],["15:00",60,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]]},"cmd":0,"mz":[6,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"999999999999999999X9","modules":{}},"dat":{"mac":"XXXXXXXXXXXX","fw":3.16,"fwb":4,"bt":{"t":20.9,"v":19.16,"p":100,"nr":443,"c":0,"m":1},"dmp":[3.6,-2.1,337.4],"st":{"b":42053,"d":754954,"wt":44150,"bl":80},"ls":1,"le":0,"lz":8,"rsi":-73,"lk":0,"act":1,"tr":0,"conn":"wifi","rain":{"s":1,"cnt":0},"modules":{"DF":{"stat":"ok"}}}}`

- Beide Mähzeiten werden erneut korrekt empfangen.

_Adapter Version 1.1.0, Install am 7.8.2020 von GitHub
FW Version 3.16b4_

**Comment by Cosmicbase** [comment]
Adapter Version 1.1.0,  von GitHub habe ich nicht gefunden.
Ich habe 1.0.2 installiert. 
Wo gibt's die 1.1.0?

**Comment by hsteinme** [comment]
> Wo gibt's die 1.1.0?

Bei einer Installation über die GitHub-URL des Adapters

**Comment by MeisterTR** [comment]
try 1.2.3
