### ISSUE TITLE
Partymodus in den Status aufnehmen

### ISSUE THREAD

**Issue by Cosmicbase** [iobroker-community-adapters/ioBroker.worx#65]
Ist es möglich den Partymodus in den Status mitaufzunehmen. Aktuell wird der ja noch nicht synchronisiert.
Ich würde gerne den Partymodus in die Vis in Form einer Switch einbauen. 
So muss ich nicht immer in die App.

**Comment by hsteinme** [comment]
Der Vorschlag, den Partymodus zu unterstützen, ist bereits Teil von https://github.com/iobroker-community-adapters/ioBroker.worx/issues/57. Dort ist er im ersten Kommentar erwähnt. Bitte schließe diesen Thread hier wieder.

@heymkeyu : Könntest Du bitte für eine größere Klarheit den Titel von https://github.com/iobroker-community-adapters/ioBroker.worx/issues/57 entsprechend erweitern (nach Deinem Urlaub). Ich habe keine Rechte dazu.
