### ISSUE TITLE
Adapter sorgt für 24 Stunden Sperre des Accounts

### ISSUE THREAD

**Issue by MKaiser96** [iobroker-community-adapters/ioBroker.worx#656]
Ich habe vor kurzem den ioBroker komplett neu aufgesetzt. Ich habe die aktuelle Version des ioBroker sowie des Worx Adapters installiert. Die Anmeldung funktioniert einwandfrei und die Daten werden synchronisiert. An dem Worx Account sind zwei Landroids angemeldet.

Leider habe ich nach kurzer Zeit Probleme mit der App. Diese meldet "Fehler. Connection timeout" und ich kann nichts mehr einstellen. Die Daten werden scheinbar im 10 Minutenrythmus synchronisiert, aber ein manuelles Synchronisieren ist nicht möglich. Auch über ioBroker kann ich keine Werte ändern. Es laufen auf dem ioBroker keine Programme, die die Datenpunkte des Adapters steuern. Ich lese damit nur Daten aus.

Das Phänomen deutet auf die 24-Stundensperre des Accounts hin. Ich habe testweise den Adapter pausiert und danach konnte ich keine Probleme mit der App feststellen. Es scheint, als würde der Adapter dafür sorgen, dass der Worx Account gesperrt wird.

**Comment by git828** [comment]
Ich habe aktuell dasselbe / ähnliche  Problem festgestellt. 
Daten werden zwar von Cloud ausgelesen in App und Adapter 
, aber kann keine Befehle senden aus der App (Connection Error) oder dem Adapter

**Comment by AirByte2305** [comment]
gleiches Problem, Adapter führte in der aktuellen Version v2.0.3 zur 24h Sperre.

**Comment by TA2k** [comment]
Passiert das auch mit der GitHub Version

**Comment by git828** [comment]
> Ich habe aktuell dasselbe / ähnliche Problem festgestellt. Daten werden zwar von Cloud ausgelesen in App und Adapter , aber kann keine Befehle senden aus der App (Connection Error) oder dem Adapter

Aktuell funktioniert es bei mir wieder ohne Probleme.

**Comment by Kotetsu90** [comment]
> Ich habe aktuell dasselbe / ähnliche Problem festgestellt. Daten werden zwar von Cloud ausgelesen in App und Adapter , aber kann keine Befehle senden aus der App (Connection Error) oder dem Adapter

Hatte bei mir das selbe verhalten. Nachdem ich den Adapter deinstalliert hatte, funktioinerte die App 1 Tag später wieder. Ich installiere jetzt mal die GitHub Version.

**Comment by Lucky-ESA** [comment]
Die GIT Version gibt euch die Info, ob ihr für 24h gesperrt seid. Es wird dann automatisch pausiert und nach 24h wieder neu gestartet. Vielleicht hat Worx was geändert daher bitte weiter beobachten. [Forum](https://forum.iobroker.net/topic/4834/adapter-worx-landroid-v2-x-x/691?_=1680022056410)

**Comment by AirByte2305** [comment]
Nach Installation der GIT Version läuft es bei mir auch seit 3 Tagen ohne Probleme.
Ich werde weiter beobachten

**Comment by MKaiser96** [comment]
Ich habe die GITHub Version einige Tage laufen gehabt. Im Log sind mir vermehrt Einträge zum Worx Adapter aufgefallen. Hier ein Ausschnitt des Protokolls.

![image](https://user-images.githubusercontent.com/50888445/228355067-6856aa55-7edf-4535-a97e-c29ae05c50a7.png)

Beim Login auf den ioBroker kam auch direkt ein Fenster, dass der Worx Adapter pausiert wurde, da er zu oft neugestartet wurde und so manuell wieder aktiviert werden muss.

**Comment by Lucky-ESA** [comment]
Eventuell mag Worx eure Requests nicht mehr. Ihr solltet zwingend eure Blocklys deaktivieren. Habe bereits eine Idee wie man den Worx Calendar besser aktualiseren kann. Der alte MQTT Login wurde über den WInter hinweg komplett deaktiviert daher meine Vermutung, dass Worx was geändert hat.

**Comment by MKaiser96** [comment]
Ich steuere meine Landroids über NodeRED und habe dort testweise alle Flows deaktiviert. Somit werden keine Daten geschrieben. Leider blieben die Probleme bestehen.

**Comment by Lucky-ESA** [comment]
Bitte Adapter auf Debug stellen und einige Befehle ausführen (auch OLMSwitch_FastHoming) bzw. die Zeiten ändern. Mir dann das Protokoll an github@luckyskills.de zusenden.

**Comment by Reefkeeper** [comment]
Gleiches Problem bei mir:
Worx-Adapter im ioBroker installiert, alles klappt prima für ca. 3 Tage.
Dann werden plötzlich nur noch Istwerte im ioBroker aktualisiert. Die Landroid-App kann dann nicht mehr mit Herunterziehen aktualisiert werden, es kommt die Meldung Verbindungsfehler, und eine Bedienung per App klappt nicht mehr.
Problem"behebung":
Landroid-Worx-Adapter stoppen. Dann wird die App sofort wieder funktionsfähig, nicht etwa erst nach 24 Stunden!
Danach kann der Adapter wieder gestartet werden. Bei mir musste ich dann aber auch das App-Passwort wieder eingeben.
Die einzige Warnung, die ich bei mir sehe, ist im Protokoll wiederholt im Abstand von einigen unregelmäßigen Minuten:
worx.0
`	2023-03-30 12:39:31.575	warn	Object of state "worx.0.2018xxxxxxxxx.rawMqtt.auto_schedule_settings" is missing the required property "common.type"`

**Comment by TA2k** [comment]
Ich habe nochmal die github version angepasst aber wäre gut welche states des adapters ihr setzt?

**Comment by Reefkeeper** [comment]
Sofern mich mein Gedächtnis nicht verläßt, war es - wenn überhaupt - nur
`worx.0.2018XXXXX.mower.mowTimeExtend`

Vielen Dank!

**Comment by TA2k** [comment]
Bitte nochmal die github version installieren und ruhig im debug log laufen lassen

**Comment by git828** [comment]
> > Ich habe aktuell dasselbe / ähnliche Problem festgestellt. Daten werden zwar von Cloud ausgelesen in App und Adapter , aber kann keine Befehle senden aus der App (Connection Error) oder dem Adapter
> 
> Aktuell funktioniert es bei mir wieder ohne Probleme.

Passiert wieder. GIt Version installiert. Ich ändere momentan startSequence für die Zone und sendCommand 1,2,3 und 9. 
Wie bereits erwähnt hat es jetzt über ein Woche funktioniert.

Hab noch das Log an github@luckyskills.de gesendet

**Comment by Reefkeeper** [comment]
> Bitte nochmal die github version installieren und ruhig im debug log laufen lassen
Rückmeldung:
Nachdem ich seit über 12 Std. wieder freigeschaltet bin und im Protokoll in der Nacht ca. alle 20 - 30 Minuten die obige Warnung bekommen habe, habe ich heute die Debugprotokollierung aktiviert. Seitdem kam die Warnung aber nicht mehr vor (über ca. 3 Stunden). Ich kann z. Zt. also kein Debugprotokoll mit der Warnung reproduzieren. Ich melde mich aber, sobald sie wieder auftritt.
Installiert ist z. Zt. die Nicht-Git-Version.

**Comment by normen** [comment]
Running into the same issue when re-using your code in my homebridge plugin, attached is a (serial-cleaned) log, should contain everything from this plugin. Could it be this happens when you log in too many times in a row?

[log.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/11141780/log.txt)

**Comment by TA2k** [comment]
You should replace the iobroker in the clientid with home bridge. normally reconnects to mqtt are no issue. Only religions or sending data to worx should be as low as possible.

**Comment by normen** [comment]
> You should replace the iobroker in the clientid with home bridge. normally reconnects to mqtt are no issue. Only religions or sending data to worx should be as low as possible.

Sorry, weiss nicht warum ich angefangen habe englisch zu tippen..
Klar, kann ich machen - willst verhindern dass es auf euch zurückfällt wenn mein Plugin wegen nem Bug anfängt 1000 mal in der Sekunde einzuloggen? xD

**Comment by TA2k** [comment]
Ist nur einfacher bei bugs im richtigen Plugin zu suchen

**Comment by normen** [comment]
Also es hat auf jeden Fall irgendwie mit zu vielen requests zu tun:
```
Apr 07 22:00:15 homebridge homebridge[10076]:   response: {
Apr 07 22:00:15 homebridge homebridge[10076]:     status: 429,
Apr 07 22:00:15 homebridge homebridge[10076]:     statusText: 'Too Many Requests',
Apr 07 22:00:15 homebridge homebridge[10076]:     headers: AxiosHeaders {
Apr 07 22:00:15 homebridge homebridge[10076]:       date: 'Fri, 07 Apr 2023 20:00:13 GMT',
Apr 07 22:00:15 homebridge homebridge[10076]:       'content-type': 'text/plain',
Apr 07 22:00:15 homebridge homebridge[10076]:       'content-length': '17',
Apr 07 22:00:15 homebridge homebridge[10076]:       connection: 'close',
Apr 07 22:00:15 homebridge homebridge[10076]:       'cf-cache-status': 'DYNAMIC',
Apr 07 22:00:15 homebridge homebridge[10076]:       server: 'cloudflare',
Apr 07 22:00:15 homebridge homebridge[10076]:       'cf-ray': '7b44db058d9b39eb-FRA',
Apr 07 22:00:15 homebridge homebridge[10076]:       'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
Apr 07 22:00:15 homebridge homebridge[10076]:     },
Apr 07 22:00:15 homebridge homebridge[10076]:     config: {
Apr 07 22:00:15 homebridge homebridge[10076]:       transitional: [Object],
Apr 07 22:00:15 homebridge homebridge[10076]:       adapter: [Array],
Apr 07 22:00:15 homebridge homebridge[10076]:       transformRequest: [Array],
Apr 07 22:00:15 homebridge homebridge[10076]:       transformResponse: [Array],
Apr 07 22:00:15 homebridge homebridge[10076]:       timeout: 0,
Apr 07 22:00:15 homebridge homebridge[10076]:       xsrfCookieName: 'XSRF-TOKEN',
Apr 07 22:00:15 homebridge homebridge[10076]:       xsrfHeaderName: 'X-XSRF-TOKEN',
Apr 07 22:00:15 homebridge homebridge[10076]:       maxContentLength: -1,
Apr 07 22:00:15 homebridge homebridge[10076]:       maxBodyLength: -1,
Apr 07 22:00:15 homebridge homebridge[10076]:       env: [Object],
Apr 07 22:00:15 homebridge homebridge[10076]:       validateStatus: [Function: validateStatus],
Apr 07 22:00:15 homebridge homebridge[10076]:       headers: [AxiosHeaders],
Apr 07 22:00:15 homebridge homebridge[10076]:       withCredentials: true,
Apr 07 22:00:15 homebridge homebridge[10076]:       httpsAgent: [CookieAgent],
Apr 07 22:00:15 homebridge homebridge[10076]:       url: 'https://id.eu.worx.com/oauth/token',
Apr 07 22:00:15 homebridge homebridge[10076]:       method: 'post',
```

Technisch gesehen habe ich vom plugin gar nichts abgesetzt die letzte Zeit, der neue counter ist auch nicht hoch gegangen... Kein Plan was da schief läuft.

**Comment by MKaiser96** [comment]
Ich habe seit mehr als 24 Stunden den Adapter pausiert, um in der App Einstellungen vornehmen zu können. Jetzt kommt folgender Fehler. 

![IMG_0357](https://user-images.githubusercontent.com/50888445/230672384-8b94a091-d429-4d4d-961b-4c690534fbbb.png)

**Comment by Lucky-ESA** [comment]
Der Worx Server war Offline. Sollte jetzt wieder gehen,

**Comment by MKaiser96** [comment]
Es wurde ein weiteres App Update nachgereicht. Jetzt funktioniert es wieder.

Gibt es schon Neuigkeiten zum Worx Adapter?

**Comment by TA2k** [comment]
Bitte mit v2.1.0 testen ob noch blocks auftreten

**Comment by MKaiser96** [comment]
Ich habe die neue Version installiert und läuft jetzt schon mehr als 24 Stunden ohne Probleme durch.

**Comment by Reefkeeper** [comment]
Bei mir ebenfalls 24 Std. ohne Probleme!
Danke!

**Comment by MKaiser96** [comment]
Leider zu früh gefreut. Soeben habe ich noch einmal die App geprüft und es kommt wieder der Connection timeout.

**Comment by TA2k** [comment]
Bitte immer die logs vom adapter posten

**Comment by Reefkeeper** [comment]
Das bedeutet nicht unbedingt eine Sperre! Bei mir kommt es in letzter Zeit öfter vor, dass ich die App mehrfach auffrischen muss, weil die Meldung "Verbindungsfehler" kommt.

10.04.2023 21:42:02 MKaiser96 ***@***.***>:

**Comment by Kotetsu90** [comment]
2.1.0 gab bei mir leider keine Verbesserung, Sperre nach ca. 20h. Ich hatte kein Script aktiv. 
[worx0-log.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/11198093/worx0-log.txt)

**Comment by TA2k** [comment]
Sieht nicht direkt nach einem block aus. Ein restart des Adapters hat nicht geholfen?

**Comment by Janideluxe** [comment]
bei mir geiches Spiel... gestern hatte ich Probleme mit der App habe daraufhin auf die neue Version geupdated und den Adapter neu gestartet (Start siehe Log)

![Screenshot 2023-04-11 19 36 15](https://user-images.githubusercontent.com/51678652/231244598-fed1ef2b-7e49-4e95-bbbb-e8208baaa590.png)

**Comment by MKaiser96** [comment]
Ich habe eben noch einmal die App gecheckt. Jetzt habe ich komischerweise wieder Zugriff. Ich habe am ioBroker in der Zwischenzeit nichts gemacht. Ich lasse dir trotzdem mal den Log zukommen.

**Comment by MKaiser96** [comment]
Ich habe heute morgen den Adapter wieder deaktiviert, da ich gar keinen Zugriff mehr über die App hatte. Seit heute Abend habe ich wieder Zugriff über die App. Ich vermute immer noch ein Problem mit dem Adapter bzw. den Worx Servern, aber halt nicht die typische 24h Sperre.

**Comment by Kotetsu90** [comment]
> Sieht nicht direkt nach einem block aus. Ein restart des Adapters hat nicht geholfen? Es ist korrekt das zwei Mäher im account und online sind? Ein debug log wäre auch nochmal hilfreich dann per mail [tombox2020@gmail.com](mailto:tombox2020@gmail.com)

2 Mäher sind korrekt. Habe über die letzten 3 Tage einen Debug Log erstellt und schick sie dir per Mail. 
Nach ein paar Stunden waren die Mäher wieder nicht erreichbar. Ein Adapterneustart hat aber geholfen. Mal sehen wie langes es jetzt hält.

**Comment by TA2k** [comment]
Kannst du die github version ein wenig im debug mode laufen lassen

**Comment by MrDuFF85** [comment]
Hab bei mir das gleiche Problem . Es ist kein direkter Block . Login mit dem Adapter und auch mit der App funktioniert, allerdings die Kommunikation nicht . Ist eigenartig wenn man den Worx mit direkt Vorort manuell am Display startet erhält man auch wieder Daten, aber nur bis er wieder in der Station ist. Werde das morgen mal genauer prüfen .
Aber es geht dann weder die App noch der Adapter ( trotz erfolgreichem Login )

**Comment by TA2k** [comment]
Ein debug log mit der aktuellsten version ist hier immer hilfreich sehr gerne an:
tombox2020@gmail.com

**Comment by l-naumann** [comment]
Könnte es sein das alle Betroffenen mind. 2 Mäher im Account haben? Bei mir besteht das Problem seit ich einen zweiten Mäher hinzugefügt habe. Kann natürlich auch Zufall sein.

**Comment by Janideluxe** [comment]
> Könnte es sein das alle Betroffenen mind. 2 Mäher im Account haben? Bei mir besteht das Problem seit ich einen zweiten Mäher hinzugefügt habe. Kann natürlich auch Zufall sein.

Die These könnte ich bestätigen, hatte mit 2 Mähern im Account die selben Probleme. Habe meinen 2. Mäher aus dem Account entfernt und seitdem keinerlei Probleme mehr.

**Comment by TA2k** [comment]
Das ist interessant ich gehe davon aus das beide Mäher aktiv genutzt werden. 

Dann wäre es gut wenn jemand bereit wäre kurz sein Account bereitstellen könnte um zu sehen was der Adapter falsch oder die App anders macht.
tombox2020@gmail.com

**Comment by MrDuFF85** [comment]
Also hab mir mein Problem heute genauer angeschaut und alles mögliche versucht . Worx neu registriert , neues WLAN ausgestrahlt usw. Kommunikation mit der App und Adapter funktioniert nicht und teils sporadisch. Meine Vermutung das es an den Worx Servern liegt wurde heute von mehreren anderern Usern bestätigt .
Es gibt aktuell offensichtlich Probleme seitens Worx.

**Comment by MrDuFF85** [comment]
Laut Debug keine MQTT Verbdinung.  Habe jetzt mal die neuste GitVerstion installiert werde diese nach 24h testen ( aktuell schein ich geblockt zu sein ) 

![worx](https://user-images.githubusercontent.com/24492740/232327710-a98a703f-7a62-4c24-ba7e-dfb435f4860b.jpg)

**Comment by TA2k** [comment]
Wichtig wäre ein log bevor es zu dem block kam oder Zugang zu dem account wenn es sich um 2 Mäher Account handelt

**Comment by Lucky-ESA** [comment]
Laut PIC hat @MrDuFF85 einen komplett anderen host. Hatte diesen auch mal getestet und wurde sofort gesperrt.

**Comment by TA2k** [comment]
Ich habe nochmal in die GitHub version mehr logs eingebaut. Falls unterschiedliche Mäher unterschiedliche Endpunkte haben

**Comment by Kotetsu90** [comment]
Ich hab die Version vom 15.04 instlliert und laufen lassen. Beide Mäher sind seit gestern wieder offline in App. Logs schick ich per Mail.

**Comment by Domi920** [comment]
@TA2k habe die neue Version von gestern installiert.
Die Verbindung scheint zu funktionieren. 
In der Landroid App gibt es keine Verbindungsprobleme.

Allerdings kann ich die Zeitprogrammierung in IOBroker nicht vornehmen. 
Wenn ich die Laufzeit in Minuten ändere, wird diese nicht bestätigt.
Wenn man in der Landroid App aktualisiert, sieht man das die Daten nicht übernommen wurden und die "alten" Daten werden in ioBroker zurückgemeldet.

Ich habe Dir das Log per E-Mail geschickt.

Gruß Dominik

**Comment by MrDuFF85** [comment]
Bei mir funktioniert jetzt seit 2 Tagen nach dem Update der GitVersion die Kommunikation wieder . 1 Mäher bisher kein Block .
Muss jetzt nur mal schauen wie ich jetzt zur richtigen Zeit den Status bekommen für die Steuerung meiner Rollos an der Garage brauche ich die eigentlich fast Live :-(.

kann man den Adapter ggf. Erweitern das man die Abfrage manuell triggern kann . Brauch den Status eigentlich nur bei der Ausfahrt und bei der Heimfahrt . Ist den bekannt wieviele Anfragen der Worx Server zulässt ohne das man geblockt wird . Meine was gelesen zu haben von 1 x pro Minute, das würde mir reichen nur wäre es nice wenn man die Abfrage manuell anstoßen könnte .
Muss mir den Adapter mal genauer anschauen vielleicht bekomm ich das auch irgendwie selber hin .

**Comment by Lucky-ESA** [comment]
Dafür kannst du den DP worx.0.xxx.activityLog.manuell_update verwenden. Hier wird die Cloud abgefragt und nicht über MQTT. Start und Heimfahrt wird ja sofort an den Adapter gesendet. Für MQTT Update kannst du worx.0.xxx.mower.mqtt_update verwenden. Wenn du gesperrt werden solltest, kannst du im Counter sehen wann das passiert -> worx.0.xxx.mower.mqtt_update_count
Kannst uns ja dann die Infos geben, wie oft man einen Request versenden kann :-)

Gruß//Lucky

**Comment by l-naumann** [comment]
Hab die neue Version auch seit 24 Stunden laufen, bisher keine Probleme mehr mit zwei Mähern.

**Comment by Janideluxe** [comment]
> Bei mir funktioniert jetzt seit 2 Tagen nach dem Update der GitVersion die Kommunikation wieder . 1 Mäher bisher kein Block . Vielen Dank für die Anpassung
> 
> Muss jetzt nur mal schauen wie ich jetzt zur richtigen Zeit den Status bekommen für die Steuerung meiner Rollos an der Garage brauche ich die eigentlich fast Live :-(.
> 
> kann man denn Adapter ggf. Erweitern das man die Abfrage manuell triggern kann . Brauch den Status eigentlich nur bei der Ausfahrt und bei der Heimfahrt . Ist den bekannt wieviele Anfragen der Worx Server zulässt ohne das man geblockt wird . Meine was gelesen zu haben von 1 x pro Minute, das würde mir reichen nur wäre es nice wenn man die Abfrage manuell anstoßen könnte . Muss mir den Adapter mal genauer anschauen vielleicht bekomm ich das auch irgendwie selber hin .

wieso triggerst du nicht auf den Datenpunkt worx.0.xxx.mower.status, so mache ich das mit meiner motorischen Roboter Garage, stoppe ihn dann sofort wieder für 10 sekunden damit das Tor auffahren kann und dann starte ich ihn wieder (alles natürlich in nem Skript) so muss man nichts abfragen sondern reagiert nur auf das, was er sendet.

**Comment by Lucky-ESA** [comment]
Die Daten kommen tagsüber automatisch vom MQTT Server und nachts nur bei besondere Ereignisse. Wir hatten vermutet, dass ein Anping notwendig ist um in keine Sperre zu laufen. Diesen Haken sollten man nur zum testen setzen.

**Comment by TA2k** [comment]
Mich würde interessieren ob mit Ping mehr Daten kommen und ob ein Ping zur Sperrung führen kann gerade bei 2 Mähern

**Comment by Kotetsu90** [comment]
Bei mir ebenfalls mit der v2.1.2 keine Probleme mehr seit über 2 Tagen.

**Comment by moelloman** [comment]
Das positive Feedback bzgl. v2.1.2 kann ich bestätigen :)

**Comment by Domi920** [comment]
> Mich würde interessieren ob mit Ping mehr Daten kommen und ob ein Ping zur Sperrung führen kann gerade bei 2 Mähern

Habe die Ping Option in den Einstellungen der Instanz aktiviert.
Vor ein paar Stunden gab es wieder Verbindungsfehler in der Landroid App.
Jetzt funktioniert aber wieder alles.
Obwohl die Ping Option noch aktiviert ist.

Allerdings kann man keine Zeiten Programmieren, weil diese nicht bestätigt werden.

Habe 2 Mäher im Konto & nutze die aktuellste Version vom Adapter V2.1.3

**Comment by TA2k** [comment]
Kommen denn mit ping öfters aktuellere Daten?

**Comment by l-naumann** [comment]
> Hab die neue Version auch seit 24 Stunden laufen, bisher keine Probleme mehr mit zwei Mähern.

Leider zu früh gefreut. Ich kann jetzt immer nur noch einen Mäher steuern. Nach Neustart des Adapters bekomme ich kurz Daten für beide Mäher, nach kurzer Zeit dann aber nur noch für einen Mäher. Wenn ich den anderen Mäher dann steuern  möchte, kommt der Fehler "No mower found!". 

Hier ein Log von Adapter-Neustart bis zu diesem Problem: https://pastebin.com/kFY5LXBt

**Comment by TA2k** [comment]
Das kann eigentlich nicht passieren.. vielleicht nochmal alle Objekte löschen und Adapter von GitHub installieren

**Comment by Lucky-ESA** [comment]
@l-naumann
Einer deiner Mäher hat ein rsi von -83. Bei mir habe ich schon bei -73 in der APP manchmal einen Verbindungsfehler. Hat aber eigentlich nichts damit zu tun das der Mäher mit der SN XXX573B verschwindet. Tombox fügt mehr Logs hinzu damit der Fehler gefunden wird. Bei der neuen Firmware 3.30 soll sich wohl was ändern: Neue Firmware für WLAN

**Comment by l-naumann** [comment]
Der Mäher war zu dem Zeitpunkt am Mähen und wahrscheinlich gerade am anderen Ende des Gartens. Habe bisher aber keine Probleme damit gehabt.
Ich habe den Adapter vorhin komplett deinstalliert und die 2.1.3 installiert. Hat leider nichts gebracht, der Mäher verschwindet immer noch.

**Comment by TA2k** [comment]
Die GitHub version installieren da sollten dann mehr logs sichtbar sein

**Comment by Lucky-ESA** [comment]
@l-naumann
Kannst du bitte erneut vom GIT laden und im Debug Modus laufen lassen.

**Comment by MKaiser96** [comment]
Ich möchte mal kurzes Feedback geben.

Bei mir funktioniert der Adapter einwandfrei. Ich lese vorwiegend nur die Daten und steuere die Mähzeitverlängerung sowie den Startpunkt der Zone. Das funktioniert soweit ich das überprüfen kann einwandfrei.

**Comment by Domi920** [comment]
> 

Meinst du auf längere Sicht bzw. auf einen Zeitraum von ein paar Tagen, oder überhaupt?

**Comment by Domi920** [comment]
> Wie genau schreibst du die Zeiten? Nach dem du die Zeiten in den Datenpunkten schreibst und danach worx.0.xxx.calendar.calJson_sendto auf true setzt?

Du hast recht!
Dann funktioniert es, danke!

@TA2k in der "alten" Version musste man nicht extra erst "worx.0.202130267101009806F3.calendar.calJson_sendto" auf true setzen. Es genügte, wenn man in den jeweiligen Ordnern die Zeit änderte.
Muss ich da selbst was programmieren, dass die Zeiten übernommen werden, oder gibt es eine Möglichkeit dass dies wieder automatisch geht?

**Comment by Lucky-ESA** [comment]
**Bitte bei 24h Sperre bleiben!**
Hier meine Beiträge lesen und auch dort andere Fragen stellen.
[Worx Thread](https://forum.iobroker.net/topic/4834/adapter-worx-landroid-v2-x-x/764)

Wir mussten diese Änderungen vornehmen um die Requests zu reduzieren und NEIN, dass werden wir nicht mehr ändern.
In der Handy APP kannst du auch alle Zeiten eingeben und musst danach speichern drücken. Genau so funktioniert jetzt der Adapter.
Mit Blocklys oder Java alle gewünschten Zeiten eintragen und nach einer Pause von 1,1 Sek. den Button xxx.calendar.calJson_sendto auf true setzen.

Gruß//Lucky

**Comment by Domi920** [comment]
> **Bitte bei 24h Sperre bleiben!** Hier meine Beiträge lesen und auch dort andere Fragen stellen. [Worx Thread](https://forum.iobroker.net/topic/4834/adapter-worx-landroid-v2-x-x/764)
> 
> Wir mussten diese Änderungen vornehmen um die Requests zu reduzieren und NEIN, dass werden wir nicht mehr ändern. In der Handy APP kannst du auch alle Zeiten eingeben und musst danach speichern drücken. Genau so funktioniert jetzt der Adapter. Mit Blocklys oder Java alle gewünschten Zeiten eintragen und nach einer Pause von 1,1 Sek. den Button xxx.calendar.calJson_sendto auf true setzen.
> 
> Gruß//Lucky

Ok, danke für den Link :-)

Gut diese Information zu haben. Diese Info wäre in den Changelog gut gewesen, dann hätt ichs sofort gelesen.
Wie kommst du auf die Zeit von 1,1 Sekunden genau?

**Comment by l-naumann** [comment]
Hat jetzt eine Woche gedauert bis das "No mower found" Problem wieder aufgetreten ist.
Hier das Log: https://pastebin.com/ttXw6byr

**Comment by TA2k** [comment]
Wieviele Mäher hast du denn sind die immer alle drei dauerhaft aktiv?

**Comment by Lucky-ESA** [comment]
> @l-naumann Kannst du bitte erneut vom GIT laden und im Debug Modus laufen lassen.

Du hast nicht die aktuelle GIT Version geladen. Bitte heute neu laden und dann wieder testen. Sollte der Fehler noch immer bestehen dann sende uns bitte deine kompletten LOG`s an tombox2020@gmail.com und an github@luckyskills.de

Gruß//Lucky

**Comment by l-naumann** [comment]
Bin auf Stand von Commit [a492743](https://github.com/iobroker-community-adapters/ioBroker.worx/commit/a492743). Das war der aktuelle Commit nachdem ihr mir geschrieben hattet. Werde dann jetzt nochmal updaten, kann aber wieder einige Tage dauern bis der Fehler auftritt.

**Comment by Lucky-ESA** [comment]
Danach hatte ich dir geschrieben "bitte aktualisieren". Der Commit ee20683 könnte dein Problem lösen.

Gruß//Lucky

**Comment by l-naumann** [comment]
Seither keine Probleme mehr. Ich denke hier kann man so langsam mal zu machen.

**Comment by Lucky-ESA** [comment]
Wir hatten ja dank deiner Logs den Fehler gesehen. Wir mussten aber erneut noch was ändern.
Daher bitte noch mal vom GIT laden aber du musst nichts mehr prüfen.

**Comment by mbhomie007** [comment]
Gibt es bald ein neues Release, wo der Fix enthalten ist?

**Comment by mcm1957** [comment]
should be fixed with 2.2.0.

Please confirm

**Comment by Lucky-ESA** [comment]
Fixed in Release > 2.1.0
New Mqtt Connection > 2.3.1
