### ISSUE TITLE
Manuellen Bordercut (Randschnitt) einbinden

### ISSUE THREAD

**Issue by Cosmicbase** [iobroker-community-adapters/ioBroker.worx#66]
Mit der der Landroid App 2.0.1 und der FW 3.16 ist jetzt auch ein manueller Randschnitt möglich.
Könnte man den auch in den Adapter einbauen und wenn ja wie und ab wann?

**Comment by hsteinme** [comment]
Ein Kantenschnitt ist schon seit einer "gefühlten Ewigkeit" im Adapter aufrufbar, und zwar über den Datenpunkt mower.edgecut. Leider gab es zwischendurch einige Firmware-Versionen, die dies unterbanden. In neueren FW-Versionen läuft es wieder. Ich hatte dies zuletzt mit der FW-Version 3.15b16 und der Adapter-Version 1.0.2 positiv getestet. Bitte daher diesen Issue wieder schließen.

Siehe auch https://github.com/iobroker-community-adapters/ioBroker.worx/issues/62
