### ISSUE TITLE
Klingenlaufzeit wird nicht synchronisiert

### ISSUE THREAD

**Issue by Cosmicbase** [iobroker-community-adapters/ioBroker.worx#67]
Seit dem App Update 2.0.1 ist es möglich die Klingenlaufzeit auf 0 zu setzen (Klingenwechsel).
Leider wird die Laufzeit nicht synchronisiert.

**Comment by hsteinme** [comment]
- Welchen Wert liefert die App?
- Welchen Wert liefert der Adapter in totalBladeTime?
- Erinnerst Du Dich noch, bei welchem Wert Dein letzter Reset durchgeführt wurde?

**Comment by Cosmicbase** [comment]
Die App sagt jetzt 0 Stunden Klingennutzung.
Der Adapter 148h.
Ursprünglich war es in der App auch 148h.
Habe es in der neuen App auf 0 gesetzt weil ich tatsächlich die Klingen getauscht habe.

**Comment by hsteinme** [comment]
totalBladeTime liefert den Wert dat.st.b des MQTT-Servers. Das ist die Klingenlaufzeit seit "Geburt" des Mähers. totalBladeTime sollte aus Kompatibilitätsgründen diesen Wert auch weiterhin liefern.

Beim Resetten der Klingenarbeitszeit stellt die App die bisherige Laufzeit (und den Reset-Timestamp) an anderer Stelle in der Cloud ab. Bei jeder Anzeige der Klingenarbeitszeit verringert die App dann die weiterhin vom Mäher geschickte Gesamtlaufzeit der Klingen um diesen zwischengespeicherten "Basiswert".

Es ist halt die Frage, ob der Adapter noch einen neuen Datenpunkt currentBladeTime bereitstellen soll, der dann die Laufzeit seit letztem Reset darstellt.

@MeisterTR: siehe JSON.raw.blade_work_time und blade_work_time_reset und blade_work_time_reset_at.

Eine analoge Fragestellung ergibt sich übrigens auch bei den Batterieladezyklen, die ja auch zurück gesetzt werden können.

**Comment by verkel21** [comment]
Hallo zusammen, ja das ist mir auch schon aufgefallen. Wäre schön wenn man die Datenpunkt noch in IoBroker hätte, als Benachrichtigung für einen Klingenwechsel.

**Comment by MeisterTR** [comment]
bleibt so, rest muus man dann über ein script realisieren.. :)

**Comment by hsteinme** [comment]
> rest muus man dann über ein script realisieren

D.h. ein Script müsste die Differenz zwischen dat.st.b und blade_work_time_reset bilden. dat.st.b stellt der Adapter in totalBladeTime  zur Verfügung. Wie kann ein Sript aber an blade_work_time_reset kommen?

**Comment by TA2k** [comment]
Ich habe dazu mal ein PR gemacht #267

**Comment by TA2k** [comment]
Einfach die github version installieren dann in den Optionen rohdaten aktivieren dann sieht man alle rohdaten.
