### ISSUE TITLE
Nach Fehler wieder einschalten

### ISSUE THREAD

**Issue by ChrisMuc44** [iobroker-community-adapters/ioBroker.worx#678]
Hallo Zusammen,
Ich habe den Adapter installiert. Fehler zurücksetzen oder einschalten nach Fehler ist durch diesen Adapter nicht möglich, korrekt? Gibt es eine Möglichkeit den Roboter aus der Ferne nach Fehler wieder einzuschalten und zu starten?

Herzlichen Dank

Christof

**Comment by Lucky-ESA** [comment]
Hallo,
das ist leider nicht möglich.

Gruß//Lucky

**Comment by hsteinme** [comment]
Hintergrund dieser fehlenden Möglichkeit sind europaweit geltende Sicherheitsrichtlinien, die es verbieten, auf Fehler gestoßene Automaten ohne direkten Sichtkontakt wieder in Gang zu setzen.
