### ISSUE TITLE
Neue Funktionen in Android App mit FM 3.16

### ISSUE THREAD

**Issue by wolwo3** [iobroker-community-adapters/ioBroker.worx#68]
Hallo,

es gibt ein Android- App Update zu FW3.16: 
Mehrere Mähzeiten pro Tag
Zonen anpassbar (Startpunkt)
Partymode
usw...

Es wäre toll diese Funktionen auch in den Adapter zu integrieren, speziell die Mähzeiten und den Partymode.
Gleichfalls möchte ich mich für die Entwicklung des Adapters bedanken!

**Comment by Cosmicbase** [comment]
Ich finde persönlich den Adapter sehr super und nutze auch div. Datenpunkte in meiner Vis. Vielen Dank an den Entwickler @MeisterTR und Co .
Jetzt kommt leider das große ABER und da muss ich den anderen Usern zustimmen, das ein ständiges Auf und Zumachen von Issues an der Entwicklungsarbeit nix ändert. Ebenso fehlende Dinge wie in #57 beschrieben sind sehr spärlich beschrieben sind und man keinen Einblick hat wann ein Release kommt.
Interessant wären eher an dieser Stelle Kommentare von den @MeisterTR , etc.

Ich selber würde den Partymodus liebend gerne einbauen, oder auch die Klingenlaufzeit etc. resetten. Nur funktioniert das NOCH nicht.

**Comment by MeisterTR** [comment]
teste 1.2.3
