### ISSUE TITLE
Cloud connection error 

### ISSUE THREAD

**Issue by ITCrowdIOB** [iobroker-community-adapters/ioBroker.worx#70]
The Status is only yellow and the following Error Mesages are in the iobroker log.

worx.0 | 2020-08-26 22:38:20.730 | error | (4618) ERROR: RequestError: Error: getaddrinfo ENOTFOUND api.worxlandroid.com
-- | -- | -- | --
worx.0 | 2020-08-26 22:38:20.729 | error | (4618) Could not Connect to Worx Server: RequestError: Error: getaddrinfo ENOTFOUND api.worxlandroid.com

Same Problem in 1.0.2 and 1.2.0

**Comment by MeisterTR** [comment]
please make an adapter upload, and send a debug log

**Comment by MeisterTR** [comment]
fixed in 1.2.3
