### ISSUE TITLE
Object worx.0.XXXXXXXXX.areas.startSequence is invalid: Default value has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by mbhomie007** [iobroker-community-adapters/ioBroker.worx#704]
Seit Version 2.2.0 wird folgende Meldung im Log angezeigt:

![Screenshot 2023-06-30 093913](https://github.com/iobroker-community-adapters/ioBroker.worx/assets/64688879/91f7b935-9e99-4a9a-ae8c-bb153756537d)

![Screenshot 2023-06-30 093622](https://github.com/iobroker-community-adapters/ioBroker.worx/assets/64688879/1eda17d1-b784-4d92-970c-45da15b0b4ac)

![image](https://github.com/iobroker-community-adapters/ioBroker.worx/assets/64688879/8749fc13-ab69-4bb5-b816-62a6dc6e5605)

**Comment by mcm1957** [comment]
@Lucky-ESA 
Looks like this is related to your change 4128a6184fed1e808ebf83994c474734b7467991

When really a change of the type of an object is requried, the code should handle the migration of existing objects (extendObject all) or at least the user MUST be advided to delete the old object manually (although this solution is suboptimal).

Anyway - check the default value too, this seesm to be of wrong type too.

**Comment by Lucky-ESA** [comment]
@mbhomie007
Danke für die Info. Hatte def: 0 nicht gelöscht.
Fix ich heute noch.

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Fixed with Release 2.3.1
