### ISSUE TITLE
Incorrect role value specified for startSequence

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.worx#705]
Code uses invalid role "json" for state startSequence

role: "json",

Roles MUST use values listed at https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md only.
json is no valid role.

Did you meant common.type='json' (instead of 'string')?

**Comment by Lucky-ESA** [comment]
@mcm1957 
The role is correct.

json common.type = string

This is the only way to change the value with Blocklys.

**Comment by mcm1957** [comment]
Sorry, your are correct.

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md#common
