### ISSUE TITLE
Is this adapter a replacement for iobroker-community-adapters/ioBroker.landroid ?

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.worx#707]
Please check whether this adapter (worx) can replace the following adapter https://github.com/iobroker-community-adapters/ioBroker.landroid.

**Comment by Lucky-ESA** [comment]
Yes, this adapter can replace ioBroker.landroid.

**Comment by mcm1957** [comment]
Adapter landroid has been deprecated and a suggestion to move to workx has been posted.

https://github.com/iobroker-community-adapters/ioBroker.landroid/issues/170
