### ISSUE TITLE
available firmwares

### ISSUE THREAD

**Issue by Lucky-ESA** [iobroker-community-adapters/ioBroker.worx#712]
No data is currently coming from Worx for the available firmwares.

Von Worx kommen derzeit keine Daten für die verfügbaren Firmwares.

Wir müssen leider warten...

Gruß//Lucky

**Comment by manny4566** [comment]
Ist das der Grund warum der Adapter keine Firmware Updates anzeigt?
Mein Roboter hat laut App nämlich die 3.30 offen. Der Adapter zeigt aber weiterhin an, dass nur die 3,28, die bereits installiert ist, vefügbar ist (worx.0.xxx.mower.firmware_available)
Danke

**Comment by Lucky-ESA** [comment]
Das ist korrekt.

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Fixed with Release 2.3.1
