### ISSUE TITLE
in V2.3.1 werden areas objekte nicht richtig angelegt

### ISSUE THREAD

**Issue by Jogi2020** [iobroker-community-adapters/ioBroker.worx#721]
Nach Update auf v2.3.1 werden folgende Warnungen angezeigt:
<html>
<body>

worx.0 | 2023-07-20 19:59:18.277 | warn | State "worx.0.2019xxxxxxxxxxxxxxxxxxE.areas.actualAreaIndicator" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
worx.0 | 2023-07-20 19:59:18.276 | warn | State "worx.0.2019xxxxxxxxxxxxxxxxxxE.areas.actualArea" has no existing object, this might lead to an error in future versions

</body>
</html>

Ich habe nach dem Update alle Objekte vom Works Adapter gelöscht.
Dann den Adapter neu gestartet, damit die Objekte neu angelegt werden.
Heute standen dann die Warnungen im Protokoll.
Ich habe jetzt die beiden Objekte manuell angelegt.

**Comment by Lucky-ESA** [comment]
Ist bereits in der GIT Version behoben. 4 neue Datenpunkte haben auch keine Schreibrechte.

**Comment by Lucky-ESA** [comment]
Fixed in Release 2.3.2
