### ISSUE TITLE
Error message with 2.3.2

### ISSUE THREAD

**Issue by flapman** [iobroker-community-adapters/ioBroker.worx#729]
Getting a lot of error after updating to 2.3.2. after error Adapter starts again and the same happens.
`
<html>
<body>

host.raspberrypi4 | 2023-08-07 01:20:18.890 | info | Restart adapter system.adapter.worx.0 because enabled
-- | -- | -- | --
host.raspberrypi4 | 2023-08-07 01:20:18.890 | error | instance system.adapter.worx.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi4 | 2023-08-07 01:20:18.890 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
host.raspberrypi4 | 2023-08-07 01:20:18.889 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1155:14)
host.raspberrypi4 | 2023-08-07 01:20:18.889 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/aws-crt/dist/native/auth.js:20:35)
host.raspberrypi4 | 2023-08-07 01:20:18.889 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:103:18)
host.raspberrypi4 | 2023-08-07 01:20:18.889 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1057:19)
host.raspberrypi4 | 2023-08-07 01:20:18.889 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:868:12)
host.raspberrypi4 | 2023-08-07 01:20:18.889 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1033:32)
host.raspberrypi4 | 2023-08-07 01:20:18.888 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
host.raspberrypi4 | 2023-08-07 01:20:18.888 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1155:14)
host.raspberrypi4 | 2023-08-07 01:20:18.888 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/aws-crt/dist/native/binding.js:97:11)
host.raspberrypi4 | 2023-08-07 01:20:18.888 | error | Caught by controller[0]: /opt/iobroker/node_modules/aws-crt/dist/bin/linux-arm-glibc/aws-crt-nodejs
host.raspberrypi4 | 2023-08-07 01:20:18.888 | error | Caught by controller[0]: Error: AWS CRT binary not present in any of the following locations:
host.raspberrypi4 | 2023-08-07 01:20:18.888 | error | Caught by controller[0]: ^
host.raspberrypi4 | 2023-08-07 01:20:18.888 | error | Caught by controller[0]: throw new Error("AWS CRT binary not present in any of the following locations:\n\t" + search_paths.join('\n\t'));
host.raspberrypi4 | 2023-08-07 01:20:18.887 | error | Caught by controller[0]: /opt/iobroker/node_modules/aws-crt/dist/native/binding.js:97
host.raspberrypi4 | 2023-08-07 01:20:17.439 | info | instance system.adapter.worx.0 started with pid 7667

</body>
</html>`

**Comment by Lucky-ESA** [comment]
What firmware do you have on your Raspberry?
Node?
NPM?

**Comment by flapman** [comment]
Node v16.18.1
NPM 8.19.2

**Comment by Lucky-ESA** [comment]
And your system?
pi@iobroker:~ $ cat /proc/version && hostnamectl

**Comment by hsteinme** [comment]
Me too had this error "AWS CRT binary not present in ...". Re-installing the adapter from GitHub ended up with error 25. Then I executed:
- all instances of the adapter stopped
- iob stop
- iob fix
- iob start
- re-installing the adapter - without any "bad" exit code
- starting the adapter's instances

... and they all could be started without any problems.

**Comment by Lucky-ESA** [comment]
Fixed with 3.0.0
