### ISSUE TITLE
"totalBladeTime" don't reset after reset in App

### ISSUE THREAD

**Issue by mbhomie007** [iobroker-community-adapters/ioBroker.worx#748]
After I click in the Android App on reset button, the counter don't reset the blade time in adapter state.
After new adapter start, the issue don't solved.

So the states are not up to date with the app.

adapter v2.3.2

![image](https://github.com/iobroker-community-adapters/ioBroker.worx/assets/64688879/5c1a3bcf-b187-4e1b-bdb7-7c5cd010dcd1)

![Screenshot_20230828_094337_Landroid](https://github.com/iobroker-community-adapters/ioBroker.worx/assets/64688879/d22759fc-3f45-4259-ad76-0a20a784ca72)

**Comment by Lucky-ESA** [comment]
You must calculate the blade working time yourself.
worx.0.xxx.mower.totalBladeTime - worx.0.xxx.rawMqtt.blade_work_time_reset == current work time

BR//Lucky

**Comment by mbhomie007** [comment]
Okay, so the blade values don't synchronise between the adapter and the app, right?

**Comment by hsteinme** [comment]
This topic has nothing to do with synchronisation. The app does not have its own data storage. The two values mentioned by @Lucky-ESA, totalBladeTime and blade_work_time_reset, are stored separately in the cloud. The app fetches the values from there, calculates the difference and displays it. And this is exactly how a user/script of the worx adapter must proceed.

**Comment by mbhomie007** [comment]
Thank you very much for your detailed information.
