### ISSUE TITLE
"firmware_available_date" not correct

### ISSUE THREAD

**Issue by mbhomie007** [iobroker-community-adapters/ioBroker.worx#749]
"firmware_available_date" not correct "Thu Jan 01 1970"

v2.3.2

![image](https://github.com/iobroker-community-adapters/ioBroker.worx/assets/64688879/3ffd21c0-c50d-4285-96b1-90ef4aae3d7b)

**Comment by Lucky-ESA** [comment]
Please read the description.
[Description](https://github.com/iobroker-community-adapters/ioBroker.worx/blob/master/docs/en/README.md)
[Beschreibung](https://github.com/iobroker-community-adapters/ioBroker.worx/blob/master/docs/de/README.md)

Date available firmware - Dummy 1970-01-01 when the adapter is reinstalled and no update is available (wire & Vision/readonly)
