### ISSUE TITLE
change request: send raw json to mower

### ISSUE THREAD

**Issue by Maj0rT** [iobroker-community-adapters/ioBroker.worx#756]
Hi,
It would be great if you had the option to transfer a raw json.
Sometimes the firmware already supports features that the app does not yet include. Currently, for example, activating "over the border" for the WR206E, which can already be activated using the following JSON:
`{"mz":{"p":[],"s":[{"id":1,"c":1,"cfg":{"cut":{"bd":100,"ob":1}}}]}}`
Best regards,
Torsten

**Comment by Lucky-ESA** [comment]
Added ONLY mz json in release 2.3.3 latest or stable >= 2.3.3
I cannot implement an uncontrolled JSON.

**Comment by Lucky-ESA** [comment]
@Maj0rT Kannst du bitte mal testen? Kann sonst nicht in stable wechseln.
