### ISSUE TITLE
sendCommand stopped working

### ISSUE THREAD

**Issue by l-naumann** [iobroker-community-adapters/ioBroker.worx#772]
The sendCommand function for my M500 and M700 mowers stopped working a few weeks ago.
No matter which command I try to send, it's not executed. Everything else works fine.

Log output:
<html>
<body>

worx.0 | 2023-10-04 15:50:25.532 | debug | GET MQTT DATA from API: {"cfg":{"id":---,"sn":"---","dt":"04/10/2023","tm":"15:49:15","lg":"en","cmd":0,"sc":{"m":2,"d":[["10:30",0,0],["10:30",480,1],["10:30",480,0],["10:30",480,1],["10:30",480,0],["10:30",480,1],["10:30",480,1]],"dd":[["09:00",0,0],["18:30",0,0],["18:30",0,0],["18:30",0,0],["18:30",0,0],["18:30",0,0],["18:30",0,0]],"distm":0,"p":0,"ots":{"wtm":0,"bc":0}},"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"mzk":1,"rd":90,"al":{"lvl":1,"t":600},"tq":0},"dat":{"mac":"---","fw":3.32,"fwb":1,"ls":7,"le":0,"conn":"wifi","bt":{"t":22.8,"v":17.65,"p":33,"nr":263,"c":0,"m":1},"dmp":[3.9,-4.5,286.4],"st":{"b":52743,"d":912289,"wt":53550,"bl":61},"act":1,"rsi":-78,"lk":0,"tr":0,"lz":0,"rain":{"s":0,"cnt":0}}}
-- | -- | -- | --
worx.0 | 2023-10-04 15:50:25.521 | debug | {"id":---,"uuid":"---","product_id":50,"user_id":---,"serial_number":"---","mac_address":"---","name":"---","locked":false,"firmware_version":"3.32.0+1","firmware_auto_upgrade":true,"push_notifications":true,"sim":null,"push_notifications_level":"warning","test":false,"iot_registered":true,"mqtt_registered":true,"pin_code":null,"registered_at":"2021-08-12 00:00:00","online":true,"app_settings":null,"protocol":0,"pending_radio_link_validation":null,"capabilities":["auto_lock","bluetooth_pairing","border_cut","digital_fence_settings","follow_border","lock","mqtt","multi_zone","multi_zone_percentage","one_time_scheduler","ota_upgrade","pairing_smartconfig","pause_over_border","pause_over_wire","rain_delay","rain_delay_start","safe_go_home","scheduler_two_slots","unrestricted_mowing_time","zone_keeper"],"capabilities_available":[],"features":{"auto_lock":3.25,"bluetooth_pairing":true,"chassis":"m_2019","digital_fence_settings":3.25,"display_type":"lcd","input_type":"keyboard_arrow_keys","lock":true,"mqtt":true,"multi_zone":true,"multi_zone_percentage":true,"multi_zone_zones":4,"one_time_scheduler":3.15,"pause_over_wire":3.26,"rain_delay":true,"rain_delay_start":3.08,"safe_go_home":3.25,"scheduler_two_slots":3.15,"unrestricted_mowing_time":true,"wifi_pairing":"smartconfig"},"accessories":null,"mqtt_endpoint":"iot.eu-west-1.worxlandroid.com","mqtt_topics":{"command_in":"PRM100/---/commandIn","command_out":"PRM100/---/commandOut"},"warranty_registered":true,"purchased_at":"2021-08-11 00:00:00","warranty_expires_at":"2024-08-11 00:00:00","setup_location":{"latitude":---,"longitude":---},"city":{"id":---,"country_id":276,"name":"---","latitude":---,"longitude":---,"created_at":"2018-02-15 22:34:24","updated_at":"2018-02-15 22:34:24"},"time_zone":"Europe/Berlin","lawn_size":137.14538574219,"lawn_perimeter":61,"auto_schedule_settings":null,"auto_schedule":false,"improvement":true,"diagnostic":true,"distance_covered":910284,"mower_work_time":53434,"blade_work_time":52629,"blade_work_time_reset":0,"blade_work_time_reset_at":null,"battery_charge_cycles":263,"battery_charge_cycles_reset":0,"battery_charge_cycles_reset_at":null,"created_at":"2021-03-23 05:35:00","updated_at":"2023-07-31 12:15:55","last_status":{"timestamp":"2023-10-04 13:49:16","payload":{"cfg":{"id":18712,"sn":"---","dt":"04/10/2023","tm":"15:49:15","lg":"en","cmd":0,"sc":{"m":2,"d":[["10:30",0,0],["10:30",480,1],["10:30",480,0],["10:30",480,1],["10:30",480,0],["10:30",480,1],["10:30",480,1]],"dd":[["09:00",0,0],["18:30",0,0],["18:30",0,0],["18:30",0,0],["18:30",0,0],["18:30",0,0],["18:30",0,0]],"distm":0,"p":0,"ots":{"wtm":0,"bc":0}},"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"mzk":1,"rd":90,"al":{"lvl":1,"t":600},"tq":0},"dat":{"mac":"---","fw":3.32,"fwb":1,"ls":7,"le":0,"conn":"wifi","bt":{"t":22.8,"v":17.65,"p":33,"nr":263,"c":0,"m":1},"dmp":[3.9,-4.5,286.4],"st":{"b":52743,"d":912289,"wt":53550,"bl":61},"act":1,"rsi":-78,"lk":0,"tr":0,"lz":0,"rain":{"s":0,"cnt":0}}}},"last_gps_status":null}
worx.0 | 2023-10-04 15:49:06.829 | debug | Worxcloud MQTT sendMessage to --- Message: {"cmd":2}
worx.0 | 2023-10-04 15:49:06.829 | debug | Send cmd:2

</body>
</html>

**Comment by mcm1957** [comment]
Please add version infos:
Adapter
Admin
Js-controller
Node
O/S

**Comment by l-naumann** [comment]
I was unable to update from 2.1.3 to 2.3.x. Now managed to do it and the issue is resolved.
