### ISSUE TITLE
instance system.adapter.worx.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

### ISSUE THREAD

**Issue by zoizo030** [iobroker-community-adapters/ioBroker.worx#800]
**Versions:**  
 - Adapter version: 2.3.4
 - JS-Controller version: 5.0.16
 - Node version: 18.17.1
 - NPM: 10.2.3
 -  javascript:     7.1.6
 - Operating system: Admin 6.12.3
 - Rasberry 3 B

Nachträglicher Test geändert auf
CHANGE Node auf 18.18.2
CHANGE NPM: 9.8.1

![worx2](https://github.com/iobroker-community-adapters/ioBroker.worx/assets/133063783/ed0d63e1-25f4-4a6b-b3cf-404d94d43280)

Systemcheck mit iob diag

[systemcheck.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/13369429/systemcheck.txt)

**Screenshots & Logfiles**

**Comment by mcm1957** [comment]
Node version: 18.17.1
NPM: 10.2.3

There's something wrong:
Node 18 is boundled with npm 9.x.x.

not sure whther this is related to issue but you shoudl install ths npm version which is delivered with node an never ever updat enpm seperatly.

**Comment by zoizo030** [comment]
Ok have Change: 

Node.js: v18.18.2
NPM: 9.8.1

same mistake 
Uninstalling and restarting didn't help

[error.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/13370359/error.txt)

**Comment by Ilovegym66** [comment]
looks like your Node installation is faulty or/and system not fine, open a new thread in the iobroker.forum to support this, please.
some hints:
make a backup of iobroker and raspi
cd /opt/iobroker
iob stop
iob nodejs-update

this command check your node and npm installation and if you wish, it corrects it.

**Comment by Lucky-ESA** [comment]
@zoizo030 
Bitte dein System neu aufsetzen und am besten ohne Backup. Von deinen Javascripts kannst du ein Backup erstellen und wiederherstellen.
Buster - geht gar nicht!

[Raspberry Pi OS Lite - System: 64-bit - Debian version: 12 (bookworm)](https://www.raspberrypi.com/software/operating-systems/)

Dann sollte es mit dem Adapter auch funktionieren.

Des Weiteren muss du dir Gedanken dazu machen dir neue HW zu kaufen. 1GB Ram ist zu wenig!

Gruß//Lucky

**Comment by zoizo030** [comment]
Hat jetzt funktioniert.Es läuft danke.  Ich hatte umschaltbare nodes zum testen drin. 

Ich habe nur noch aktuell worx drauf da ich die Home Automatisation 98% über Loxone habe. 
Aber der liebe worx geht leider nur über ne Bridge.

Ja 1GB ist zu wenig. Wird denk ich bald als Docker laufen auf einem NAS.

**Comment by Lucky-ESA** [comment]
Wenn du nur Worx hast dann sollten die 1GB noch reichen. Wechsel aber bitte noch auf bookworm da Buster veraltet ist und vielleicht Sicherheitslücken hat.
Buster - Bullseye - Bookworm

Gruß//Lucky
