### ISSUE TITLE
Vision advanced scheduler

### ISSUE THREAD

**Issue by Lucky-ESA** [iobroker-community-adapters/ioBroker.worx#809]
Worx has expanded the Vision scheduler to include more daily slots (more than 2 slots possible).
Android APP: Vision advanced scheduler with more daily slots and zone assignments
**Please do not create more than 2 time slots per day!!! I currently don't know whether all time slots will be transferred to the mower!**

Worx hat den Vision Mähplaner um mehr Tagesslots erweitert (mehr als 2 Slots möglich).
Android APP: Erweiterter Vision-Planer mit mehr täglichen Slots und Zonenzuweisungen
**Bitte nicht mehr als 2 Zeitfenster pro Tag erstellen!!! Ob alle Zeitfenster zum Mäher übertragen werden ist mir derzeit nicht bekannt!**

**Comment by Lucky-ESA** [comment]
@hsteinme Danke für dein Info.

Der Vision ist ja hier komplett implementiert. Beim Vision kommen nur Timeslots die gefüllt sind und der Adapter füllt diese bis auf 2 Mähzeiten pro Tag auf. Somit ist sichergestellt, dass die Datenpunkte richtig gefüllt werden. Jetzt können Vision Nutzer mehr als 2 Mähzeiten pro Tag erstellen. Sollten nun 3 Mähzeiten per API kommen werden allerdings nur 2 erwartet, wird der Adapter crachen. Das kann ich erst testen, wenn ein User sein Mäher aus dem Winterschlaf holt. Aber auch dann habe ich noch keine Idee wie ich das umsetzen soll. Erstelle ich Datenpunkte, muss ich bei jeder Aktualisierung prüfen, ob zu viele oder zu wenige Datenpunkte vorhanden sind. Dann entweder die Datenpunkte löschen oder neue erstellen. Schlimmer wird es im "rawMqtt" da dort angelegte Datenpunkte nicht geprüft werden.
Kress werde ich wohl so nicht umsetzen können da mir die Hardware fehlt.

Gruß//Lucky

**Comment by hsteinme** [comment]
> Beim Vision kommen nur Timeslots die gefüllt sind und der Adapter füllt diese bis auf 2 Mähzeiten pro Tag auf.

Upps! Bei mir heute Morgen nicht, siehe obige Screenshots - obwohl ich den Adapter heute Morgen neu installiert hatte (aus GitHub) und obwohl ich den Vision erst heute Morgen in den entsprechenden Account gesetzt hatte. Auch waren heute Morgen die Datenpunkte Saturday2 usw. überhaupt nicht angelegt.

Ich habe nun den Calendar-Folder gelöscht und die Instanz durchgestartet. Und sieh an: Die Werte werden nun so dargestellt, wie Du es beschrieben hast. Klasse! Sorry für die so entstandene Verwirrung.

Dennoch sollten die Nutzer sich bewusst sein,
- dass die Zoneninformation nicht verfügbar ist
- dass die Datenpunkte zwar vom Adapter her beschreibbar sind, dass aber die Cloud bzw. der Mäher Änderungen nicht annimmt.

**Comment by hsteinme** [comment]
> Sollten nun 3 Mähzeiten per API kommen werden allerdings nur 2 erwartet, wird der Adapter crachen.

Nein, der Adapter überlebt diese Situation ohne mit der Wimper zu zucken. Ich habe es gerade getestet: Drei Mähzeiten an einem Tag, im Debug-Log wird der Counter korrekt auf 3 gestellt, in den Calendar-Objekten landen die beiden zeitlich ersten Mähzeiten. Der Adapter arbeitet weiter, als sei nichts Besonderes geschehen.

**Comment by Lucky-ESA** [comment]
Das ist schon mal gut. Hast du eventuell mal die API? Hast du eine Idee wie ich das per Datenpunkte darstellen könnte?

**Comment by hsteinme** [comment]
Nachtrag: rawMqtt.last_status.payload.cfg.sc.slotsxx werden tagesgerecht analog zu calendar.xxxday gefüllt.

**Comment by Lucky-ESA** [comment]
Stimmt, bearbeite die Slots vor der Erstellung von rawMqtt API. Da muss ich mir auch was einfallen lassen...

**Comment by hsteinme** [comment]
Schau mal bitte in Deinen persönlichen Nachrichtenpott im Roboter-Forum.

**Comment by Lucky-ESA** [comment]
Fixed with 3.0.0
