### ISSUE TITLE
Request for datapoint attribute extension for "mowTimeExtend"

### ISSUE THREAD

**Issue by HerrKlaus** [iobroker-community-adapters/ioBroker.worx#880]
Issue:
I visualize the object "mowTimeExtend" within the Lovelace gui as some kind of a scrollbar. When using the object as created from the adapter, the scrollbar is only visualized with changeable values from 0...100%.
As the value of this object can be set between -100%...+100% with a stepsize of 10% in the worx app, I have added the min/max/step attributes manually in the object attributes, to make the scrollbar fully usable.
Unfortunately, starting the adapter always overwrites manually added object attributes (section common) - I think for a good reason.

Request:
Please add the min/max/step attributes for "mowTimeExtend" in the adapter code to have to correct range defined:
    "min": -100,
    "max": 100,
    "step": 10

Affected:
helper.js around line 897

**Comment by Lucky-ESA** [comment]
Added in next Release

**Comment by HerrKlaus** [comment]
tested with Release 3.0.2, works perfectly
Big Thanks @Lucky-ESA
