### ISSUE TITLE
Version 3.0.2: Aus einem Account gelöschte Mäher werden weiterhin im Objektbaum geführt.

### ISSUE THREAD

**Issue by hsteinme** [iobroker-community-adapters/ioBroker.worx#922]
Ich nutze zwei Instanzen mower.0 und mower.1, die auf zwei getrennte Worx Accounts zugreifen. Ich habe nun einen Mäher aus dem Account zu worx.0 in den Account zu worx.1 übertragen. Nach einem Restart der beiden Instanzen ist der übertragene Mäher korrekterweise im Objektbaum zu worx.1 angelegt. Seine bisherigen Objekte in worx.0 existieren jedoch weiterhin - als tote Objekte. Auch ein erneutes Speichern der Einstellungen von worx.0 hilft nicht weiter. Manuelles Löschen ist also angesagt.

**Comment by Lucky-ESA** [comment]
Das ist Absicht. Könnte eventuell ein Warning ins Log schreiben aber löschen werde ich den Objektbaum nicht.
Vielle User haben noch Blocklys oder VIS zu diesen States und ein Löschen würde >99 Errors auslösen und somit > 99 Sentry Meldungen an den Javascript Entwickler (spreche aus Erfahrung).
